"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { BarChart3, Crown, Gamepad2, Gift, GraduationCap, Home, Medal, Trophy } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import NotificationBell from "@/components/learner-notification-bell";

type Learner = { id:string; full_name:string|null; xp:number; current_streak:number; challenge_points:number; avatar_url?:string|null; avatar_emoji?:string|null };
type Profile = { full_name:string|null; grade:string|null; avatar_url:string|null; avatar_emoji:string|null; xp:number; current_streak:number };
function gradeLabel(v:string|null|undefined){const m=String(v||"").match(/[1-7]/);return m?`Grade ${m[0]}`:"Student";}

export default function LeaderboardPage(){
 const [rows,setRows]=useState<Learner[]>([]); const [profile,setProfile]=useState<Profile|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const s=createClient(); if(!s){setLoading(false);return;} const {data:a}=await s.auth.getUser(); if(!a.user){window.location.href="/login";return;}
 const [{data:p},{data:r}]=await Promise.all([s.from("profiles").select("full_name,grade,avatar_url,avatar_emoji,xp,current_streak").eq("id",a.user.id).maybeSingle(),s.from("profiles").select("id,full_name,xp,current_streak,challenge_points,avatar_url,avatar_emoji").order("xp",{ascending:false}).limit(50)]);
 setProfile(p as Profile|null);setRows((r??[]) as Learner[]);setLoading(false);})();},[]);
 const first=(profile?.full_name||"Learner").split(" ")[0]; const avatar=profile?.avatar_url;
 const Avatar=({src,emoji,size="h-12 w-12"}:{src?:string|null;emoji?:string|null;size?:string})=>src?<img src={src} alt="" className={`${size} rounded-full object-cover`}/>:<div className={`${size} grid place-items-center rounded-full bg-[#dff7ff] text-2xl`}>{emoji||"🧑‍🎓"}</div>;
 return <main className="min-h-screen overflow-x-hidden bg-[#eef9ff] text-[#083d78]">
 <header className="sticky top-0 z-40 hidden h-[76px] lg:block border-b border-white/10 bg-[#073b73] text-white shadow-sm lg:h-[90px]"><div className="mx-auto flex h-full max-w-[1680px] items-center justify-between px-4 sm:px-6 lg:px-12">
 <Link href="/dashboard" className="flex min-w-0 shrink-0 items-center rounded-2xl bg-white px-3 py-1.5 shadow-md ring-1 ring-white/40 transition hover:shadow-lg"><img src="/fahi-hisaabu-logo-optimized.webp" onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = "/fahi-hisaabu-logo.png"; }} alt="Fahi Hisaabu" className="h-[44px] w-auto max-w-[200px] object-contain lg:h-[57px] lg:max-w-[220px]" /></Link>
 <nav className="hidden items-center gap-8 lg:flex"><Link href="/dashboard" className="flex items-center gap-3 px-4 py-7 text-lg font-bold"><Home size={25}/>Home</Link><Link href="/brain-games" className="flex items-center gap-3 px-4 py-7 text-lg font-bold"><Gamepad2 size={25}/>Games</Link><Link href="/leaderboard" className="relative flex items-center gap-3 px-4 py-7 text-lg font-black"><Trophy size={25}/>Leaderboard<span className="absolute bottom-0 left-4 right-4 h-1 rounded-full bg-yellow-400"/></Link><Link href="/rewards" className="flex items-center gap-3 px-4 py-7 text-lg font-bold"><Gift size={25}/>Rewards</Link><Link href="/progress" className="flex items-center gap-3 px-4 py-7 text-lg font-bold"><BarChart3 size={25}/>Progress</Link><Link href="/profile" className="flex items-center gap-3 px-4 py-7 text-lg font-bold"><GraduationCap size={25}/>Profile</Link></nav><NotificationBell/></div></header>
 <div className="mx-auto flex max-w-[1680px]">
 <section className="min-w-0 flex-1 px-4 py-6 pb-24 sm:px-6 lg:px-12 lg:py-10"><div className="mx-auto max-w-[1340px]">
 <div className="mb-7"><p className="text-sm font-black uppercase tracking-[.18em] text-[#197fe9]">Community</p><h1 className="mt-1 text-[38px] font-black tracking-tight sm:text-[48px] lg:text-[54px]">Leaderboard 🏆</h1><p className="mt-2 text-[18px] font-semibold text-[#6685a4] sm:text-[21px]">Celebrate progress, consistency and learning effort.</p></div>
 <div className="rounded-[32px] bg-gradient-to-r from-[#735fe6] to-[#197fe9] p-6 text-white shadow-lg sm:p-8"><div className="flex items-center gap-5"><div className="grid h-20 w-20 shrink-0 place-items-center rounded-3xl bg-white/15 text-4xl">🏆</div><div><h2 className="text-3xl font-black">Top Learners</h2><p className="mt-1 font-semibold text-white/80">{rows.length} learners ranked by learning XP</p></div></div></div>
 <div className="mt-6 overflow-hidden rounded-[30px] border border-[#d7eaf7] bg-white p-3 shadow-lg sm:p-5">{loading?<div className="p-10 text-center font-black text-[#6685a4]">Loading leaderboard…</div>:rows.length?<div className="space-y-3">{rows.map((r,i)=><div key={r.id} className={`flex items-center gap-3 rounded-2xl p-3 sm:gap-4 sm:p-4 ${i<3?"bg-[#f4f1ff]":"bg-[#f5fbff]"}`}><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white font-black shadow-sm">{i===0?<Crown size={22} className="text-yellow-500"/>:i===1?<Medal size={22}/>:i===2?<Medal size={22} className="text-orange-500"/>:i+1}</div><Avatar src={r.avatar_url} emoji={r.avatar_emoji}/><div className="min-w-0 flex-1"><p className="truncate text-[17px] font-black text-[#083d78] sm:text-[19px]">{r.full_name||"Learner"}</p><p className="text-xs font-bold text-[#6685a4]">🔥 {r.current_streak??0} day streak</p></div><div className="text-right"><p className="text-[16px] font-black text-[#735fe6] sm:text-lg">{r.xp??0} XP</p><p className="text-xs font-black text-[#e97b35]">🏆 {r.challenge_points??0} BCP</p></div></div>)}</div>:<div className="p-10 text-center font-black">No rankings yet</div>}</div>
 </div></section></div>
 <nav className="fixed inset-x-0 bottom-0 z-50 border-t border-[#cfe4f2] bg-white/95 px-2 pb-[calc(env(safe-area-inset-bottom)+6px)] pt-2 shadow-[0_-6px_20px_rgba(8,61,120,.10)] lg:hidden"><div className="mx-auto grid max-w-lg grid-cols-6"><Link href="/dashboard" className="flex flex-col items-center gap-1 py-1.5 text-[#526f89]"><Home size={22}/><span className="text-[11px] font-black">Home</span></Link><Link href="/brain-games" className="flex flex-col items-center gap-1 py-1.5 text-[#526f89]"><Gamepad2 size={22}/><span className="text-[11px] font-black">Games</span></Link><Link href="/leaderboard" className="flex flex-col items-center gap-1 py-1.5 text-[#197fe9]"><Trophy size={22}/><span className="text-[11px] font-black">Leaderboard</span></Link><Link href="/rewards" className="flex flex-col items-center gap-1 py-1.5 text-[#526f89]"><Gift size={22}/><span className="text-[11px] font-black">Rewards</span></Link><Link href="/progress" className="flex flex-col items-center gap-1 py-1.5 text-[#526f89]"><BarChart3 size={22}/><span className="text-[11px] font-black">Progress</span></Link><Link href="/profile" className="flex flex-col items-center gap-1 py-1.5 text-[#526f89]"><GraduationCap size={22}/><span className="text-[11px] font-black">Profile</span></Link></div></nav>
 </main>;
}