"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Brain, CheckCircle2, ChevronDown, Circle, Flame, Target, Trophy, Zap } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Topic={id:string;title:string;description:string;level:string;lessons:number;sort_order:number};
type Progress={topic_id:string;questions_answered:number;correct_answers:number;completed_at:string|null};
type Attempt={question_id:string;is_correct:boolean;created_at:string};
type Band="Unknown"|"Emerging"|"Developing"|"Mastered";

const topics=["place-value","addition-subtraction","multiplication","fractions"];
const styles=["from-violet-500 to-indigo-500","from-cyan-400 to-blue-500","from-amber-400 to-orange-500","from-pink-400 to-rose-500"];
function band(score:number):Band{return score===0?"Unknown":score<60?"Emerging":score<80?"Developing":"Mastered"}
function action(score:number):string{return score<50?"Remediate":score<70?"Practice":score<90?"Advance":"Challenge"}

export default function SkillsPage(){
 const [data,setData]=useState<Topic[]>([]),[progress,setProgress]=useState<Progress[]>([]),[attempts,setAttempts]=useState<Attempt[]>([]),[open,setOpen]=useState<string|null>(null),[loading,setLoading]=useState(true);
 const [profile,setProfile]=useState<{xp:number;current_streak:number;best_streak:number}|null>(null);
 useEffect(()=>{const s=createClient();if(!s){setLoading(false);return;}s.auth.getUser().then(async({data:u})=>{if(!u.user){location.href="/login";return;}const [{data:t},{data:p},{data:a},{data:pr}]=await Promise.all([s.from("learning_topics").select("id,title,description,level,lessons,sort_order").order("sort_order"),s.from("topic_progress").select("topic_id,questions_answered,correct_answers,completed_at").eq("user_id",u.user.id),s.from("question_attempts").select("question_id,is_correct,created_at").eq("user_id",u.user.id).order("created_at",{ascending:false}).limit(30),s.from("profiles").select("xp,current_streak,best_streak").eq("id",u.user.id).maybeSingle()]);setData((t??[]) as Topic[]);setProgress((p??[]) as Progress[]);setAttempts((a??[]) as Attempt[]);setProfile(pr);setLoading(false);});},[]);
 const rows=useMemo(()=>data.filter(t=>topics.includes(t.id)).map((t,i)=>{const p=progress.find(x=>x.topic_id===t.id);const answered=p?.questions_answered??0;const correct=p?.correct_answers??0;const score=answered?Math.round(correct/answered*100):0;return {...t,answered,correct,score,band:band(score),action:action(score),style:styles[i%styles.length]};}),[data,progress]);
 const weakest=[...rows].sort((a,b)=>a.score-b.score)[0]; const total=rows.reduce((n,r)=>n+r.answered,0), correct=rows.reduce((n,r)=>n+r.correct,0), overall=total?Math.round(correct/total*100):0;
 if(loading)return <main className="flex min-h-screen items-center justify-center bg-slate-50"><div className="rounded-3xl bg-white p-8 font-bold text-[#071b3a] shadow-xl">Loading your skill journey…</div></main>;
 return <main className="min-h-screen bg-gradient-to-br from-[#f7f7ff] via-white to-[#f0fbff]">
  <header className="border-b border-white/80 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><Link href="/dashboard" className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold text-slate-600 hover:bg-violet-50"><ArrowLeft size={17}/> Dashboard</Link><Link href="/mission" className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-black text-white shadow-lg shadow-violet-200">Practice <ArrowRight size={16}/></Link></div></header>
  <div className="mx-auto max-w-6xl px-5 py-8">
   <section className="rounded-[2rem] bg-gradient-to-br from-violet-600 via-indigo-600 to-blue-500 p-7 text-white shadow-2xl shadow-indigo-200 sm:p-9"><div className="flex flex-col gap-7 md:flex-row md:items-end md:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1.5 text-xs font-black uppercase tracking-wider"><Brain size={14}/> Skill journey</div><h1 className="mt-4 text-3xl font-black sm:text-5xl">See how your maths skills grow.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-indigo-100 sm:text-base">Every practice answer contributes to your mastery. Open a topic to see accuracy, learning stage and your next recommended action.</p></div><div className="grid grid-cols-3 gap-3"><div className="rounded-2xl bg-white/10 p-4 text-center"><Zap className="mx-auto text-yellow-300" size={20}/><b className="mt-1 block text-2xl">{profile?.xp??0}</b><span className="text-[11px] text-indigo-100">XP</span></div><div className="rounded-2xl bg-white/10 p-4 text-center"><Flame className="mx-auto text-orange-300" size={20}/><b className="mt-1 block text-2xl">{profile?.current_streak??0}</b><span className="text-[11px] text-indigo-100">Streak</span></div><div className="rounded-2xl bg-white/10 p-4 text-center"><Target className="mx-auto text-cyan-300" size={20}/><b className="mt-1 block text-2xl">{overall}%</b><span className="text-[11px] text-indigo-100">Accuracy</span></div></div></div></section>
   {weakest&&<section className="mt-6 rounded-3xl border border-amber-100 bg-gradient-to-r from-amber-50 to-orange-50 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-orange-600">Recommended next step</p><h2 className="mt-1 text-xl font-black text-[#071b3a]">Strengthen {weakest.title}</h2><p className="mt-1 text-sm text-slate-600">Your current mastery is {weakest.score}%. The adaptive engine recommends <b>{weakest.action}</b>.</p></div><Link href="/mission" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-orange-500 px-5 py-3 font-black text-white shadow-lg shadow-orange-200">Start practice <ArrowRight size={17}/></Link></div></section>}
   <div className="mt-7 space-y-4">{rows.map((r,i)=><section key={r.id} className="overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm"><button onClick={()=>setOpen(open===r.id?null:r.id)} className="w-full p-5 text-left sm:p-6"><div className="flex items-center gap-4"><div className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br ${r.style} text-white`}><span className="font-black">{i+1}</span></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-black text-[#071b3a]">{r.title}</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-600">{r.band}</span></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full bg-gradient-to-r ${r.style}`} style={{width:`${r.score}%`}}/></div><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{r.correct}/{r.answered} correct</span><span className="font-black text-[#071b3a]">{r.score}%</span></div></div><ChevronDown className={`shrink-0 text-slate-400 transition ${open===r.id?"rotate-180":""}`}/></div></button>{open===r.id&&<div className="border-t border-slate-100 bg-slate-50/60 px-5 pb-6 pt-5 sm:px-6"><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-white p-4"><CheckCircle2 className="text-emerald-500" size={20}/><p className="mt-3 text-sm font-black">Accuracy</p><p className="mt-1 text-2xl font-black text-[#071b3a]">{r.score}%</p><p className="text-xs text-slate-500">{r.answered} questions answered</p></div><div className="rounded-2xl bg-white p-4"><Trophy className="text-amber-500" size={20}/><p className="mt-3 text-sm font-black">Learning stage</p><p className="mt-1 text-2xl font-black text-[#071b3a]">{r.band}</p><p className="text-xs text-slate-500">Keep practising to progress.</p></div><div className="rounded-2xl bg-white p-4"><Target className="text-violet-500" size={20}/><p className="mt-3 text-sm font-black">Next action</p><p className="mt-1 text-2xl font-black text-[#071b3a]">{r.action}</p><Link href="/mission" className="mt-1 inline-flex items-center gap-1 text-xs font-black text-violet-600">Open adaptive mission <ArrowRight size={13}/></Link></div></div><div className="mt-4 rounded-2xl border border-violet-100 bg-violet-50 p-4"><p className="text-sm font-bold text-violet-900">{r.description||"Keep building this skill through focused practice."}</p><p className="mt-1 text-xs text-violet-700">Course level: {r.level} · {r.lessons} lessons</p></div></div>}</section>)}</div>
   {!rows.length&&<div className="rounded-3xl bg-white p-10 text-center shadow-sm"><Circle className="mx-auto text-slate-300" size={38}/><h2 className="mt-4 text-xl font-black text-[#071b3a]">Your skill map is ready</h2><p className="mt-2 text-sm text-slate-500">Complete your first adaptive mission to start building mastery.</p><Link href="/mission" className="mt-5 inline-flex items-center gap-2 rounded-2xl bg-violet-600 px-5 py-3 font-black text-white">Start mission <ArrowRight size={16}/></Link></div>}
  </div>
 </main>;
}