export const privacySections = [
  ["1. Information We Collect", "Fahi Hisaabu may collect account and profile information needed to provide the learning service, such as a learner name, grade, account identifier and optional profile image. The platform also records learning activity such as questions attempted, answers, progress, XP, streaks, achievements, rewards and game activity."],
  ["2. How We Use Information", "Learner information is used to provide and improve the learning experience, authenticate accounts, show appropriate learning activities, record progress, calculate rewards and streaks, maintain platform security, troubleshoot problems and support users."],
  ["3. Student and Child Privacy", "Fahi Hisaabu is designed for learners, including school-age children. We aim to collect only information reasonably needed to operate the learning experience. Children should use the service with the involvement of a parent, guardian or school where required by applicable rules."],
  ["4. Learning and Progress Data", "The platform may store question attempts, answers, scores, activity history, challenge completion, revision progress, game activity, XP, streaks and achievements so learners can continue their learning journey and view progress over time."],
  ["5. Profile Images", "Where profile photo upload is available, an uploaded image is used to personalize the learner profile. Learners should not upload images they do not have permission to use."],
  ["6. Service Providers", "Fahi Hisaabu uses technology service providers to operate the platform, including services for authentication, databases, storage and hosting. Information may be processed by those providers as necessary to deliver the service."],
  ["7. Security", "We use reasonable technical and organizational measures intended to protect learner information. No online service or storage system can guarantee absolute security."],
  ["8. Data Retention and Deletion", "Information may be retained while an account is active and as reasonably necessary to operate the service, maintain security, resolve issues or meet applicable obligations. A learner, parent or guardian may contact the platform operator to ask about access, correction or deletion options."],
  ["9. Changes to This Policy", "This Privacy Policy may be updated as Fahi Hisaabu develops. When material changes are made, the updated policy and effective date should be published on this page."],
  ["10. Contact", "Questions about privacy, learner information, access, correction or deletion should be directed to the Fahi Hisaabu platform operator. Official privacy contact details will be published here before public launch."]
];

export const paymentSections = [
  ["Delivery and Access Policy", "Fahi Hisaabu provides digital subscription access. No physical products are delivered. Bank transfer payments are activated after the payment receipt has been received and manually verified. Users should ensure that the payment information and receipt provided are accurate and clearly identifiable."],
  ["Refund, Exchange and Cancellation Policy", "If an online payment fails or is cancelled before successful completion, no subscription access will be granted and no payment will be considered completed. Once a subscription has been successfully activated and access to the digital learning service has been provided, payments are generally non-refundable, except where required by applicable law or where a payment has been charged incorrectly. Subscriptions may be cancelled to prevent future renewal where recurring payments are offered. Cancellation does not normally provide a refund for an already activated subscription period. As Fahi Hisaabu provides a digital service, product exchanges do not apply."],
  ["Keep Your Records", "Please keep a copy of your payment receipt, subscription confirmation, and these policies for your records."],
  ["Support", "For questions regarding payments, subscription activation, cancellations, refunds, or account access, please contact Fahi Hisaabu Support. Official support contact details will be published here before public launch."]
];
