"use client";

import { useState } from "react";
import { Check, CheckSquare, Loader2, X } from "lucide-react";
import { getGenerationReviewBatch, bulkReviewGeneratedQuestions, reviewGeneratedQuestion } from "@/lib/ai-generation-review";

export default function AIQuestionReviewPage() {
  const [jobId, setJobId] = useState(""); const [items, setItems] = useState<any[]>([]); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const load = async () => { if (!jobId.trim()) return; setBusy(true); setMessage(""); try { setItems(await getGenerationReviewBatch(jobId.trim())); setSelected([]); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not load batch."); } finally { setBusy(false); } };
  const refresh = async () => { try { setItems(await getGenerationReviewBatch(jobId.trim())); } catch {} };
  const bulk = async (status: "approved" | "rejected") => { if (!selected.length) return; setBusy(true); try { const n = await bulkReviewGeneratedQuestions(selected, status); setMessage(`${n} question(s) marked ${status}.`); await refresh(); setSelected([]); } catch (e) { setMessage(e instanceof Error ? e.message : "Review failed."); } finally { setBusy(false); } };
  const one = async (id: string, status: "approved" | "rejected") => { setBusy(true); try { await reviewGeneratedQuestion(id, status); await refresh(); } catch (e) { setMessage(e instanceof Error ? e.message : "Review failed."); } finally { setBusy(false); } };
  const toggle = (id: string) => setSelected((s) => s.includes(id) ? s.filter((x) => x !== id) : [...s, id]);
  const pending = items.filter((x) => x.validation_status !== "approved" && x.validation_status !== "rejected").length;
  return <main className="min-h-screen bg-slate-50 p-5 sm:p-8"><div className="mx-auto max-w-7xl">
    <header className="mb-6"><p className="text-xs font-black uppercase tracking-widest text-violet-600">Teacher AI workspace</p><h1 className="text-3xl font-black text-[#071b3a]">Generated Question Review</h1><p className="mt-1 text-sm text-slate-500">Review a generation batch before questions enter the published learning bank.</p></header>
    <div className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><div className="flex flex-col gap-3 sm:flex-row"><input value={jobId} onChange={(e)=>setJobId(e.target.value)} placeholder="Generation job UUID" className="flex-1 rounded-2xl border border-slate-200 px-4 py-3 font-semibold"/><button onClick={load} disabled={busy} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#071b3a] px-5 py-3 font-black text-white">{busy && <Loader2 size={16} className="animate-spin"/>} Load batch</button></div>{message && <p className="mt-3 text-sm font-bold text-slate-600">{message}</p>}</div>
    {items.length > 0 && <div className="mt-6 flex flex-wrap items-center gap-3"><span className="rounded-full bg-white px-4 py-2 text-sm font-black ring-1 ring-slate-200">{items.length} generated</span><span className="rounded-full bg-amber-50 px-4 py-2 text-sm font-black text-amber-700">{pending} awaiting decision</span><button disabled={!selected.length || busy} onClick={()=>bulk("approved")} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white disabled:opacity-40">Approve selected</button><button disabled={!selected.length || busy} onClick={()=>bulk("rejected")} className="rounded-xl bg-rose-600 px-4 py-2 text-sm font-black text-white disabled:opacity-40">Reject selected</button></div>}
    <div className="mt-5 space-y-4">{items.map((q, i) => <article key={q.id} className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><div className="flex gap-4"><button onClick={()=>toggle(q.id)} className={`mt-1 grid h-6 w-6 shrink-0 place-items-center rounded-md border ${selected.includes(q.id) ? "border-violet-600 bg-violet-600 text-white" : "border-slate-300"}`}>{selected.includes(q.id) && <Check size={15}/>}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Question {i+1} · {q.question_type} · {q.difficulty}</p><span className={`rounded-full px-3 py-1 text-xs font-black ${q.validation_status === "approved" ? "bg-emerald-50 text-emerald-700" : q.validation_status === "rejected" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"}`}>{q.validation_status}</span></div><h2 className="mt-2 text-lg font-black text-[#071b3a]">{q.prompt}</h2>{Array.isArray(q.options) && q.options.length > 0 && <ul className="mt-3 grid gap-2 sm:grid-cols-2">{q.options.map((o:any,j:number)=><li key={j} className="rounded-xl bg-slate-50 px-3 py-2 text-sm font-semibold">{String.fromCharCode(65+j)}. {typeof o === "string" ? o : JSON.stringify(o)}</li>)}</ul>}<div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase text-slate-400">AI confidence</p><p className="font-black">{q.ai_confidence == null ? "—" : `${Math.round(Number(q.ai_confidence)*100)}%`}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase text-slate-400">Quality score</p><p className="font-black">{q.quality_score ?? "Pending"}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase text-slate-400">Math check</p><p className="font-black">{q.mathematically_correct == null ? "Pending" : q.mathematically_correct ? "Pass" : "Review"}</p></div></div>{q.explanation && <p className="mt-4 text-sm text-slate-600"><strong>Explanation:</strong> {q.explanation}</p>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>one(q.id,"approved")} disabled={busy} className="inline-flex items-center gap-1 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white"><CheckSquare size={15}/> Approve</button><button onClick={()=>one(q.id,"rejected")} disabled={busy} className="inline-flex items-center gap-1 rounded-xl bg-rose-600 px-4 py-2 text-sm font-black text-white"><X size={15}/> Reject</button></div></div></div></article>)}</div>
    {!items.length && <div className="mt-6 rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm font-semibold text-slate-400">Enter a generation job UUID to review its questions.</div>}
  </div></main>;
}
