"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, Loader2, Trophy } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import LearnerBottomNav from "@/components/learner-bottom-nav";

type Q={id:string;prompt:string;options:any;answer:string;explanation:string};
type C={id:string;challenger_id:string;challenged_id:string;status:string;question_ids:string[];expires_at:string;challenger_correct:number;challenged_correct:number;challenger_points:number;challenged_points:number;winner_id:string|null;};
type P={id:string;display_name:string;avatar_emoji:string;avatar_url:string|null;};

export default function BuddyPlayPage(){
 const params=useSearchParams(); const id=params.get("id"); const [c,setC]=useState<C|null>(null); const [qs,setQs]=useState<Q[]>([]); const [answers,setAnswers]=useState<Record<string,string>>({}); const [submitted,setSubmitted]=useState(false); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [uid,setUid]=useState(""); const [profiles,setProfiles]=useState<Record<string,P>>({});
 useEffect(()=>{if(id)void load()},[id]);
 useEffect(()=>{if(!id||!c||c.status!=="pending"||!submitted)return;const timer=window.setInterval(async()=>{const s=createClient();const {data}=await s.from("buddy_challenges").select("*").eq("id",id).maybeSingle();if(data){setC(data as C);if(data.status==="completed"){setSubmitted(true)}}},5000);return()=>window.clearInterval(timer)},[id,c?.status,submitted]);
 async function load(){const s=createClient();if(!s){setError("Learning account is not configured.");setLoading(false);return}const u=await s.auth.getUser();if(!u.data.user){window.location.href="/login";return}setUid(u.data.user.id);const {data,error:e}=await s.from("buddy_challenges").select("*").eq("id",id).maybeSingle();if(e||!data){setError(e?.message||"Challenge not found.");setLoading(false);return}const challenge=data as C;setC(challenge);const profileIds=[challenge.challenger_id,challenge.challenged_id];const {data:p}=await s.from("profiles").select("id,display_name,avatar_emoji,avatar_url").in("id",profileIds);setProfiles(Object.fromEntries((p||[]).map((x:any)=>[x.id,x])));const ids=(challenge.question_ids||[]) as string[];const {data:q,error:qe}=await s.from("learning_questions").select("id,prompt,options,answer,explanation").in("id",ids);if(qe){setError(qe.message)}else{const ordered=ids.map(x=>(q||[]).find((v:any)=>v.id===x)).filter(Boolean) as Q[];setQs(ordered)}setLoading(false)}
 function choose(qid:string,value:string){if(!submitted)setAnswers(a=>({...a,[qid]:value}))}
 async function submit(){if(!c||qs.length!==5||Object.keys(answers).length!==5)return;setBusy(true);setError("");const s=createClient();const {data,error:e}=await s.rpc("submit_buddy_challenge",{p_challenge_id:c.id,p_answers:answers});if(e){setError(e.message);setBusy(false);return}setC(data as C);setSubmitted(true);setBusy(false)}
 if(loading)return <main className="grid min-h-screen place-items-center bg-[#eef9ff]"><Loader2 className="animate-spin text-[#197fe9]" size={36}/></main>;
 if(error&&!c)return <main className="grid min-h-screen place-items-center bg-[#eef9ff] p-5"><div className="max-w-md rounded-3xl bg-white p-8 text-center shadow-xl"><p className="font-bold text-rose-700">{error}</p><Link href="/peer-challenge" className="mt-5 inline-flex rounded-full bg-[#197fe9] px-6 py-3 font-black text-white">Back</Link></div></main>;
 const meChallenger=c?.challenger_id===uid; const myScore=meChallenger?c?.challenger_correct:c?.challenged_correct; const otherScore=meChallenger?c?.challenged_correct:c?.challenger_correct;
 if(c?.status==="pending"&&submitted)return <main className="grid min-h-screen place-items-center bg-[#eef9ff] p-5"><div className="w-full max-w-xl rounded-[32px] bg-white p-8 text-center shadow-xl"><div className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-[#eef8ff] text-4xl">⏳</div><h1 className="mt-5 text-3xl font-black">Challenge Sent!</h1><p className="mt-2 font-semibold leading-6 text-[#6685a4]">Your 5 answers are locked. Your classmate has up to 3 days to respond.</p><div className="mt-6 rounded-2xl bg-[#f9fdff] p-5"><p className="text-xs font-black uppercase tracking-wide text-[#6685a4]">Status</p><p className="mt-1 text-lg font-black text-[#197fe9]">Waiting for {profiles[c.challenged_id]?.display_name||"your classmate"}</p><div className="mt-4 flex items-center justify-center gap-3"><div className="grid h-12 w-12 place-items-center overflow-hidden rounded-2xl bg-[#eef8ff] text-2xl">{profiles[c.challenged_id]?.avatar_url?<img src={profiles[c.challenged_id].avatar_url!} alt="" className="h-full w-full object-cover"/>:<span>{profiles[c.challenged_id]?.avatar_emoji||"🧑‍🎓"}</span>}</div><span className="text-sm font-black text-[#6685a4]">Waiting for their answers…</span></div><p className="mt-3 text-sm font-semibold text-[#6685a4]">This screen checks automatically. You can also leave and return from Challenge History.</p></div><Link href="/peer-challenge/history" className="mt-6 inline-flex rounded-full bg-[#197fe9] px-7 py-3 font-black text-white">View Challenge History</Link><Link href="/peer-challenge" className="ml-2 mt-3 inline-flex rounded-full border-2 border-slate-200 bg-white px-7 py-3 font-black text-slate-600">Back</Link></div></main>;
 if(c?.status==="completed"&&submitted){const me=profiles[uid];const otherId=meChallenger?c.challenged_id:c.challenger_id;const other=profiles[otherId];const winner=c.winner_id;const draw=!winner;const iWon=winner===uid;return <main className="min-h-screen bg-[#eef9ff] p-5 text-[#083d78]"><div className="mx-auto flex min-h-[calc(100vh-40px)] max-w-xl items-center"><div className="w-full rounded-[36px] bg-white p-7 text-center shadow-xl sm:p-9"><div className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-yellow-100 text-4xl">{draw?"🤝":"🏆"}</div><p className="mt-5 text-xs font-black uppercase tracking-[.18em] text-[#ff6035]">Final Result</p><h1 className="mt-2 text-3xl font-black">{draw?"It's a Draw!":iWon?"You Won!":"Challenge Complete!"}</h1><p className="mt-2 font-semibold text-[#6685a4]">Both learners finished all 5 questions. BCP have been awarded.</p><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-3xl border-2 border-[#d7eaf7] bg-[#f8fcff] p-5"><div className="mx-auto grid h-16 w-16 place-items-center overflow-hidden rounded-2xl bg-[#eef8ff] text-3xl">{me?.avatar_url?<img src={me.avatar_url} alt="" className="h-full w-full object-cover"/>:<span>{me?.avatar_emoji||"🧑‍🎓"}</span>}</div><p className="mt-3 text-sm font-black text-[#6685a4]">You</p><p className="mt-1 truncate font-black">{me?.display_name||"You"}</p><p className="mt-2 text-4xl font-black text-[#197fe9]">{myScore}/5</p><p className="text-xs font-black text-[#6685a4]">{meChallenger?c.challenger_cp:c.challenged_cp} BCP</p></div><div className="rounded-3xl border-2 border-[#ffe0d5] bg-[#fffaf7] p-5"><div className="mx-auto grid h-16 w-16 place-items-center overflow-hidden rounded-2xl bg-[#fff0e9] text-3xl">{other?.avatar_url?<img src={other.avatar_url} alt="" className="h-full w-full object-cover"/>:<span>{other?.avatar_emoji||"🧑‍🎓"}</span>}</div><p className="mt-3 text-sm font-black text-[#6685a4]">Buddy</p><p className="mt-1 truncate font-black">{other?.display_name||"Your buddy"}</p><p className="mt-2 text-4xl font-black text-[#ff6035]">{otherScore}/5</p><p className="text-xs font-black text-[#6685a4]">{meChallenger?c.challenged_cp:c.challenger_cp} BCP</p></div></div><div className="mt-5 rounded-2xl bg-[#f5fbff] p-4 text-sm font-bold text-[#6685a4]">{draw?"Great job! You both scored the same.":iWon?"Nice work! Keep challenging your classmates.":"Good effort! Challenge your buddy again and try to beat your score."}</div><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:justify-center"><Link href="/peer-challenge/history" className="inline-flex justify-center rounded-full bg-[#197fe9] px-7 py-3 font-black text-white">Challenge History</Link><Link href="/peer-challenge" className="inline-flex justify-center rounded-full border-2 border-slate-200 bg-white px-7 py-3 font-black text-slate-600">Back to Buddy Challenge</Link></div></div></div></main>;}
 return <main className="min-h-screen bg-[#eef9ff] text-[#083d78]"><header className="sticky top-0 z-40 bg-[#073b73] text-white shadow-sm"><div className="mx-auto flex h-[76px] max-w-[1100px] items-center px-4"><Link href="/peer-challenge" className="mr-3 grid h-10 w-10 place-items-center rounded-full bg-white/10"><ArrowLeft size={20}/></Link><div><p className="text-xs font-black uppercase tracking-wider text-white/70">Buddy Challenge</p><h1 className="text-xl font-black">5 Questions • 1 Buddy</h1></div></div></header>
 <section className="mx-auto max-w-[900px] px-4 py-7 sm:px-6 lg:py-10"><div className="mb-5 flex items-center justify-between rounded-2xl bg-white px-5 py-4 shadow-sm"><div><p className="text-xs font-black uppercase text-[#ff6035]">Your turn</p><p className="font-black">{submitted?"Submitted":"Answer all 5 questions"}</p></div><div className="font-black text-[#197fe9]">{Object.keys(answers).length}/5</div></div>
 {c?.status==="pending"&&!meChallenger&&!submitted&&<div className="mb-5 rounded-2xl bg-amber-50 p-4 text-sm font-bold text-amber-800">This challenge is waiting for you to accept it before you can answer.</div>}
 <div className="space-y-4">{qs.map((q,i)=><div key={q.id} className="rounded-[28px] border border-[#d7eaf7] bg-white p-5 shadow-sm sm:p-7"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#ff6035] font-black text-white">{i+1}</span><h2 className="pt-1 text-lg font-black leading-7">{q.prompt}</h2></div>{Array.isArray(q.options)&&q.options.length>0?<div className="mt-5 grid gap-3 sm:grid-cols-2">{q.options.map((o:any,n:number)=>{const value=typeof o==="object"?String(o.id??o.text??o.value):String(o);const label=typeof o==="object"?String(o.text??o.label??o.value??o.id):String(o);return <button key={value} onClick={()=>choose(q.id,value)} disabled={submitted||(!meChallenger&&c.status==="pending")} className={`rounded-2xl border-2 px-4 py-3 text-left font-bold ${answers[q.id]===value?"border-[#197fe9] bg-[#eef8ff]":"border-[#dcecf7] bg-white"} disabled:opacity-60`}><span className="mr-2 inline-grid h-7 w-7 place-items-center rounded-lg bg-slate-100 text-xs font-black">{String.fromCharCode(65+n)}</span>{label}</button>})}</div>:<input value={answers[q.id]||""} onChange={e=>choose(q.id,e.target.value)} disabled={submitted||(!meChallenger&&c.status==="pending")} className="mt-5 h-13 w-full rounded-2xl border-2 border-slate-200 px-4 font-bold outline-none focus:border-[#197fe9]" placeholder="Type your answer"/>}</div>)}</div>
 {error&&<div className="mt-5 rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</div>}
 {submitted?<div className="mt-6 rounded-2xl bg-emerald-50 p-5 text-center font-black text-emerald-800"><Check className="mx-auto mb-2"/>{c?.status==="completed"?"Both learners have submitted. See the final result.":"Your 5 answers are locked in. Your buddy can now complete the challenge."}</div>:<button onClick={()=>void submit()} disabled={busy||Object.keys(answers).length!==5||(!meChallenger&&c?.status==="pending")} className="mt-6 w-full rounded-full bg-[#ff6035] px-6 py-4 text-lg font-black text-white shadow-md disabled:opacity-40">{busy?"Submitting...":"Submit 5 Answers"}</button>}
 <div className="mt-5 rounded-2xl bg-white p-4 text-center text-sm font-bold text-[#6685a4]">Answers are locked after submission • 5 questions • 3 challenges per day • Available 6 AM–10 PM</div>
 </section><LearnerBottomNav /></main>;
}