"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { ArrowLeft, Check, X, Loader2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
type C={id:string;challenger_id:string;challenged_id:string;status:string;challenge_type:string;question_ids:string[];expires_at:string;created_at:string};
type P={id:string;display_name:string;avatar_emoji:string;avatar_url:string|null};
export default function BuddyIncomingPage(){
 const [items,setItems]=useState<C[]>([]);const [profiles,setProfiles]=useState<Record<string,P>>({});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [error,setError]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){const s=createClient();if(!s)return;const u=await s.auth.getUser();if(!u.data.user){window.location.href="/login";return}const {data,error:e}=await s.from("buddy_challenges").select("*").eq("status","pending").eq("challenged_id",u.data.user.id).order("created_at",{ascending:false});if(e){setError(e.message);setLoading(false);return}const rows=(data||[]) as C[];setItems(rows);const ids=[...new Set(rows.map(x=>x.challenger_id))];if(ids.length){const {data:p}=await s.from("profiles").select("id,display_name,avatar_emoji,avatar_url").in("id",ids);setProfiles(Object.fromEntries((p||[]).map((x:any)=>[x.id,x])))}setLoading(false)}
 async function act(id:string,action:"accept"|"reject"){setBusy(id);setError("");const s=createClient();const {data,error:e}=await s.rpc(action==="accept"?"accept_buddy_challenge":"reject_buddy_challenge",{p_challenge_id:id});if(e){setError(e.message);setBusy("");return}if(action==="accept")window.location.href=`/peer-challenge/play?id=${data?.id||data?.[0]?.id||id}`;else{setItems(x=>x.filter(c=>c.id!==id));setBusy("")}}
 return <main className="min-h-screen bg-[#eef9ff] text-[#083d78]"><header className="bg-[#073b73] text-white shadow-sm"><div className="mx-auto flex h-[76px] max-w-[1000px] items-center px-4"><Link href="/peer-challenge" className="mr-3 grid h-10 w-10 place-items-center rounded-full bg-white/10"><ArrowLeft size={20}/></Link><div><p className="text-xs font-black uppercase tracking-wider text-white/70">Buddy Challenge</p><h1 className="text-xl font-black">Incoming Challenges</h1></div></div></header><section className="mx-auto max-w-[900px] px-4 py-8 sm:px-6 lg:py-12"><div className="rounded-[32px] bg-white p-5 shadow-sm sm:p-8"><h2 className="text-2xl font-black">Your Buddies want to challenge you! 🏆</h2>{error&&<div className="mt-5 rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</div>}{loading?<div className="grid place-items-center py-16"><Loader2 className="animate-spin text-[#197fe9]" size={34}/></div>:items.length===0?<div className="py-16 text-center"><div className="text-5xl">📭</div><p className="mt-4 font-black">No pending challenges</p><p className="mt-1 font-semibold text-[#6685a4]">New Buddy Challenges will appear here.</p></div>:<div className="mt-6 space-y-4">{items.map(c=>{const p=profiles[c.challenger_id];return <div key={c.id} className="flex flex-col gap-4 rounded-3xl border-2 border-[#dcecf7] bg-[#f9fdff] p-5 sm:flex-row sm:items-center"><div className="grid h-16 w-16 shrink-0 place-items-center rounded-2xl bg-[#fff0e9] text-3xl">{p?.avatar_url?<img src={p.avatar_url} alt={p.display_name} className="h-full w-full object-cover"/>:<span>{p?.avatar_emoji||"🧑‍🎓"}</span>}</div><div className="min-w-0 flex-1"><h3 className="text-lg font-black">{p?.display_name||"A learner"}</h3><p className="mt-1 text-sm font-bold text-[#6685a4]">5 questions • Reply within 3 days</p><p className="mt-1 text-xs font-semibold text-[#8ba2b7]">Challenge sent {new Date(c.created_at).toLocaleDateString()}</p></div><div className="flex gap-2"><button onClick={()=>void act(c.id,"reject")} disabled={!!busy} className="inline-flex items-center gap-1 rounded-full border-2 border-slate-200 bg-white px-4 py-2.5 text-sm font-black text-slate-600"><X size={16}/>Reject</button><button onClick={()=>void act(c.id,"accept")} disabled={!!busy} className="inline-flex items-center gap-1 rounded-full bg-[#ff6035] px-5 py-2.5 text-sm font-black text-white"><Check size={16}/>{busy===c.id?"Opening...":"Accept"}</button></div></div>})}</div>}</div></section></main>;
}