import Link from "next/link";
import { ArrowLeft,Brain,Play,Sparkles,Target,Trophy,Zap } from "lucide-react";
import { BRAIN_GAME_CATEGORIES,gamesForCategory,type BrainGameCategoryKey } from "@/lib/brain-games/catalog";
const order:BrainGameCategoryKey[]=["memory","flexibility","speed","attention","problem-solving","adventure"];
export default async function BrainGameCategoryPage({params}:{params:Promise<{category:string}>}){
 const {category:raw}=await params; const key=raw.toLowerCase() as BrainGameCategoryKey; const category=BRAIN_GAME_CATEGORIES[key]; if(!category)return <main className="grid min-h-screen place-items-center"><Link href="/brain-games">Back to Brain Games</Link></main>;
 const games=gamesForCategory(key);
 return <main className="min-h-screen overflow-x-hidden bg-gradient-to-b from-sky-50 to-white px-3 py-4 text-[#17395f] sm:px-6 sm:py-6"><div className="mx-auto max-w-7xl">
 <header className="flex items-center justify-between rounded-[22px] border-2 border-white bg-white/90 px-3 py-2.5 shadow-sm"><Link href="/brain-games" className="inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-2 text-sm font-black"><ArrowLeft size={17}/> Brain Games</Link><div className="hidden items-center gap-2 text-xs font-black text-slate-500 sm:flex"><Brain size={15}/> 30 UNIQUE GAMES • NO REPEAT CYCLE</div><Link href="/dashboard" className="px-3 py-2 text-sm font-black text-slate-500">Home</Link></header>
 <section className={`relative mt-4 overflow-hidden rounded-[34px] bg-gradient-to-br ${category.accent} px-5 py-6 text-white shadow-xl sm:px-8 sm:py-8`}><div className="relative flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-4"><div className="grid h-24 w-24 place-items-center rounded-[30px] border-4 border-white/60 bg-white/20 text-6xl">{category.icon}</div><div><div className="inline-flex items-center gap-2 rounded-full bg-white/20 px-3 py-1.5 text-[11px] font-black"><Sparkles size={13}/> MIND GAMES</div><h1 className="mt-2 text-4xl font-black sm:text-5xl">{category.title}</h1><p className="mt-2 max-w-2xl font-bold text-white/90">{category.subtitle}</p></div></div><div className="grid grid-cols-3 gap-2"><div className="rounded-2xl bg-white/15 p-3 text-center"><Trophy className="mx-auto"/><b className="text-xl">30</b><small className="block">Games</small></div><div className="rounded-2xl bg-white/15 p-3 text-center"><Target className="mx-auto"/><b className="text-xl">0</b><small className="block">Repeats</small></div><div className="rounded-2xl bg-white/15 p-3 text-center"><Zap className="mx-auto"/><b className="text-xl">900+</b><small className="block">XP</small></div></div></div></section>
 <nav className="mt-4 flex gap-2 overflow-x-auto pb-1">{order.map(item=>{const c=BRAIN_GAME_CATEGORIES[item];return <Link key={item} href={`/brain-games/${item}`} className={`shrink-0 rounded-full border-2 px-3 py-2 text-xs font-black ${item===key?"border-violet-400 bg-violet-500 text-white":"border-white bg-white text-slate-500"}`}><span className="mr-1">{c.icon}</span>{c.title}</Link>})}</nav>
 <section className="mt-5"><div className="mb-4"><div className="text-xs font-black uppercase tracking-[.18em] text-slate-400">30-game no-repeat cycle</div><h2 className="mt-1 text-2xl font-black sm:text-3xl">Choose a challenge 🎮</h2><p className="mt-1 text-sm font-semibold text-slate-500">Complete all 30 before starting a fresh category cycle.</p></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{games.map((game,index)=><article key={game.id} className="group overflow-hidden rounded-[24px] border-4 border-white bg-white shadow-[0_8px_22px_rgba(15,23,42,.08)] transition hover:-translate-y-1"><div className={`relative h-28 bg-gradient-to-br ${category.accent} p-4 text-white`}><span className="rounded-full bg-white/20 px-2 py-1 text-[9px] font-black">GAME {String(index+1).padStart(2,"0")} / 30</span><div className="mt-3 text-3xl">{category.icon}</div></div><div className="p-4"><div className="flex items-start justify-between gap-2"><h3 className="text-lg font-black text-slate-800">{game.title}</h3><span className="shrink-0 rounded-full bg-yellow-50 px-2 py-1 text-[10px] font-black text-amber-700">+{game.reward} XP</span></div><p className="mt-2 min-h-10 text-sm font-semibold leading-5 text-slate-500">{game.description}</p><Link href={`/brain-games/challenge/${game.id}`} className={`mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r ${category.accent} px-4 py-3 text-sm font-black text-white`}><Play size={15} fill="currentColor"/> Play</Link></div></article>)}</div></section>
 </div></main>
}