"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, ChevronRight, FileQuestion, Loader2, Sparkles, Wand2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { getUserRole } from "@/app/auth/role-router";

type Book={id:string;title:string;subject:string;grade:number;min_age:number|null;max_age:number|null;processing_status:string};
type Chapter={id:string;title:string;chapter_number:number;page_start:number|null;page_end:number|null};
type Objective={id:string;title:string;description:string|null;skill_code:string|null;cognitive_level:string|null};
type Question={id:string;prompt:string;question_type:string;difficulty:string;skill:string;topic:string;options:any;correct_answer:any;explanation:string;hint:string|null;interaction_config:any;source_reference:any;ai_confidence:number|null;validation_status:string};
const types=["multiple_choice","number_input","text_input","true_false","ordering","drag_drop","number_line","manipulatives","geometry","timed_challenge"];
const labels:Record<string,string>={multiple_choice:"Multiple Choice",number_input:"Number Input",text_input:"Text Input",true_false:"True / False",ordering:"Ordering",drag_drop:"Drag & Drop",number_line:"Number Line",manipulatives:"Manipulatives",geometry:"Geometry",timed_challenge:"Timed Challenge"};
const input="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-100";

export default function AIQuestionBuilder(){
 const supabase=createClient();
 const[books,setBooks]=useState<Book[]>([]),[chapters,setChapters]=useState<Chapter[]>([]),[objectives,setObjectives]=useState<Objective[]>([]),[questions,setQuestions]=useState<Question[]>([]);
 const[grade,setGrade]=useState("5"),[age,setAge]=useState("10"),[bookId,setBookId]=useState(""),[chapterId,setChapterId]=useState(""),[objectiveId,setObjectiveId]=useState(""),[difficulty,setDifficulty]=useState("adaptive"),[selectedTypes,setSelectedTypes]=useState<string[]>(["multiple_choice"]),[count,setCount]=useState("10");
 const[status,setStatus]=useState("Loading AI Question Builder…"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[jobId,setJobId]=useState("");
 const book=books.find(b=>b.id===bookId);
 async function loadBooks(){
  if(!supabase)return;
  const{data:{user}}=await supabase.auth.getUser(); if(!user){window.location.href="/login";return;}
  const role=await getUserRole(supabase,user.id); if(role!=="admin"&&role!=="teacher"){setStatus("Teacher or administrator access is required.");return;}
  const{data,error}=await supabase.from("books").select("id,title,subject,grade,min_age,max_age,processing_status").eq("is_active",true).eq("processing_status","indexed").order("grade").order("title");
  if(error){setStatus(error.message);return;} setBooks((data??[]) as Book[]);setStatus("");
 }
 useEffect(()=>{void loadBooks()},[]);
 useEffect(()=>{setAge(book?.min_age?String(book.min_age):age)},[bookId]);
 useEffect(()=>{(async()=>{if(!supabase||!bookId){setChapters([]);setObjectives([]);return;} const[{data:c},{data:o}]=await Promise.all([supabase.from("book_chapters").select("id,title,chapter_number,page_start,page_end").eq("book_id",bookId).order("chapter_number"),supabase.from("learning_objectives").select("id,title,description,skill_code,cognitive_level").eq("book_id",bookId).order("title")]);setChapters((c??[]) as Chapter[]);setObjectives((o??[]) as Objective[])})()},[bookId]);
 useEffect(()=>{if(!supabase||!chapterId)return; (async()=>{const{data}=await supabase.from("learning_objectives").select("id,title,description,skill_code,cognitive_level").eq("book_id",bookId).eq("chapter_id",chapterId).order("title");setObjectives((data??[]) as Objective[])})()},[chapterId]);
 function toggleType(t:string){setSelectedTypes(v=>v.includes(t)?v.filter(x=>x!==t):[...v,t])}
 async function generate(){
  if(!supabase||!bookId){setNotice("Select an indexed curriculum book first.");return;} if(!selectedTypes.length){setNotice("Select at least one question type.");return;}
  setBusy(true);setNotice("Gemini is generating curriculum-grounded questions…");setQuestions([]);
  try{const{data,error}=await supabase.functions.invoke("generate-ai-questions",{body:{book_id:bookId,chapter_id:chapterId||null,objective_id:objectiveId||null,grade:Number(grade),age:Number(age),count:Number(count),difficulty,question_types:selectedTypes}});if(error)throw error;if(data?.error)throw new Error(data.error+(data.details?`: ${data.details}`:""));setJobId(data.job_id||"");setQuestions((data.questions??[]) as Question[]);setNotice(`Generation complete: ${data.count??0} questions created and queued for validation.`)}catch(e){setNotice(e instanceof Error?e.message:"Unable to generate questions.")}finally{setBusy(false)}
 }
 const approved=questions.filter(q=>q.validation_status==="approved").length;
 const pending=questions.filter(q=>q.validation_status==="pending").length;
 const rejected=questions.filter(q=>q.validation_status==="rejected").length;
 const statusText=books.length?"":status;
 const currentChapter=useMemo(()=>chapters.find(c=>c.id===chapterId),[chapters,chapterId]);
 if(statusText)return <Gate text={statusText}/>;
 return <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-violet-50 p-5 pb-24 sm:p-8"><div className="mx-auto max-w-7xl">
  <header className="flex flex-wrap items-center justify-between gap-4"><Link href="/admin" className="inline-flex items-center gap-2 font-bold text-slate-600"><ArrowLeft size={18}/> Admin dashboard</Link><Link href="/admin/books" className="rounded-xl bg-white px-4 py-2 text-sm font-bold text-violet-700 ring-1 ring-slate-200">Book Library</Link></header>
  <section className="mt-7 rounded-[2rem] bg-gradient-to-br from-[#17234f] via-violet-700 to-blue-600 p-7 text-white shadow-2xl sm:p-10"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-black uppercase tracking-wider"><Sparkles size={14}/> Gemini curriculum engine</div><h1 className="mt-4 text-4xl font-black sm:text-5xl">AI Question Builder</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-indigo-100">Generate age-appropriate mathematics questions from your indexed curriculum books. Every request is grounded in the selected source, chapter and learning objective.</p></div><div className="rounded-3xl bg-white/10 p-5 text-center"><Wand2 className="mx-auto text-yellow-300" size={25}/><p className="mt-2 text-3xl font-black">{questions.length}</p><p className="text-xs font-bold text-indigo-100">Generated this run</p></div></div></section>
  {notice&&<div className="mt-5 flex gap-3 rounded-2xl border border-violet-100 bg-violet-50 px-5 py-4 text-sm font-bold text-violet-800"><CheckCircle2 size={18} className="shrink-0"/><span>{notice}</span></div>}
  <section className="mt-6 grid gap-6 lg:grid-cols-[1fr_1.15fr]">
   <div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100 sm:p-8"><div><p className="text-xs font-black uppercase tracking-wider text-violet-600">Generation controls</p><h2 className="mt-1 text-2xl font-black text-[#071b3a]">Build your question set</h2></div><div className="mt-6 grid gap-4 sm:grid-cols-2">
    <Field label="Grade"><select className={input} value={grade} onChange={e=>{setGrade(e.target.value);setBookId("")}}>{Array.from({length:13},(_,i)=><option key={i} value={i+1}>Grade {i+1}</option>)}</select></Field>
    <Field label="Age"><input className={input} value={age} onChange={e=>setAge(e.target.value)} type="number" min="3" max="25"/></Field>
    <Field label="Curriculum Book"><select className={input} value={bookId} onChange={e=>{setBookId(e.target.value);setChapterId("");setObjectiveId("")}}><option value="">Select indexed book…</option>{books.filter(b=>b.grade===Number(grade)).map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></Field>
    <Field label="Chapter"><select className={input} value={chapterId} disabled={!bookId} onChange={e=>{setChapterId(e.target.value);setObjectiveId("")}}><option value="">All chapters</option>{chapters.map(c=><option key={c.id} value={c.id}>Chapter {c.chapter_number}: {c.title}</option>)}</select></Field>
    <Field label="Learning Objective" wide><select className={input} value={objectiveId} disabled={!bookId} onChange={e=>setObjectiveId(e.target.value)}><option value="">Any objective</option>{objectives.map(o=><option key={o.id} value={o.id}>{o.title}{o.skill_code?` · ${o.skill_code}`:""}</option>)}</select></Field>
    <Field label="Difficulty"><select className={input} value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="adaptive">Adaptive</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></Field>
    <Field label="Number of Questions"><input className={input} value={count} onChange={e=>setCount(e.target.value)} type="number" min="1" max="100"/></Field>
   </div>
   <div className="mt-5"><p className="text-sm font-black text-[#071b3a]">Question Types</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{types.map(t=><label key={t} className={`flex cursor-pointer items-center gap-3 rounded-2xl border p-3 text-sm font-bold transition ${selectedTypes.includes(t)?"border-violet-300 bg-violet-50 text-violet-800":"border-slate-200 bg-white text-slate-600"}`}><input type="checkbox" checked={selectedTypes.includes(t)} onChange={()=>toggleType(t)} className="h-4 w-4 accent-violet-600"/><span>{labels[t]}</span></label>)}</div></div>
   <button disabled={busy||!bookId} onClick={()=>void generate()} className="mt-6 inline-flex items-center justify-center gap-3 rounded-2xl bg-gradient-to-r from-violet-600 to-blue-600 px-6 py-4 font-black text-white shadow-lg shadow-violet-200 disabled:cursor-not-allowed disabled:opacity-50">{busy?<Loader2 className="animate-spin" size={19}/>:<Wand2 size={19}/>} {busy?"Generating…":"Generate Questions"}</button>
   {!bookId&&<p className="mt-3 text-xs font-semibold text-slate-400">Upload and index a book in <Link href="/admin/books" className="text-violet-600 underline">Book Library</Link> before generating.</p>}
   </div>
   <div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-violet-600">Generation results</p><h2 className="mt-1 text-2xl font-black text-[#071b3a]">Question set</h2>{jobId&&<p className="mt-1 text-xs text-slate-400">Job {jobId.slice(0,8)}…</p>}</div><div className="flex gap-2 text-xs font-black"><span className="rounded-full bg-emerald-50 px-3 py-1 text-emerald-700">Approved {approved}</span><span className="rounded-full bg-amber-50 px-3 py-1 text-amber-700">Review {pending}</span><span className="rounded-full bg-red-50 px-3 py-1 text-red-700">Rejected {rejected}</span></div></div>
    {questions.length===0?<div className="mt-7 rounded-3xl border-2 border-dashed border-slate-200 p-12 text-center"><FileQuestion className="mx-auto text-slate-300" size={46}/><h3 className="mt-4 text-lg font-black text-[#071b3a]">Ready to generate</h3><p className="mt-2 text-sm text-slate-500">Select an indexed book and generation settings, then create a fresh curriculum-grounded set.</p></div>:<div className="mt-6 space-y-4">{questions.map((q,i)=><article key={q.id} className="rounded-3xl border border-slate-100 bg-slate-50/70 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-white px-3 py-1 text-[11px] font-black uppercase text-violet-700">Q{i+1}</span><span className="rounded-full bg-white px-3 py-1 text-[11px] font-bold text-slate-600">{labels[q.question_type]||q.question_type}</span><span className="rounded-full bg-white px-3 py-1 text-[11px] font-bold capitalize text-slate-600">{q.difficulty}</span></div><span className={`rounded-full px-3 py-1 text-[11px] font-black capitalize ${q.validation_status==="approved"?"bg-emerald-50 text-emerald-700":q.validation_status==="rejected"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{q.validation_status}</span></div><h3 className="mt-4 font-black leading-6 text-[#071b3a]">{q.prompt}</h3>{Array.isArray(q.options)&&q.options.length>0&&<div className="mt-3 grid gap-2 sm:grid-cols-2">{q.options.map((o:any,j:number)=><div key={j} className="rounded-xl bg-white px-3 py-2 text-sm font-semibold text-slate-600">{String.fromCharCode(65+j)}. {String(o)}</div>)}</div>}<div className="mt-4 grid gap-3 text-xs sm:grid-cols-2"><Meta label="Skill" value={q.skill}/><Meta label="Topic" value={q.topic}/><Meta label="Confidence" value={q.ai_confidence==null?"—":`${Math.round(q.ai_confidence*100)}%`}/><Meta label="Source" value={typeof q.source_reference==="string"?q.source_reference:JSON.stringify(q.source_reference)}/></div><details className="mt-4"><summary className="cursor-pointer text-xs font-black text-violet-700">Show answer & explanation</summary><div className="mt-3 rounded-2xl bg-white p-4 text-sm"><p><b>Answer:</b> {typeof q.correct_answer==="string"?q.correct_answer:JSON.stringify(q.correct_answer)}</p><p className="mt-2 text-slate-600"><b>Explanation:</b> {q.explanation}</p>{q.hint&&<p className="mt-2 text-slate-500"><b>Hint:</b> {q.hint}</p>}</div></details></article>)}</div>}
   </div>
  </section>
  {book&&<div className="mt-6 flex flex-wrap items-center gap-3 rounded-2xl bg-white px-5 py-4 text-xs font-semibold text-slate-500 ring-1 ring-slate-100"><span className="font-black text-violet-700">Source locked:</span><span>{book.title}</span>{currentChapter&&<><ChevronRight size={14}/><span>Chapter {currentChapter.chapter_number}: {currentChapter.title}</span></>}</div>}
 </div></main>
}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={wide?"sm:col-span-2":""}><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">{label}</span>{children}</label>}
function Meta({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white p-3"><p className="font-black uppercase tracking-wider text-[10px] text-slate-400">{label}</p><p className="mt-1 break-words font-semibold text-slate-600">{value||"—"}</p></div>}
function Gate({text}:{text:string}){return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto mt-24 max-w-xl rounded-3xl bg-white p-10 text-center shadow-xl"><Sparkles className="mx-auto text-violet-600" size={45}/><h1 className="mt-4 text-2xl font-black text-[#071b3a]">AI Question Builder</h1><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p><Link href="/dashboard" className="mt-6 inline-flex rounded-2xl bg-violet-600 px-5 py-3 font-black text-white">Back to dashboard</Link></div></main>}
