"use client";

import Link from "next/link";
import { ArrowLeft, Brain, CheckCircle2, Coins, RotateCcw, Sparkles, Star, Trophy, Zap } from "lucide-react";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function EvenOddPage() {
  const [started,setStarted]=useState(false),[time,setTime]=useState(45),[score,setScore]=useState(0),[combo,setCombo]=useState(0),[round,setRound]=useState(0),[num,setNum]=useState(24),[done,setDone]=useState(false),[saving,setSaving]=useState(false),[result,setResult]=useState<any>(null);
  const next=()=>setNum(Math.floor(Math.random()*99)+1);
  const answer=(choice:"even"|"odd")=>{ if(done)return; const correct=(num%2===0?"even":"odd")===choice; if(correct){setScore(s=>s+1);setCombo(c=>c+1)}else setCombo(0);setRound(r=>r+1);next(); if(round>=19) finish(score+(correct?1:0),20,Math.max(combo+(correct?1:0),0)); };
  const finish=async(s:number,total:number,c:number)=>{setDone(true);setSaving(true);try{const {data}=await createClient().rpc("complete_brain_game",{p_game_key:"brain-even-odd",p_score:s,p_total:total,p_combo:c});setResult(data?.[0]??null)}finally{setSaving(false)}};
  useEffect(()=>{if(!started||done)return; if(time<=0){finish(score,Math.max(round,1),combo);return} const id=setInterval(()=>setTime(t=>t-1),1000);return()=>clearInterval(id)},[started,done,time,score,round,combo]);
  const restart=()=>{setStarted(true);setTime(45);setScore(0);setCombo(0);setRound(0);setDone(false);setResult(null);next()};
  return <main className="min-h-screen bg-[radial-gradient(circle_at_20%_10%,#fff6a5,transparent_25%),linear-gradient(135deg,#effcff,#f7efff)] px-4 py-5 text-slate-800"><div className="mx-auto max-w-4xl"><Link href="/brain-games" className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 font-black shadow"><ArrowLeft size={18}/> Brain Arena</Link><section className="mt-5 overflow-hidden rounded-[38px] border-4 border-white bg-gradient-to-br from-violet-500 via-purple-600 to-fuchsia-500 p-6 text-white shadow-xl sm:p-10"><div className="flex items-center justify-between gap-4"><div><span className="rounded-full bg-white/20 px-3 py-1 text-xs font-black">ATTENTION • BRAIN GAME</span><h1 className="mt-3 text-4xl font-black sm:text-6xl">Even or Odd 🔢</h1><p className="mt-2 font-bold text-white/85">Think fast! Is the number even or odd?</p></div><Brain size={58}/></div></section>{!started&&!done?<div className="mt-6 rounded-[32px] bg-white p-8 text-center shadow-xl"><div className="text-7xl">⚡🔢⚡</div><h2 className="mt-4 text-3xl font-black">Ready for a quick brain workout?</h2><p className="mx-auto mt-2 max-w-xl font-semibold text-slate-500">45 seconds • 20 rounds • Build your combo</p><button onClick={restart} className="mt-6 rounded-2xl bg-gradient-to-r from-violet-500 to-fuchsia-500 px-10 py-4 text-lg font-black text-white shadow-lg">Start Game 🚀</button></div>:done?<Result result={result} saving={saving} score={score} onAgain={restart}/>:<div className="mt-6 rounded-[32px] bg-white p-5 shadow-xl sm:p-8"><div className="grid grid-cols-3 gap-3"><Stat icon="⏱️" value={`${time}s`} label="TIME"/><Stat icon="⭐" value={score} label="SCORE"/><Stat icon="🔥" value={combo} label="COMBO"/></div><div className="mt-7 rounded-[28px] bg-gradient-to-br from-slate-50 to-violet-50 p-8 text-center"><div className="text-sm font-black text-purple-500">ROUND {Math.min(round+1,20)} / 20</div><div className="mt-4 text-7xl font-black text-slate-800 sm:text-9xl">{num}</div><p className="mt-3 font-bold text-slate-500">Choose quickly!</p><div className="mt-7 grid grid-cols-2 gap-4"><button onClick={()=>answer("even")} className="rounded-3xl bg-cyan-500 px-5 py-6 text-2xl font-black text-white shadow-lg transition hover:-translate-y-1">EVEN</button><button onClick={()=>answer("odd")} className="rounded-3xl bg-orange-500 px-5 py-6 text-2xl font-black text-white shadow-lg transition hover:-translate-y-1">ODD</button></div></div></div>}<Link href="/brain-games" className="mx-auto mt-5 flex w-fit items-center gap-2 rounded-full px-4 py-2 font-bold text-slate-500"><ArrowLeft size={15}/> Back to Brain Arena</Link></div></main>
}
function Stat({icon,value,label}:{icon:string,value:any,label:string}){return <div className="rounded-2xl bg-slate-50 p-3 text-center"><div>{icon}</div><b className="block text-xl">{value}</b><span className="text-[10px] font-black text-slate-400">{label}</span></div>}
function Result({result,saving,score,onAgain}:{result:any,saving:boolean,score:number,onAgain:()=>void}){return <div className="mt-6 rounded-[32px] bg-white p-8 text-center shadow-xl"><div className="text-7xl">🏆</div><h2 className="mt-3 text-4xl font-black">Brain Workout Complete!</h2><p className="mt-2 font-semibold text-slate-500">You scored {score} correct answers.</p>{saving?<p className="mt-5 font-bold">Saving your rewards…</p>:<div className="mt-6 grid grid-cols-3 gap-3"><Stat icon="⭐" value={result?.stars??"—"} label="STARS"/><Stat icon="✨" value={`+${result?.xp??score*10}`} label="XP"/><Stat icon="🪙" value={`+${result?.coins??score*2}`} label="COINS"/></div>}<button onClick={onAgain} className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-gradient-to-r from-violet-500 to-fuchsia-500 px-8 py-4 font-black text-white"><RotateCcw size={18}/> Play Again</button></div>}
