"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Brain, CheckCircle2, CircleAlert, ClipboardCheck, Target, TrendingUp, UserRound, XCircle } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Student={id:string;name:string};
type Topic={id:string;title:string};
type Progress={topic_id:string;questions_answered:number;correct_answers:number;mastery:number};
type Attempt={question_id:string;is_correct:boolean;created_at:string};
type Intervention={id:number;intervention_type:string;topic_id:string|null;notes:string;status:string;created_at:string;completed_at:string|null};

const band=(m:number)=>m>=80?"Mastered":m>=60?"Developing":m>0?"Emerging":"Unknown";
const action=(m:number)=>m<50?"Remediate":m<70?"Practice":m<90?"Advance":"Challenge";

export default function StudentSupportProfile(){
 const [students,setStudents]=useState<Student[]>([]),[studentId,setStudentId]=useState(""),[topics,setTopics]=useState<Topic[]>([]),[progress,setProgress]=useState<Progress[]>([]),[attempts,setAttempts]=useState<Attempt[]>([]),[interventions,setInterventions]=useState<Intervention[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{(async()=>{const s=createClient();if(!s){setError("Supabase is not configured yet.");setLoading(false);return;}const{data:{user}}=await s.auth.getUser();if(!user){location.href="/login";return;}const{data:c,error:e}=await s.from("classes").select("id").eq("status","active");if(e||!c?.length){setError(e?.message||"No active classes found.");setLoading(false);return;}const roster=await Promise.all(c.map(x=>s.rpc("get_class_roster_report",{p_class_id:x.id})));const map=new Map<string,string>();roster.forEach(r=>(r.data??[]).forEach((x:any)=>map.set(x.student_id,x.display_name||"Student")));const list=[...map].map(([id,name])=>({id,name}));setStudents(list);if(list.length)setStudentId(list[0].id);const{data:t,error:te}=await s.from("learning_topics").select("id,title").order("sort_order");if(te)setError(te.message);setTopics((t??[]) as Topic[]);setLoading(false);})();},[]);
 useEffect(()=>{if(!studentId)return;(async()=>{const s=createClient();if(!s)return;setError("");const[{data:p,error:pe},{data:a,error:ae},{data:i,error:ie}]=await Promise.all([s.from("topic_progress").select("topic_id,questions_answered,correct_answers,mastery").eq("user_id",studentId),s.from("question_attempts").select("question_id,is_correct,created_at").eq("user_id",studentId).order("created_at",{ascending:false}).limit(20),s.rpc("get_teacher_interventions",{p_class_id:null,p_student_id:studentId,p_status:"open"})]);if(pe||ae)setError(pe?.message||ae?.message||"Could not load learner data.");if(ie)setError(ie.message);setProgress((p??[]) as Progress[]);setAttempts((a??[]) as Attempt[]);setInterventions((i??[]) as Intervention[]);})();},[studentId]);
 const selected=students.find(s=>s.id===studentId);const map=useMemo(()=>new Map(progress.map(p=>[p.topic_id,p])),[progress]);const overall=progress.length?Math.round(progress.reduce((n,p)=>n+p.mastery,0)/progress.length):0;const weakest=[...progress].sort((a,b)=>a.mastery-b.mastery)[0];const accuracy=attempts.length?Math.round(attempts.filter(a=>a.is_correct).length/attempts.length*100):0;
 if(loading)return <main className="flex min-h-screen items-center justify-center bg-slate-50"><div className="rounded-3xl bg-white p-8 font-black shadow">Loading student support profile…</div></main>;
 return <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-violet-50 p-5 pb-24 sm:p-8"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-4"><Link href="/teacher" className="inline-flex items-center gap-2 font-bold text-slate-600"><ArrowLeft size={18}/> Teacher Dashboard</Link><Link href="/teacher/interventions" className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-black text-white">Interventions <ArrowRight size={16}/></Link></header>
 <section className="mt-6 rounded-[2rem] bg-gradient-to-br from-[#17234f] via-violet-700 to-blue-600 p-7 text-white shadow-2xl sm:p-9"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-black uppercase tracking-wider"><UserRound size={14}/> Student support profile</div><h1 className="mt-4 text-4xl font-black">{selected?.name||"Learner"}</h1><p className="mt-2 text-indigo-100">One view for mastery, recent performance, interventions and the next best teaching action.</p></div><select value={studentId} onChange={e=>setStudentId(e.target.value)} className="rounded-2xl border-0 bg-white/15 px-4 py-3 font-black text-white outline-none"><option className="text-slate-900" value="">Select student</option>{students.map(s=><option className="text-slate-900" key={s.id} value={s.id}>{s.name}</option>)}</select></div></section>
 {error&&<div className="mt-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}
 <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={<Target/>} label="Overall mastery" value={`${overall}%`}/><Stat icon={<TrendingUp/>} label="Recent accuracy" value={`${accuracy}%`}/><Stat icon={<CheckCircle2/>} label="Recent answers" value={attempts.length}/><Stat icon={<ClipboardCheck/>} label="Open interventions" value={interventions.length}/></section>
 <section className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100 sm:p-8"><div className="flex items-center gap-3"><Brain className="text-violet-600"/><div><p className="text-xs font-black uppercase tracking-wider text-violet-600">Mastery map</p><h2 className="text-xl font-black text-[#071b3a]">Skills needing teacher attention</h2></div></div><div className="mt-6 space-y-3">{topics.map(t=>{const p=map.get(t.id);const m=Math.round(p?.mastery??0);return <div key={t.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-black text-[#071b3a]">{t.title}</p><p className="text-xs font-bold text-slate-400">{p?.questions_answered??0} questions · {p?.correct_answers??0} correct</p></div><div className="text-right"><p className="text-sm font-black text-violet-700">{m}%</p><p className="text-[11px] font-black text-slate-400">{band(m)} · {action(m)}</p></div></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-violet-500" style={{width:`${Math.min(100,m)}%`}}/></div></div>})}</div></div>
 <aside className="space-y-6"><div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-orange-100"><div className="flex items-center gap-3"><CircleAlert className="text-orange-500"/><h2 className="font-black text-[#071b3a]">Next best action</h2></div>{weakest?<><p className="mt-4 text-xs font-black uppercase tracking-wider text-slate-400">Weakest topic</p><p className="mt-1 text-2xl font-black text-orange-600">{topics.find(t=>t.id===weakest.topic_id)?.title||weakest.topic_id}</p><p className="mt-2 text-sm leading-6 text-slate-600">Current mastery is {Math.round(weakest.mastery)}%. Recommended action: <b>{action(weakest.mastery)}</b>.</p></>:<p className="mt-4 text-sm text-slate-500">No mastery data yet.</p>}<Link href="/teacher/interventions" className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-violet-600 px-4 py-3 font-black text-white">Create support action <ArrowRight size={16}/></Link></div><div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100"><h2 className="font-black text-[#071b3a]">Open interventions</h2><div className="mt-4 space-y-3">{interventions.length?interventions.map(i=><div key={i.id} className="rounded-2xl bg-slate-50 p-3"><p className="font-black text-violet-700">{i.intervention_type}{i.topic_id?` · ${i.topic_id}`:""}</p><p className="mt-1 text-sm text-slate-600">{i.notes||"No note added."}</p></div>):<p className="text-sm text-slate-500">No open interventions.</p>}</div></div></aside></section>
 <section className="mt-6 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100 sm:p-8"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-violet-600">Recent performance</p><h2 className="text-xl font-black text-[#071b3a]">Latest answer history</h2></div><Link href="/teacher/interventions" className="text-sm font-black text-violet-600">Manage support <ArrowRight className="inline" size={15}/></Link></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{attempts.slice(0,8).map((a,i)=><div key={`${a.question_id}-${i}`} className="flex items-center gap-3 rounded-2xl border border-slate-100 p-3"><span className={a.is_correct?"text-emerald-500":"text-red-500"}>{a.is_correct?<CheckCircle2 size={19}/>:<XCircle size={19}/>}</span><div><p className="text-xs font-black text-slate-600">{a.question_id}</p><p className="text-[11px] text-slate-400">{new Date(a.created_at).toLocaleString()}</p></div></div>)}</div></section>
 </div></main>;
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><div className="text-violet-600">{icon}</div><p className="mt-3 text-xs font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-2xl font-black text-[#071b3a]">{value}</p></div>}
