"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Home, BookOpen, ClipboardCheck, Gamepad2, Trophy, Gift, BarChart3, UserRound, ArrowRight, CheckCircle2, Target, Menu, X, GraduationCap } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import NotificationBell from "@/components/learner-notification-bell";

type Profile={full_name:string|null;grade:string|null;avatar_url:string|null;avatar_emoji:string|null};
const links=[{href:"/dashboard",label:"Dashboard",icon:Home},{href:"/learn",label:"My Learning",icon:BookOpen},{href:"/homework",label:"Homework",icon:ClipboardCheck},{href:"/progress",label:"Progress",icon:BarChart3},{href:"/brain-games",label:"Games",icon:Gamepad2},{href:"/leaderboard",label:"Leaderboard",icon:Trophy},{href:"/rewards",label:"Rewards",icon:Gift},{href:"/profile",label:"Profile",icon:UserRound}];
const groups=[{title:"Fahi Hisaabu Homework",icon:"📝",head:"bg-[#fff4dc]",number:"text-[#12355c]"},{title:"Homework from Teachers",icon:"🏫",head:"bg-[#e2f3ff]",number:"text-[#12355c]"},{title:"Homework from Parents",icon:"🏠",head:"bg-[#e3f8ec]",number:"text-[#12355c]"}];
export default function HomeworkPage(){
 const [profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[mobileMenu,setMobileMenu]=useState(false);
 useEffect(()=>{let active=true;(async()=>{const sb=createClient();if(!sb){setLoading(false);return;}const {data:{user}}=await sb.auth.getUser();if(!active)return;if(user){const {data}=await sb.from("profiles").select("full_name,grade,avatar_url,avatar_emoji").eq("id",user.id).maybeSingle();if(active)setProfile(data??{full_name:user.user_metadata?.full_name??"Learner",grade:null,avatar_url:null,avatar_emoji:"🧑‍🎓"});}if(active)setLoading(false);})();return()=>{active=false;};},[]);
 const grade=profile?.grade?.match(/[1-7]/)?.[0]??"—";
 return <main className="min-h-screen bg-[#eef9ff] text-[#102f57]">
 <header className="hidden lg:block sticky top-0 z-50 bg-[#0869c5] text-white shadow-md"><div className="mx-auto flex h-[72px] max-w-[1800px] items-center justify-between gap-3 px-4 lg:px-8"><Link href="/dashboard" className="flex shrink-0 items-center gap-2 text-xl font-black"><img src="/fahi-hisaabu-logo-optimized.webp" onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = "/fahi-hisaabu-logo.png"; }} alt="Fahi Hisaabu" className="h-11 w-auto max-w-[200px] object-contain sm:h-14 sm:max-w-[260px]"/></Link><nav className="hidden items-center gap-1 xl:flex">{[{href:"/dashboard",label:"Home",icon:Home},{href:"/learn",label:"Practice",icon:BookOpen},{href:"/homework",label:"Homework",icon:ClipboardCheck},{href:"/brain-games",label:"Games",icon:Gamepad2},{href:"/leaderboard",label:"Leaderboard",icon:Trophy},{href:"/rewards",label:"Rewards",icon:Gift}].map(item=><Link key={item.href} href={item.href} className={`flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold transition hover:bg-white/15 ${item.href==="/homework"?"bg-[#22a8f3]":""}`}><item.icon size={20}/>{item.label}</Link>)}</nav><div className="flex items-center gap-3"><NotificationBell/><Link href="/profile" className="hidden items-center gap-2 rounded-full bg-white/10 px-2 py-1.5 sm:flex">{profile?.avatar_url?<img src={profile.avatar_url} alt="" className="h-9 w-9 rounded-full object-cover"/>:<span className="grid h-9 w-9 place-items-center rounded-full bg-white text-xl">{profile?.avatar_emoji??"🧑‍🎓"}</span>}<span className="max-w-[90px] truncate text-sm font-black">{profile?.full_name?.split(" ")[0]??"Learner"}</span></Link><button type="button" className="rounded-lg p-2 xl:hidden" aria-label="Open navigation menu" aria-expanded={mobileMenu} onClick={()=>setMobileMenu(v=>!v)}>{mobileMenu?<X/>:<Menu/>}</button></div></div>{mobileMenu&&<nav className="grid grid-cols-2 gap-2 border-t border-white/20 p-3 xl:hidden">{links.map(item=><Link key={item.href} href={item.href} className={`flex items-center gap-2 rounded-xl p-3 font-bold ${item.href==="/homework"?"bg-[#22a8f3]":"bg-white/10"}`}><item.icon size={19}/>{item.label}</Link>)}</nav>}</header>
 <div className="mx-auto flex max-w-[1800px]"><aside className="hidden w-[214px] shrink-0 rounded-r-3xl border-r border-[#d5e8f7] bg-white px-3 py-6 shadow-sm lg:block"><nav className="sticky top-[94px] space-y-2">{links.map(item=><Link key={item.href} href={item.href} className={`flex items-center gap-3 rounded-2xl px-4 py-4 text-[15px] font-bold transition ${item.href==="/homework"?"bg-[#e0f2ff] text-[#0875dc]":"text-[#3c5977] hover:bg-[#f1f8ff]"}`}><item.icon size={22}/>{item.label}</Link>)}</nav></aside>
 <div className="min-w-0 flex-1 px-4 pb-16 pt-6 sm:px-7 lg:px-9">
 <div className="relative mb-6 overflow-hidden rounded-[28px] bg-gradient-to-r from-[#f6fcff] via-[#e6f7ff] to-[#bceaff] px-6 py-7 sm:px-9"><div className="relative z-10 flex items-center gap-5"><span className="text-6xl drop-shadow-md" aria-hidden="true">📚</span><div><h1 className="text-4xl font-black tracking-tight sm:text-5xl">Homework</h1><p className="mt-2 text-base font-medium text-[#4a6685] sm:text-lg">Complete your maths homework and see your progress.</p></div></div><div className="pointer-events-none absolute bottom-0 right-3 hidden items-end gap-2 text-6xl opacity-80 sm:flex" aria-hidden="true"><span>🌴</span><span className="text-4xl">⛵</span><span>🏝️</span></div></div>
 {!loading&&!profile&&<div className="mb-5 rounded-2xl border border-[#b8d9f5] bg-white p-5 font-semibold"><Link href="/dashboard" className="text-[#0875dc] underline">Sign in through the Dashboard</Link> to view your homework.</div>}
 <div className="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-[24px] border-2 border-[#a9d2f8] bg-white p-5 shadow-sm"><div><span className="rounded-full bg-[#fff2d9] px-3 py-1 text-xs font-black text-[#93610e]">INTERACTIVE SAMPLE</span><h2 className="mt-2 text-2xl font-black">Try a Grade 4 Homework</h2><p className="mt-1 text-sm font-semibold text-[#6685a4]">12 questions · 20 marks · Spiral notebook · Review and score</p></div><Link href="/homework/practice" className="rounded-2xl bg-[#197fe9] px-6 py-4 font-black text-white shadow-md">Start Sample →</Link></div><section className="mb-6 rounded-[26px] border border-[#cfe3f4] bg-white p-4 shadow-sm sm:p-6"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-3 text-2xl font-black"><span className="text-3xl">📝</span>My Homework</h2><span className="rounded-full border border-[#c9e4fa] bg-[#f7fcff] px-4 py-2 text-sm font-semibold text-[#42739c]">No assignments connected yet</span></div><div className="grid gap-5 md:grid-cols-3">{groups.map(group=><article key={group.title} className="overflow-hidden rounded-[20px] border border-[#d3e7f7] bg-white shadow-sm"><h3 className={`px-3 py-4 text-center text-base font-black ${group.head}`}>{group.title}</h3><div className="flex items-center justify-between gap-2 px-5 py-5"><div className="flex items-baseline gap-3"><span className={`text-5xl font-black ${group.number}`}>0</span><span className="font-medium text-[#5b7793]">Total</span></div><span className="text-5xl" aria-hidden="true">{group.icon}</span></div><div className="flex items-center gap-6 border-t border-[#e2eef7] px-5 py-3"><span className="w-6 text-2xl font-black text-[#35a653]">0</span><span className="font-medium text-[#5b7793]">Completed</span></div><div className="flex items-center gap-6 bg-[#eaf7ff] px-5 py-3"><span className="w-6 text-2xl font-black text-[#0875dc]">0</span><span className="font-medium text-[#0875dc]">Pending</span></div></article>)}</div><p className="mt-5 text-xs font-medium text-[#7890a7]">Assignment counts will update when the homework assignment system is connected.</p></section>
 <section className="rounded-[26px] border border-[#cfe3f4] bg-white p-4 shadow-sm sm:p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-4"><span className="text-5xl" aria-hidden="true">🎯</span><div><h2 className="text-2xl font-black">Self Practice</h2><p className="mt-1 text-sm font-medium text-[#5b7793]">Problem Sums + Mechanical Sums + High Ability Skills</p></div></div><Link href="/learn" className="font-bold text-[#0875dc] hover:underline">Explore Maths Skills →</Link></div><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-[20px] border border-[#f6e0c7] bg-[#fffdfa] p-5"><div className="flex items-center gap-4 rounded-2xl bg-gradient-to-r from-[#ffe88a] to-[#ffba27] p-4"><span className="text-6xl" aria-hidden="true">🏅</span><div><div className="text-lg font-black text-[#805400]">Mastered</div><div className="text-4xl font-black">—</div></div></div><div className="mt-6 flex flex-wrap gap-6"><span className="flex items-center gap-2 font-bold text-[#299b52]"><CheckCircle2 size={24}/> Passed —</span><span className="flex items-center gap-2 font-bold text-[#dc4c54]"><X size={24}/> Needs Improvement —</span></div><p className="mt-5 text-xs text-[#7890a7]">Skill mastery tracking is not connected yet.</p></div><div className="rounded-[20px] border border-[#f6e0c7] bg-[#fffdfa] p-5"><div className="mb-4 flex items-center gap-2"><Target size={24} className="text-[#ff8b1a]"/><h3 className="text-xl font-black">Maths Practice</h3></div><div className="h-7 overflow-hidden rounded-full border-4 border-[#e5eaf0] bg-white"><div className="h-full w-0 bg-[#ff981d]"/></div><p className="mt-3 text-sm text-[#5b7793]">Your skill progress will appear here.</p><Link href="/learn" className="mt-7 flex items-center justify-center gap-3 rounded-[22px] bg-gradient-to-b from-[#ffb335] to-[#ff691f] px-5 py-5 text-center text-2xl font-black text-white shadow-md transition hover:brightness-105">Start Practice <ArrowRight size={28}/></Link></div></div></section>
 </div></div></main>;
}
