"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { BookOpen, Home, Gamepad2, Trophy, Gift, BarChart3, GraduationCap, ArrowRight, ArrowLeft, CheckCircle2, Clock3, ClipboardList, LogOut } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import NotificationBell from "@/components/learner-notification-bell";

type Profile = {full_name:string|null;grade:string|null;avatar_url:string|null;avatar_emoji:string|null};
const sample = [
 {title:"Multiplication & Division",topic:"Multiply and divide whole numbers",questions:12,marks:20,icon:"✖️",tone:"amber"},
 {title:"Fractions",topic:"Identify and compare fractions",questions:10,marks:20,icon:"🧩",tone:"green"},
];
const nav = [{href:"/dashboard",label:"Home",icon:Home},{href:"/brain-games",label:"Games",icon:Gamepad2},{href:"/leaderboard",label:"Leaderboard",icon:Trophy},{href:"/rewards",label:"Rewards",icon:Gift},{href:"/progress",label:"Progress",icon:BarChart3},{href:"/profile",label:"Profile",icon:GraduationCap}];
export default function HomeworkPage(){
 const [profile,setProfile]=useState<Profile|null>(null);
 const [loading,setLoading]=useState(true);
 const [tab,setTab]=useState<"todo"|"completed"|"all">("todo");
 const [preview,setPreview]=useState<number|null>(null);
 useEffect(()=>{let live=true;(async()=>{const sb=createClient();if(!sb){setLoading(false);return;}const {data:{user}}=await sb.auth.getUser();if(!live)return;if(user){const {data}=await sb.from("profiles").select("full_name,grade,avatar_url,avatar_emoji").eq("id",user.id).maybeSingle();if(live)setProfile(data??{full_name:user.user_metadata?.full_name??"Learner",grade:null,avatar_url:null,avatar_emoji:"🧑‍🎓"});}if(live)setLoading(false);})();return()=>{live=false};},[]);
 const grade=profile?.grade?.match(/[1-7]/)?.[0]??"4";
 return <main className="min-h-screen bg-[#eef9ff] pb-24 text-[#083d78] lg:pb-0">
 <header className="sticky top-0 z-40 bg-[#073b73] text-white shadow-md"><div className="mx-auto flex min-h-[76px] max-w-[1680px] items-center justify-between gap-4 px-4 lg:px-12"><Link href="/dashboard"><img src="/dashboard-assets/dashboard-logo.svg" alt="Fahi Hisaabu" className="h-11 max-w-[190px] object-contain lg:h-14"/></Link><nav className="hidden items-center gap-6 xl:flex">{nav.map(n=><Link key={n.href} href={n.href} className="flex items-center gap-2 font-bold hover:text-yellow-200"><n.icon size={20}/>{n.label}</Link>)}</nav><div className="flex items-center gap-3"><NotificationBell/><Link href="/dashboard" className="rounded-full bg-white/15 px-3 py-2 text-sm font-black">Dashboard</Link></div></div></header>
 <div className="mx-auto max-w-[1480px] px-4 py-8 sm:px-8 lg:px-12">
 <div className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><Link href="/dashboard" className="mb-2 inline-flex items-center gap-1 text-sm font-bold text-[#3977a7]"><ArrowLeft size={16}/> Back to Dashboard</Link><h1 className="text-4xl font-black sm:text-5xl">My Homework</h1><p className="mt-2 text-lg font-semibold text-[#6685a4]">Your homework and independent maths practice</p></div><div className="rounded-3xl bg-white px-5 py-4 shadow-sm"><p className="text-sm font-bold text-[#6685a4]">Student</p><p className="text-xl font-black">{loading?"Loading…":profile?.full_name??"Learner"} · Grade {grade}</p></div></div>
 <section className="mb-8 overflow-hidden rounded-[28px] border border-[#cde3f5] bg-white shadow-sm"><div className="border-b border-[#dceaf5] bg-[#f5fbff] px-5 py-4 sm:px-8"><span className="inline-flex rounded-xl bg-[#197fe9] px-8 py-3 text-xl font-black text-white shadow-sm">Homework</span></div><div className="p-5 sm:p-8"><div className="mb-7 flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-black text-[#1169a5]">{new Date().toLocaleDateString("en-US",{month:"short",year:"numeric"})} Homework</h2><span className="rounded-full border border-[#cfe2f3] bg-[#f7fbff] px-5 py-2 text-sm font-bold text-[#527694]">0 homework pending next month</span></div>
 <div className="grid gap-5 lg:grid-cols-3">{[{title:"Fahi Hisaabu Homework",icon:"📝",color:"#eaf7ff"},{title:"Homework From Teachers",icon:"🏫",color:"#effaf3"},{title:"Homework From Parents",icon:"🏠",color:"#fff6e8"}].map(item=><div key={item.title} className="overflow-hidden rounded-2xl border border-[#d9e7f1] bg-white shadow-sm"><div className="border-b border-[#dceaf5] bg-[#f8fbff] px-4 py-4 text-center text-lg font-black text-[#496d8b]">{item.title}</div><div className="flex items-center justify-between px-6 py-5"><div className="flex items-baseline gap-3"><span className="text-5xl font-black">0</span><span className="font-bold text-[#6685a4]">Total</span></div><span className="text-5xl" aria-hidden="true">{item.icon}</span></div><div className="flex items-center gap-5 border-t border-[#e1ecf5] px-6 py-3"><span className="text-2xl font-black text-[#299b5d]">0</span><span className="font-semibold text-[#527694]">Completed</span></div><div className="flex items-center gap-5 bg-[#e8f7ff] px-6 py-3"><span className="text-2xl font-black text-[#1389c7]">0</span><span className="font-semibold text-[#527694]">Pending</span></div></div>)}</div>
 <p className="mt-5 text-sm font-semibold text-[#6d89a0]">Homework assignments will appear here when assignment management is connected. No sample assignments are counted as real homework.</p></div></section>
 <section className="overflow-hidden rounded-[28px] border border-[#cde3f5] bg-white shadow-sm"><div className="border-b border-[#dceaf5] bg-[#f5fbff] px-5 py-4 sm:px-8"><span className="inline-flex rounded-xl bg-[#197fe9] px-8 py-3 text-xl font-black text-white shadow-sm">Self Practice</span></div><div className="grid gap-8 p-5 sm:p-8 lg:grid-cols-2"><div className="lg:border-r lg:border-[#dceaf5] lg:pr-8"><h2 className="text-xl font-black text-[#1169a5]">Build your maths skills</h2><p className="mt-2 text-sm font-semibold text-[#6685a4]">Practise questions at your own pace</p><div className="mt-7 flex items-center gap-5 rounded-3xl bg-gradient-to-r from-[#fff2bd] to-[#ffdc67] p-5"><span className="text-6xl" aria-hidden="true">🏅</span><div><p className="text-lg font-black text-[#996100]">Skills Mastered</p><p className="text-4xl font-black text-[#083d78]">—</p></div></div><div className="mt-6 flex flex-wrap gap-6"><span className="flex items-center gap-2 font-black text-[#339e67]"><CheckCircle2 size={23}/> Passed: —</span><span className="flex items-center gap-2 font-black text-[#d85a61]">✖ Needs Improvement: —</span></div><p className="mt-4 text-sm text-[#6685a4]">Your skill totals will appear when practice tracking is connected.</p></div><div><h2 className="text-xl font-black text-[#1169a5]">Maths Practice</h2><p className="mt-2 text-sm font-semibold text-[#6685a4]">Choose activities suited to your grade</p><div className="mt-9 h-7 overflow-hidden rounded-full border-4 border-[#e3eaf0] bg-[#f7fafc]"><div className="h-full w-0 rounded-full bg-[#f59e0b]"/></div><p className="mt-3 text-sm font-semibold text-[#6685a4]">Skill progress will show here</p><Link href="/learn" className="mt-8 flex w-full items-center justify-center gap-3 rounded-3xl bg-[#ff9e22] px-6 py-5 text-2xl font-black text-white shadow-lg transition hover:bg-[#f18c0d]">Start Practice <ArrowRight size={25}/></Link></div></div></section>
 </div><nav className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-6 border-t border-[#cfe4f2] bg-white px-1 pb-[calc(env(safe-area-inset-bottom)+6px)] pt-2 shadow-lg lg:hidden">{nav.map(n=><Link key={n.href} href={n.href} className="flex flex-col items-center gap-1 py-1 text-[#526f89]"><n.icon size={20}/><span className="text-[10px] font-bold">{n.label}</span></Link>)}</nav>
 </main>;
}
