"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { BookOpen, Home, Gamepad2, Trophy, Gift, BarChart3, GraduationCap, ArrowRight, ArrowLeft, CheckCircle2, Clock3, ClipboardList, LogOut } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import NotificationBell from "@/components/learner-notification-bell";

type Profile = {full_name:string|null;grade:string|null;avatar_url:string|null;avatar_emoji:string|null};
const sample = [
 {title:"Multiplication & Division",topic:"Multiply and divide whole numbers",questions:12,marks:20,icon:"✖️",tone:"amber"},
 {title:"Fractions",topic:"Identify and compare fractions",questions:10,marks:20,icon:"🧩",tone:"green"},
];
const nav = [{href:"/dashboard",label:"Home",icon:Home},{href:"/brain-games",label:"Games",icon:Gamepad2},{href:"/leaderboard",label:"Leaderboard",icon:Trophy},{href:"/rewards",label:"Rewards",icon:Gift},{href:"/progress",label:"Progress",icon:BarChart3},{href:"/profile",label:"Profile",icon:GraduationCap}];
export default function HomeworkPage(){
 const [profile,setProfile]=useState<Profile|null>(null);
 const [loading,setLoading]=useState(true);
 const [tab,setTab]=useState<"todo"|"completed"|"all">("todo");
 const [preview,setPreview]=useState<number|null>(null);
 useEffect(()=>{let live=true;(async()=>{const sb=createClient();if(!sb){setLoading(false);return;}const {data:{user}}=await sb.auth.getUser();if(!live)return;if(user){const {data}=await sb.from("profiles").select("full_name,grade,avatar_url,avatar_emoji").eq("id",user.id).maybeSingle();if(live)setProfile(data??{full_name:user.user_metadata?.full_name??"Learner",grade:null,avatar_url:null,avatar_emoji:"🧑‍🎓"});}if(live)setLoading(false);})();return()=>{live=false};},[]);
 const grade=profile?.grade?.match(/[1-7]/)?.[0]??"4";
 return <main className="min-h-screen bg-[#eef9ff] pb-24 text-[#083d78] lg:pb-0">
 <header className="sticky top-0 z-40 bg-[#073b73] text-white shadow-md"><div className="mx-auto flex min-h-[76px] max-w-[1680px] items-center justify-between gap-4 px-4 lg:px-12"><Link href="/dashboard"><img src="/dashboard-assets/dashboard-logo.svg" alt="Fahi Hisaabu" className="h-11 max-w-[190px] object-contain lg:h-14"/></Link><nav className="hidden items-center gap-6 xl:flex">{nav.map(n=><Link key={n.href} href={n.href} className="flex items-center gap-2 font-bold hover:text-yellow-200"><n.icon size={20}/>{n.label}</Link>)}</nav><div className="flex items-center gap-3"><NotificationBell/><Link href="/dashboard" className="rounded-full bg-white/15 px-3 py-2 text-sm font-black">Dashboard</Link></div></div></header>
 <div className="mx-auto max-w-[1480px] px-4 py-8 sm:px-8 lg:px-12">
 <div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><Link href="/dashboard" className="mb-3 inline-flex items-center gap-1 text-sm font-bold text-[#3977a7]"><ArrowLeft size={16}/> Back to Dashboard</Link><h1 className="text-4xl font-black sm:text-5xl">📚 My Homework</h1><p className="mt-2 text-lg font-semibold text-[#6685a4]">Complete your maths homework and see your progress.</p></div><div className="rounded-3xl bg-white px-5 py-4 shadow-sm"><span className="text-sm font-bold text-[#6685a4]">Student</span><p className="text-xl font-black">{loading?"Loading…":profile?.full_name??"Please sign in"} · Grade {grade}</p></div></div>
 {!loading&&!profile?<div className="rounded-3xl border border-[#d7eaf7] bg-white p-8 text-center"><h2 className="text-2xl font-black">Sign in to view your homework</h2><p className="mt-2 text-[#6685a4]">Your assignments will appear here when homework is connected.</p><Link href="/dashboard" className="mt-5 inline-flex rounded-2xl bg-[#197fe9] px-6 py-3 font-black text-white">Go to Dashboard</Link></div>:<>
 <div className="mb-5 rounded-2xl border border-[#cde3f5] bg-[#e4f3ff] px-5 py-4 text-sm font-semibold text-[#32638b]"><strong>Homework page preview:</strong> The cards below are sample assignments, not homework assigned to your account. Teacher assignments, saved answers and grading will be connected next.</div>
 <div className="mb-6 flex flex-wrap gap-3">{([["todo","To Do"],["completed","Completed"],["all","All Homework"]] as const).map(([id,label])=><button key={id} onClick={()=>{setTab(id);setPreview(null)}} className={`rounded-full px-6 py-3 font-black transition ${tab===id?"bg-[#197fe9] text-white shadow-lg":"border border-[#cfe2f3] bg-white text-[#083d78] hover:bg-[#e7f4ff]"}`}>{label}{id==="todo"?" (2)":""}</button>)}</div>
 {preview!==null?<section className="rounded-[32px] border border-[#cfe2f3] bg-white p-6 shadow-lg sm:p-10"><button onClick={()=>setPreview(null)} className="mb-5 inline-flex items-center gap-2 font-bold text-[#197fe9]"><ArrowLeft size={18}/> Back to Homework</button><div className="mx-auto max-w-3xl rounded-[28px] border border-[#d8e8f6] bg-[#fbfdff] p-6 sm:p-10"><div className="mb-5 flex items-center gap-3"><BookOpen className="text-[#197fe9]"/><span className="text-sm font-black uppercase tracking-wide text-[#6685a4]">Sample worksheet preview</span></div><h2 className="text-3xl font-black">{sample[preview].title}</h2><p className="mt-2 text-[#6685a4]">Grade {grade} · {sample[preview].questions} questions · {sample[preview].marks} marks</p><div className="mt-8 rounded-2xl border border-[#dce8f2] bg-white p-8"><p className="font-black text-[#197fe9]">Question 1 (example only)</p><h3 className="mt-4 text-2xl font-black">What is 8 × 7?</h3><div className="mt-6 grid grid-cols-2 gap-3">{["54","56","64","48"].map(a=><div key={a} className="rounded-xl border-2 border-[#d9e8f7] p-4 text-center text-xl font-bold">{a}</div>)}</div></div><p className="mt-5 text-sm text-[#6685a4]">This is a visual preview only. Answers are not saved or submitted.</p></div></section>:tab==="completed"?<section className="rounded-[28px] border border-[#dceaf5] bg-white p-12 text-center shadow-sm"><CheckCircle2 className="mx-auto mb-4 text-[#35ad82]" size={48}/><h2 className="text-2xl font-black">No completed homework yet</h2><p className="mt-2 text-[#6685a4]">Your completed assignments and scores will appear here when homework is connected.</p></section>:<div className="grid gap-5">{sample.map((s,i)=><article key={s.title} className="flex flex-wrap items-center gap-5 rounded-[28px] border border-[#dceaf5] bg-white p-5 shadow-sm sm:p-7"><div className={`grid h-20 w-20 shrink-0 place-items-center rounded-2xl text-4xl ${i?"bg-[#e5f8ef]":"bg-[#fff1d3]"}`}>{s.icon}</div><div className="min-w-[200px] flex-1"><div className="mb-2 inline-flex rounded-full bg-[#fff3db] px-3 py-1 text-xs font-black text-[#a56a00]">Sample · To Do</div><h2 className="text-2xl font-black">{s.title}</h2><p className="mt-1 text-sm font-semibold text-[#6685a4]">Grade {grade} · {s.questions} questions · {s.marks} marks</p><p className="mt-1 text-sm text-[#6685a4]">{s.topic}</p></div><button onClick={()=>setPreview(i)} className="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-[#197fe9] px-6 py-4 text-lg font-black text-white shadow-md hover:bg-[#116ccc] sm:w-auto">Preview <ArrowRight size={19}/></button></article>)}</div>}
 </>}
 </div><nav className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-6 border-t border-[#cfe4f2] bg-white px-1 pb-[calc(env(safe-area-inset-bottom)+6px)] pt-2 shadow-lg lg:hidden">{nav.map(n=><Link key={n.href} href={n.href} className="flex flex-col items-center gap-1 py-1 text-[#526f89]"><n.icon size={20}/><span className="text-[10px] font-bold">{n.label}</span></Link>)}</nav>
 </main>;
}
