"use client";

import Link from "next/link";
import { ArrowLeft, Brain, CheckCircle2, RotateCcw, Sparkles, Trophy, Zap } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import MindSparkGate from "@/components/brain-games/MindSparkGate";

function shuffle<T>(a: T[]) { return [...a].sort(() => Math.random() - 0.5); }
function make() { const base = Math.floor(Math.random() * 40) + 5; const nums = [base, base + Math.floor(Math.random() * 8) + 2, base + Math.floor(Math.random() * 12) + 10, base + Math.floor(Math.random() * 18) + 18]; return shuffle(nums); }

export default function NumberOrderPage() {
  const [started,setStarted]=useState(false),[nums,setNums]=useState<number[]>([]),[chosen,setChosen]=useState<number[]>([]),[round,setRound]=useState(0),[score,setScore]=useState(0),[done,setDone]=useState(false),[saving,setSaving]=useState(false),[result,setResult]=useState<any>(null),[feedback,setFeedback]=useState<"none"|"correct"|"wrong">("none");
  const finishing=useRef(false);
  const start=()=>{finishing.current=false;setStarted(true);setDone(false);setRound(1);setScore(0);setChosen([]);setNums(make());setResult(null);setFeedback("none")};
  const finish=async(s:number,total:number)=>{if(finishing.current)return;finishing.current=true;setDone(true);setSaving(true);try{const{data}=await createClient().rpc("complete_brain_game",{p_game_key:"brain-number-order",p_score:s,p_total:total,p_combo:s});setResult(data?.[0]??null)}finally{setSaving(false)}};
  const pick=(n:number)=>{if(chosen.includes(n)||done||feedback!=="none")return;const c=[...chosen,n];setChosen(c);if(c.length===nums.length){const sorted=[...nums].sort((a,b)=>a-b);const ok=c.every((v,i)=>v===sorted[i]);const s=score+(ok?1:0);setFeedback(ok?"correct":"wrong");if(round>=8){setTimeout(()=>finish(s,8),550)}else{setTimeout(()=>{setScore(s);setRound(r=>r+1);setChosen([]);setNums(make());setFeedback("none")},650)}}};
  const Gate=({children}:{children:React.ReactNode})=><MindSparkGate gameKey="brain-number-order" gameTitle="Number Sequence" onStarted={start}>{children}</MindSparkGate>;
  return <main className="h-[100dvh] overflow-hidden bg-[radial-gradient(circle_at_8%_4%,#fff2a6,transparent_24%),radial-gradient(circle_at_94%_90%,#ffd7ea,transparent_25%),linear-gradient(135deg,#fffdf1,#eefcff)] px-2.5 py-2.5 text-slate-800 sm:px-5 sm:py-4"><div className="mx-auto flex h-full max-w-5xl flex-col overflow-hidden">
    <div className="flex shrink-0 items-center justify-between"><Link href="/brain-games" className="inline-flex items-center gap-1.5 rounded-full bg-white/90 px-2.5 py-1.5 text-xs font-black shadow-sm sm:px-3 sm:text-sm"><ArrowLeft size={15}/> Brain Arena</Link><Link href="/brain-games" className="rounded-full bg-white/80 px-3 py-1.5 text-[11px] font-black text-slate-500 shadow-sm">Exit</Link></div>
    <section className="mt-2.5 shrink-0 rounded-[24px] border-2 border-white bg-gradient-to-br from-amber-400 via-orange-500 to-rose-500 p-3.5 text-white shadow-xl sm:mt-4 sm:rounded-[30px] sm:p-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-white/20 text-2xl">🔢</div><div className="min-w-0 flex-1"><div className="text-[8px] font-black uppercase tracking-[.18em] text-white/75">NUMBER SEQUENCE</div><h1 className="text-xl font-black sm:text-3xl">Number Order</h1><p className="hidden text-xs font-bold text-white/85 sm:block">Think fast. Put every number in the correct order.</p></div><Brain className="hidden sm:block" size={26}/></div><div className="mt-2 grid grid-cols-3 gap-1.5"><Stat value={`${round}/8`} label="ROUND"/><Stat value={`⭐ ${score}`} label="SCORE"/><Stat value={`+${score*10}`} label="XP"/></div></section>
    {!started&&!done?<section className="mt-2.5 flex min-h-0 flex-1 items-center justify-center overflow-hidden rounded-[25px] bg-white/95 p-4 text-center shadow-xl sm:mt-4 sm:rounded-[32px] sm:p-8"><div className="w-full max-w-lg"><div className="text-5xl sm:text-7xl">🔢🧠✨</div><span className="mt-2 inline-flex rounded-full bg-orange-50 px-3 py-1 text-[9px] font-black uppercase tracking-widest text-orange-600">Brain Flexibility</span><h2 className="mt-2 text-2xl font-black sm:text-4xl">Can you put them in order?</h2><p className="mt-1.5 text-xs font-semibold leading-relaxed text-slate-500 sm:text-sm">Tap the numbers from smallest to largest. 8 rounds. Every correct round builds your brain streak.</p><div className="mx-auto mt-3 grid max-w-sm grid-cols-3 gap-2"><Tip icon="👀" text="Look"/><Tip icon="🧠" text="Think"/><Tip icon="👆" text="Order"/></div><Gate><span className="mt-4 inline-flex rounded-2xl bg-gradient-to-r from-orange-500 to-rose-500 px-7 py-3 text-sm font-black text-white shadow-lg transition hover:-translate-y-0.5 sm:mt-5 sm:px-8 sm:py-4 sm:text-base">Start Challenge 🚀</span></Gate></div></section>:
    done?<section className="mt-2.5 flex min-h-0 flex-1 items-center justify-center overflow-hidden rounded-[25px] bg-white/95 p-4 text-center shadow-xl sm:mt-4 sm:rounded-[32px] sm:p-8"><div className="w-full max-w-lg"><div className="animate-bounce text-5xl sm:text-6xl">🏆</div><h2 className="mt-1 text-2xl font-black sm:text-4xl">Order Master!</h2><p className="mt-1 text-xs font-semibold text-slate-500 sm:text-sm">You completed {score} of 8 rounds correctly.</p><div className="mt-2 text-xl">{score>=7?"⭐⭐⭐":score>=4?"⭐⭐":"⭐"}</div>{saving?<p className="mt-3 text-xs font-bold">Saving your rewards…</p>:<div className="mx-auto mt-3 grid max-w-md grid-cols-3 gap-2"><Mini i="⭐" v={result?.stars??Math.max(1,Math.ceil(score/3))} t="STARS"/><Mini i="✨" v={`+${result?.xp??score*10}`} t="XP"/><Mini i="🪙" v={`+${result?.coins??score*2}`} t="COINS"/></div>}<Gate><span className="mt-4 inline-flex items-center gap-2 rounded-2xl bg-gradient-to-r from-orange-500 to-rose-500 px-7 py-3 text-sm font-black text-white shadow-lg"><RotateCcw size={17}/> Play Again</span></Gate></div></section>:
    <section className="mt-2.5 flex min-h-0 flex-1 flex-col overflow-hidden rounded-[25px] bg-white/95 p-2.5 shadow-xl sm:mt-4 sm:rounded-[32px] sm:p-5"><div className="flex shrink-0 items-center justify-between"><span className="rounded-full bg-orange-50 px-2.5 py-1 text-[10px] font-black text-orange-600 sm:px-3 sm:text-xs">ROUND {round} / 8</span><span className="rounded-full bg-yellow-50 px-3 py-1 text-[10px] font-black text-amber-600">⭐ {score}</span></div><div className="mt-2 h-1.5 shrink-0 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-orange-400 to-rose-500 transition-all duration-500" style={{width:`${(round/8)*100}%`}}/></div><div className={`mt-2 flex min-h-0 flex-1 flex-col justify-center overflow-hidden rounded-[22px] p-3 text-center transition-all duration-300 sm:mt-4 sm:p-5 ${feedback==="correct"?"bg-gradient-to-br from-emerald-50 to-cyan-50":feedback==="wrong"?"bg-gradient-to-br from-rose-50 to-orange-50":"bg-gradient-to-br from-orange-50 via-yellow-50 to-rose-50"}`}><div className="text-[10px] font-black uppercase tracking-[.2em] text-orange-500 sm:text-xs">TAP SMALLEST → LARGEST</div><p className="mt-1 text-[10px] font-bold text-slate-400 sm:text-xs">Build the sequence one number at a time</p><div className="mt-3 flex min-h-14 flex-wrap items-center justify-center gap-1.5 sm:mt-5 sm:min-h-20 sm:gap-2">{chosen.map((n,i)=><div key={i} className="flex h-12 w-12 animate-[bounce_0.25s_ease-out] items-center justify-center rounded-2xl bg-orange-500 text-lg font-black text-white shadow-md sm:h-16 sm:w-16 sm:text-xl"><CheckCircle2 className="absolute opacity-0" size={18}/>{n}</div>)}{chosen.length===0&&<div className="text-xs font-bold text-slate-300">Your order appears here</div>}</div>{feedback!=="none"&&<div className={`mt-2 text-sm font-black sm:text-base ${feedback==="correct"?"text-emerald-600":"text-rose-600"}`}>{feedback==="correct"?"✨ Perfect order!":"💥 Not quite — next round!"}</div>}<div className="mx-auto mt-3 grid w-full max-w-xl grid-cols-2 gap-2 sm:mt-5 sm:grid-cols-4 sm:gap-3">{nums.map(n=><button key={n} disabled={chosen.includes(n)||feedback!=="none"} onClick={()=>pick(n)} className="min-h-14 rounded-2xl border-2 border-white bg-white text-2xl font-black text-orange-600 shadow-md transition hover:-translate-y-1 hover:shadow-lg active:scale-95 disabled:opacity-30 sm:min-h-16 sm:text-3xl">{n}</button>)}</div></div></section>}
    <Link href="/brain-games" className="mx-auto mt-1 flex shrink-0 items-center gap-1 px-3 py-1 text-[10px] font-bold text-slate-400 sm:mt-2 sm:text-xs"><ArrowLeft size={12}/> Brain Arena</Link>
  </div></main>;
}
function Stat({value,label}:{value:string,label:string}){return <div className="rounded-xl bg-white/15 px-2 py-1.5 text-center"><b className="block text-sm sm:text-base">{value}</b><span className="text-[7px] font-bold text-white/70 sm:text-[8px]">{label}</span></div>}
function Tip({icon,text}:{icon:string,text:string}){return <div className="rounded-2xl bg-slate-50 p-2.5"><div className="text-xl">{icon}</div><div className="text-[9px] font-black text-slate-500">{text}</div></div>}
function Mini({i,v,t}:{i:string,v:any,t:string}){return <div className="rounded-2xl bg-slate-50 p-2.5"><div>{i}</div><b className="block text-lg">{v}</b><span className="text-[8px] font-black text-slate-400">{t}</span></div>}
