"use client";

import Link from "next/link";
import { ArrowLeft, Brain, RotateCcw, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

function makeSequence(length:number){return Array.from({length},()=>Math.floor(Math.random()*9)+1)}
export default function FlashMemoryPage(){
 const [started,setStarted]=useState(false),[sequence,setSequence]=useState<number[]>([]),[input,setInput]=useState<number[]>([]),[round,setRound]=useState(1),[show,setShow]=useState(true),[score,setScore]=useState(0),[done,setDone]=useState(false),[saving,setSaving]=useState(false),[result,setResult]=useState<any>(null);
 const begin=()=>{const s=makeSequence(3);setSequence(s);setInput([]);setShow(true);setStarted(true);setRound(1);setScore(0);setDone(false)};
 useEffect(()=>{if(!show)return;const id=setTimeout(()=>setShow(false),Math.max(900,sequence.length*650));return()=>clearTimeout(id)},[show,sequence]);
 const pick=(n:number)=>{if(show||done)return;const next=[...input,n];setInput(next);const i=next.length-1;if(n!==sequence[i]){finish(score,round);return}if(next.length===sequence.length){const newScore=score+1;if(round>=8)finish(newScore,8);else{setScore(newScore);setRound(r=>r+1);const s=makeSequence(Math.min(3+Math.floor((round)/2),7));setSequence(s);setInput([]);setShow(true)}}};
 const finish=async(s:number,total:number)=>{setDone(true);setSaving(true);try{const {data}=await createClient().rpc("complete_brain_game",{p_game_key:"brain-flash-memory",p_score:s,p_total:total,p_combo:s});setResult(data?.[0]??null)}finally{setSaving(false)}};
 return <main className="min-h-screen bg-[radial-gradient(circle_at_80%_8%,#baf6ff,transparent_25%),linear-gradient(135deg,#eefcff,#f6efff)] px-4 py-5 text-slate-800"><div className="mx-auto max-w-4xl"><Link href="/brain-games" className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 font-black shadow"><ArrowLeft size={18}/> Brain Arena</Link><section className="mt-5 rounded-[38px] border-4 border-white bg-gradient-to-br from-blue-500 via-cyan-500 to-teal-500 p-7 text-white shadow-xl sm:p-10"><span className="rounded-full bg-white/20 px-3 py-1 text-xs font-black">MEMORY • BRAIN GAME</span><div className="mt-3 flex items-center justify-between"><div><h1 className="text-4xl font-black sm:text-6xl">Flash Memory ✨</h1><p className="mt-2 font-bold text-white/90">Watch the numbers. Remember the sequence. Rebuild it!</p></div><Brain size={56}/></div></section>{!started&&!done?<Intro onStart={begin}/>:done?<Result score={score} result={result} saving={saving} again={begin}/>:<div className="mt-6 rounded-[32px] bg-white p-6 shadow-xl sm:p-9"><div className="flex items-center justify-between"><div className="font-black text-cyan-600">ROUND {round} / 8</div><div className="rounded-full bg-yellow-100 px-4 py-2 font-black">⭐ {score}</div></div><div className="mt-5 rounded-[30px] bg-gradient-to-br from-slate-900 to-blue-900 p-8 text-center"><div className="text-sm font-black tracking-widest text-cyan-300">{show?"MEMORIZE!":"YOUR TURN"}</div><div className="mt-6 flex min-h-28 flex-wrap items-center justify-center gap-3">{show?sequence.map((n,i)=><div key={i} className="flex h-20 w-20 items-center justify-center rounded-2xl bg-white text-4xl font-black text-blue-600 shadow-lg">{n}</div>):input.map((n,i)=><div key={i} className="flex h-16 w-16 items-center justify-center rounded-2xl bg-cyan-400 text-2xl font-black text-white">{n}</div>)}</div></div><div className="mt-5 grid grid-cols-3 gap-3 sm:grid-cols-5">{[1,2,3,4,5,6,7,8,9].map(n=><button key={n} onClick={()=>pick(n)} className="rounded-2xl bg-slate-100 py-5 text-2xl font-black shadow-sm transition hover:-translate-y-1 hover:bg-cyan-100">{n}</button>)}</div></div>}<Link href="/brain-games" className="mx-auto mt-5 flex w-fit items-center gap-2 px-4 py-2 font-bold text-slate-500"><ArrowLeft size={15}/> Brain Arena</Link></div></main>
}
function Intro({onStart}:{onStart:()=>void}){return <div className="mt-6 rounded-[32px] bg-white p-8 text-center shadow-xl"><div className="text-7xl">👀🔢✨</div><h2 className="mt-4 text-3xl font-black">Can your memory keep up?</h2><p className="mt-2 font-semibold text-slate-500">8 rounds • sequences get longer • no rush, just remember</p><button onClick={onStart} className="mt-6 rounded-2xl bg-gradient-to-r from-blue-500 to-teal-500 px-10 py-4 font-black text-white shadow-lg">Start Memory Game 🚀</button></div>}
function Result({score,result,saving,again}:{score:number,result:any,saving:boolean,again:()=>void}){return <div className="mt-6 rounded-[32px] bg-white p-8 text-center shadow-xl"><div className="text-7xl">🧠🏆</div><h2 className="mt-3 text-4xl font-black">Memory Master!</h2><p className="mt-2 font-semibold text-slate-500">You remembered {score} rounds.</p>{saving?<p className="mt-5 font-bold">Saving rewards…</p>:<div className="mt-6 grid grid-cols-3 gap-3"><Mini icon="⭐" v={result?.stars??"—"} t="STARS"/><Mini icon="✨" v={`+${result?.xp??score*10}`} t="XP"/><Mini icon="🪙" v={`+${result?.coins??score*2}`} t="COINS"/></div>}<button onClick={again} className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-gradient-to-r from-blue-500 to-teal-500 px-8 py-4 font-black text-white"><RotateCcw size={18}/> Play Again</button></div>}
function Mini({icon,v,t}:{icon:string,v:any,t:string}){return <div className="rounded-2xl bg-slate-50 p-3"><div>{icon}</div><b className="block text-xl">{v}</b><span className="text-[10px] font-black text-slate-400">{t}</span></div>}
