import Link from "next/link";
import { ArrowLeft,Brain,Play,Sparkles,Target,Trophy,Zap } from "lucide-react";
import { BRAIN_GAME_CATEGORIES,gamesForCategory,type BrainGameCategoryKey } from "@/lib/brain-games/catalog";
export default function CategoryCatalogPage({categoryKey}:{categoryKey:BrainGameCategoryKey}){
 const category=BRAIN_GAME_CATEGORIES[categoryKey]; const games=gamesForCategory(categoryKey);
 return <main className="min-h-screen bg-gradient-to-b from-sky-50 to-white px-3 py-4 text-[#17395f] sm:px-6"><div className="mx-auto max-w-7xl">
 <header className="flex items-center justify-between rounded-[22px] bg-white px-3 py-2.5 shadow-sm"><Link href="/brain-games" className="inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-2 text-sm font-black"><ArrowLeft size={17}/> Mind Games</Link><div className="hidden items-center gap-2 text-xs font-black text-slate-500 sm:flex"><Brain size={15}/> 30 UNIQUE GAMES</div><Link href="/dashboard" className="px-3 py-2 text-sm font-black text-slate-500">Home</Link></header>
 <section className={`mt-4 rounded-[34px] bg-gradient-to-br ${category.accent} px-5 py-6 text-white shadow-xl sm:px-8`}><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div className="text-5xl">{category.icon}</div><div className="mt-2 inline-flex items-center gap-2 rounded-full bg-white/20 px-3 py-1 text-[11px] font-black"><Sparkles size={13}/> MIND GAMES</div><h1 className="mt-2 text-4xl font-black sm:text-5xl">{category.title}</h1><p className="mt-2 font-bold text-white/90">{category.subtitle}</p></div><div className="grid grid-cols-3 gap-2"><div className="rounded-2xl bg-white/15 p-3 text-center"><Trophy className="mx-auto"/><b className="text-xl">30</b><small className="block">Games</small></div><div className="rounded-2xl bg-white/15 p-3 text-center"><Target className="mx-auto"/><b className="text-xl">0</b><small className="block">Repeats</small></div><div className="rounded-2xl bg-white/15 p-3 text-center"><Zap className="mx-auto"/><b className="text-xl">900+</b><small className="block">XP</small></div></div></div></section>
 <section className="mt-5"><h2 className="text-2xl font-black">Choose a challenge 🎮</h2><p className="mt-1 text-sm font-semibold text-slate-500">30-game no-repeat cycle.</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{games.map((game,index)=><article key={game.id} className="overflow-hidden rounded-[24px] border-4 border-white bg-white shadow-lg"><div className={`h-24 bg-gradient-to-br ${category.accent} p-4 text-white`}><span className="rounded-full bg-white/20 px-2 py-1 text-[9px] font-black">GAME {String(index+1).padStart(2,"0")} / 30</span><div className="mt-3 text-3xl">{category.icon}</div></div><div className="p-4"><div className="flex justify-between gap-2"><h3 className="text-lg font-black text-slate-800">{game.title}</h3><span className="shrink-0 rounded-full bg-yellow-50 px-2 py-1 text-[10px] font-black text-amber-700">+{game.reward} XP</span></div><p className="mt-2 min-h-10 text-sm font-semibold text-slate-500">{game.description}</p><Link href={`/brain-games/challenge/${game.id}`} className={`mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r ${category.accent} px-4 py-3 text-sm font-black text-white`}><Play size={15} fill="currentColor"/> Play</Link></div></article>)}</div></section>
 </div></main>
}