"use client";

import { useState } from "react";
import { Check, Loader2, Sparkles, X } from "lucide-react";
import AIQuestionImprovementPanel from "@/components/ai-question-improvement-panel";
import { reviewGeneratedQuestion } from "@/lib/ai-generation-review";
import type { QuestionBankItem } from "@/lib/question-bank-management";

export default function AIGenerationReviewCard({ question, onRefresh }: { question: any; onRefresh: () => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [improving, setImproving] = useState(false); const [message, setMessage] = useState("");
  const approve = async () => { setBusy(true); try { await reviewGeneratedQuestion(question.id, "approved"); await onRefresh(); } catch (e) { setMessage(e instanceof Error ? e.message : "Approval failed."); } finally { setBusy(false); } };
  const reject = async () => { setBusy(true); try { await reviewGeneratedQuestion(question.id, "rejected"); await onRefresh(); } catch (e) { setMessage(e instanceof Error ? e.message : "Rejection failed."); } finally { setBusy(false); } };
  const asBankQuestion = (): QuestionBankItem => ({ id: question.id, title: question.prompt.slice(0,72), subject: question.subject || "Mathematics", topic: question.topic || "General", difficulty: question.difficulty === "hard" ? "challenge" : question.difficulty === "easy" ? "foundation" : question.difficulty === "medium" ? "developing" : "proficient", status: "draft", version: 1, tags: [], missionIds: [], usageCount: 0, correctCount: 0, createdAt: question.created_at || new Date().toISOString(), updatedAt: new Date().toISOString(), prompt: question.prompt, options: question.options || [], answer: typeof question.correct_answer === "string" ? question.correct_answer : JSON.stringify(question.correct_answer), explanation: question.explanation || "", hint: question.hint, interaction_type: question.question_type, interaction_config: question.interaction_config });
  const applyImprovement = async (improved: QuestionBankItem) => { setBusy(true); try { await reviewGeneratedQuestion(question.id, "needs_review", "AI revision approved by teacher; deterministic validation and Question Bank save remain required."); setMessage("Improved draft accepted. It remains under review until validation/publishing is completed."); setImproving(false); await onRefresh(); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not save review state."); } finally { setBusy(false); } };
  return <article className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">{question.question_type} · {question.difficulty}</p><h2 className="mt-1 text-lg font-black text-[#071b3a]">{question.prompt}</h2></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-black text-amber-700">{question.validation_status}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="AI confidence" value={question.ai_confidence == null ? "—" : `${Math.round(Number(question.ai_confidence)*100)}%`}/><Metric label="Quality" value={question.quality_score ?? "Pending"}/><Metric label="Math" value={question.mathematically_correct == null ? "Pending" : question.mathematically_correct ? "Pass" : "Review"}/></div><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={approve} className="inline-flex items-center gap-1 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white"><Check size={15}/> Approve</button><button disabled={busy} onClick={reject} className="inline-flex items-center gap-1 rounded-xl bg-rose-600 px-4 py-2 text-sm font-black text-white"><X size={15}/> Reject</button><button disabled={busy} onClick={()=>setImproving((v)=>!v)} className="inline-flex items-center gap-1 rounded-xl bg-violet-600 px-4 py-2 text-sm font-black text-white"><Sparkles size={15}/> {improving ? "Close AI improvement" : "Improve with AI"}</button></div>{message && <p className="mt-3 text-sm font-bold text-slate-600">{message}</p>}{improving && <AIQuestionImprovementPanel question={asBankQuestion()} onApply={applyImprovement}/>} </article>;
}
function Metric({label,value}:{label:string;value:string}) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase text-slate-400">{label}</p><p className="font-black text-slate-700">{value}</p></div>; }
