"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft,ArrowRight,BookOpen,Flame,Medal,Sparkles,Trophy,Zap } from "lucide-react";
import { getMyLearnerProfile,getMyProfileActivity,checkLearningLevelUp,type LearnerProfile,type ProfileActivity } from "@/lib/learner-profile";

export default function LearnerProfilePage(){
 const [p,setP]=useState<LearnerProfile|null>(null),[activity,setActivity]=useState<ProfileActivity[]>([]),[celebration,setCelebration]=useState<{level:number;title:string;icon:string}|null>(null),[error,setError]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){try{const [profile,items,ups]=await Promise.all([getMyLearnerProfile(),getMyProfileActivity(8),checkLearningLevelUp()]);setP(profile);setActivity(items);if(ups[0]?.newly_earned)setCelebration({level:ups[0].newly_reached_level,title:ups[0].title,icon:ups[0].icon});}catch(e){setError(e instanceof Error?e.message:"Profile could not be loaded.");}}
 if(error)return <main className="min-h-screen bg-slate-50 p-8 flex items-center justify-center"><div className="rounded-3xl bg-white p-8 text-center shadow-xl"><p className="font-black text-red-600">{error}</p><Link href="/dashboard" className="mt-4 inline-flex items-center gap-2 font-black text-violet-600">Dashboard <ArrowRight size={16}/></Link></div></main>;
 return <main className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-amber-50"><header className="sticky top-0 z-20 border-b border-white/70 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><Link href="/dashboard" className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-black text-slate-600 hover:bg-violet-50"><ArrowLeft size={17}/> Dashboard</Link><div className="flex items-center gap-2 font-black text-[#071b3a]"><Sparkles size={19} className="text-violet-600"/> Learner Profile</div><Link href="/progress/rewards" className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-black text-white">Rewards</Link></div></header>
 <div className="mx-auto max-w-6xl px-5 py-8 lg:px-8">
  <section className="relative overflow-hidden rounded-[2.4rem] bg-gradient-to-br from-[#071b3a] via-indigo-800 to-violet-700 p-7 text-white shadow-2xl sm:p-10"><div className="absolute -right-20 -top-24 h-80 w-80 rounded-full bg-white/10 blur-3xl"/><div className="relative flex flex-col gap-6 sm:flex-row sm:items-center"><div className="flex h-24 w-24 shrink-0 items-center justify-center overflow-hidden rounded-[2rem] bg-white/15 text-5xl ring-4 ring-white/10">{p?.avatar_url?<img src={p.avatar_url} alt="" className="h-full w-full object-cover"/>:(p?.avatar_emoji||p?.level_icon||"🌱")}</div><div className="min-w-0"><div className="text-xs font-black uppercase tracking-[.18em] text-indigo-200">Level {p?.current_level??1} · {p?.level_title??"Beginner"}</div><h1 className="mt-1 truncate text-3xl font-black sm:text-5xl">{p?.display_name||p?.full_name||"Learner"}</h1><p className="mt-2 text-sm font-semibold text-indigo-100">{p?.grade?`Grade ${p.grade}`:"Keep learning, one step at a time."}{p?.school_name?` · ${p.school_name}`:""}</p></div></div>
   <div className="mt-8"><div className="flex items-center justify-between text-sm font-black"><span>{p?.lifetime_xp??0} XP</span><span>{p?.next_level?`${p.xp_needed} XP to Level ${p.next_level}`:"Maximum level reached"}</span></div><div className="mt-2 h-4 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-white transition-all" style={{width:`${p?.level_progress_percent??0}%`}}/></div></div>
  </section>
  {celebration&&<section className="mt-6 rounded-3xl border border-amber-200 bg-amber-50 p-5 shadow-sm"><div className="flex items-center gap-4"><div className="text-4xl">{celebration.icon}</div><div><p className="font-black text-amber-950">Level up! 🎉</p><p className="text-sm font-semibold text-amber-800">You reached Level {celebration.level} — {celebration.title}.</p></div></div></section>}
  <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Streak",p?.current_streak??0,"🔥"],["Best streak",p?.best_streak??0,"🏅"],["Achievements",p?.achievement_count??0,"🏆"],["Mastered topics",`${p?.mastered_topics??0}/${p?.total_topics??0}`,"🧠"]].map(([label,value,icon])=><article key={String(label)} className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm"><div className="text-2xl">{icon}</div><p className="mt-3 text-2xl font-black text-[#071b3a]">{value}</p><p className="text-sm font-bold text-slate-500">{label}</p></article>)}</section>
  <section className="mt-6 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><article className="rounded-[1.8rem] border border-slate-100 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Zap className="text-violet-600" size={20}/><h2 className="text-xl font-black text-[#071b3a]">Learning snapshot</h2></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-violet-50 p-4"><p className="text-2xl font-black text-violet-700">{p?.recent_questions??0}</p><p className="text-xs font-bold text-slate-500">Questions · 7 days</p></div><div className="rounded-2xl bg-emerald-50 p-4"><p className="text-2xl font-black text-emerald-700">{p?.recent_accuracy??0}%</p><p className="text-xs font-bold text-slate-500">Recent accuracy</p></div><div className="rounded-2xl bg-amber-50 p-4"><p className="text-2xl font-black text-amber-700">{p?.missions_completed??0}</p><p className="text-xs font-bold text-slate-500">Missions completed</p></div><div className="rounded-2xl bg-cyan-50 p-4"><p className="text-2xl font-black text-cyan-700">{p?.best_combo??0}</p><p className="text-xs font-bold text-slate-500">Best combo</p></div></div><div className="mt-5 flex flex-wrap gap-3"><Link href="/progress/path" className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-black text-white">Learning Path</Link><Link href="/progress/achievements" className="rounded-xl bg-amber-100 px-4 py-2 text-sm font-black text-amber-800">Achievements</Link><Link href="/progress/levels" className="rounded-xl bg-indigo-100 px-4 py-2 text-sm font-black text-indigo-800">Levels</Link></div></article>
   <article className="rounded-[1.8rem] border border-slate-100 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><BookOpen className="text-indigo-600" size={20}/><h2 className="text-xl font-black text-[#071b3a]">Recent activity</h2></div><div className="mt-4 divide-y divide-slate-100">{activity.map((a,i)=><div key={`${a.created_at}-${i}`} className="py-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black text-slate-800">{a.reason}</p><p className="text-xs font-semibold text-slate-400">{a.source} · {new Date(a.created_at).toLocaleDateString()}</p></div>{a.xp>0&&<span className="text-xs font-black text-violet-600">+{a.xp} XP</span>}</div></div>)}{!activity.length&&<p className="py-8 text-center text-sm font-semibold text-slate-400">Your learning activity will appear here.</p>}</div></article></section>
 </div></main>;
}
