"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {Home,Gamepad2,Trophy,Gift,BarChart3,GraduationCap,Camera,Pencil,UserRound,Settings,ShieldCheck,Star,Flame,Medal,ArrowRight,LogOut,CheckCircle2} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import NotificationBell from "@/components/learner-notification-bell";

type Profile={full_name:string|null;avatar_url:string|null;avatar_emoji:string|null;grade:string|null;xp:number|null;current_streak:number|null;best_streak:number|null};
type Badge={id:string;title:string;image:string};
const badgeList:Badge[]=[
{id:"first-lesson",title:"First Lesson",image:"badge-math-explorer.webp"},
{id:"xp-100",title:"100 XP",image:"badge-practice-pro.webp"},
{id:"streak-3",title:"3-Day Streak",image:"badge-streak-star.webp"},
{id:"topic-complete",title:"Topic Complete",image:"badge-top-performer.webp"},
{id:"lessons-10",title:"10 Lessons",image:"badge-learner.webp"}
];
const avatars=[{id:"boy",image:"avatar-boy.webp",emoji:"👦"},{id:"girl",image:"avatar-girl.webp",emoji:"👧"},{id:"cap",image:"avatar-cap.webp",emoji:"🧢"},{id:"hijab",image:"avatar-hijab.webp",emoji:"👩"}];
export default function ProfilePage(){
 const[profile,setProfile]=useState<Profile|null>(null);
 const[earned,setEarned]=useState<string[]>([]);
 const[coins,setCoins]=useState<number|null>(null);
 const[joined,setJoined]=useState("");
 const[tab,setTab]=useState<"profile"|"achievements"|"settings"|"parent">("profile");
 const[editing,setEditing]=useState(false);
 const[name,setName]=useState("");
 const[bio,setBio]=useState("");
 const[saving,setSaving]=useState(false);
 const[uploading,setUploading]=useState(false);
 const[error,setError]=useState("");
 const[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;(async()=>{
  const db=createClient();if(!db){setError("Account is not configured.");setLoading(false);return;}
  const{data:{user}}=await db.auth.getUser();if(!user){window.location.href="/login";return;}
  const[{data:p,error:pe},{data:b},{data:wallet}]=await Promise.all([
   db.from("profiles").select("full_name,avatar_url,avatar_emoji,grade,xp,current_streak,best_streak").eq("id",user.id).maybeSingle(),
   db.from("student_achievements").select("achievement_key").eq("user_id",user.id).eq("completed",true),
   db.rpc("get_mind_spark_status")
  ]);
  if(!active)return;
  if(pe){setError(pe.message);setLoading(false);return;}
  const person=(p??{full_name:user.user_metadata?.full_name??"Student",avatar_url:null,avatar_emoji:"👦",grade:null,xp:0,current_streak:0,best_streak:0}) as Profile;
  setProfile(person);setName(person.full_name??"");setEarned((b??[]).map(x=>x.achievement_key));
  const w=wallet as Record<string,unknown>|null;
  const balance=w?.balance??w?.sparks??w?.mind_sparks;
  if(typeof balance==="number")setCoins(balance);
  if(user.created_at)setJoined(new Date(user.created_at).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"}));
  setLoading(false);
 })();return()=>{active=false};},[]);
 async function saveName(){const db=createClient();if(!db||!name.trim())return;setSaving(true);const{data:{user}}=await db.auth.getUser();if(!user){setSaving(false);return;}const{error:e}=await db.from("profiles").update({full_name:name.trim()}).eq("id",user.id);if(e)setError(e.message);else{setProfile(p=>p?{...p,full_name:name.trim()}:p);setEditing(false);}setSaving(false);}
 async function selectAvatar(emoji:string){const db=createClient();if(!db)return;setSaving(true);const{data:{user}}=await db.auth.getUser();if(!user){setSaving(false);return;}const{error:e}=await db.from("profiles").update({avatar_emoji:emoji,avatar_url:null}).eq("id",user.id);if(e)setError(e.message);else setProfile(p=>p?{...p,avatar_emoji:emoji,avatar_url:null}:p);setSaving(false);}
 async function uploadPhoto(file:File){if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>2*1024*1024){setError("Choose a JPG, PNG or WebP photo under 2 MB.");return;}const db=createClient();if(!db)return;setUploading(true);const{data:{user}}=await db.auth.getUser();if(!user){setUploading(false);return;}const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";const key=user.id+"/profile-"+Date.now()+"."+ext;const{error:e}=await db.storage.from("avatars").upload(key,file,{contentType:file.type});if(e){setError(e.message);setUploading(false);return;}const{data}=db.storage.from("avatars").getPublicUrl(key);const{error:saveError}=await db.from("profiles").update({avatar_url:data.publicUrl}).eq("id",user.id);if(saveError){setError(saveError.message);await db.storage.from("avatars").remove([key]);}else setProfile(p=>p?{...p,avatar_url:data.publicUrl}:p);setUploading(false);}
 async function signOut(){const db=createClient();if(db)await db.auth.signOut();window.location.href="/login";}
 const grade=profile?.grade?.match(/[1-7]/)?.[0];const first=profile?.full_name?.trim().split(/\s+/)[0]||"Learner";
 const displayAvatar=profile?.avatar_url;
 if(loading)return <main className="grid min-h-screen place-items-center bg-[#eff8ff] font-bold text-[#103d76]">Loading your profile…</main>;
 return <main className="min-h-screen bg-[#f0f8ff] text-[#123467]">
 <header className="sticky top-0 z-40 hidden h-[76px] bg-[#073b73] text-white shadow-sm lg:block lg:h-[90px]"><div className="mx-auto flex h-full max-w-[1680px] items-center justify-between px-4 sm:px-6 lg:px-12"><Link href="/dashboard" className="flex shrink-0 items-center rounded-2xl bg-white px-3 py-1.5 shadow-md"><img src="/fahi-hisaabu-logo-optimized.webp" alt="Fahi Hisaabu" className="h-[44px] max-w-[200px] object-contain lg:h-[57px] lg:max-w-[220px]"/></Link><nav className="hidden items-center gap-8 lg:flex">{([{href:"/dashboard",label:"Home",Icon:Home},{href:"/brain-games",label:"Games",Icon:Gamepad2},{href:"/leaderboard",label:"Leaderboard",Icon:Trophy},{href:"/rewards",label:"Rewards",Icon:Gift},{href:"/progress",label:"Progress",Icon:BarChart3},{href:"/profile",label:"Profile",Icon:GraduationCap}]).map(({href,label,Icon})=><Link key={href} href={href} className={`relative flex items-center gap-3 px-4 py-7 text-lg ${href==="/profile"?"font-black":"font-bold"}`}><Icon size={25}/>{label}{href==="/profile"&&<span className="absolute bottom-0 left-4 right-4 h-1 rounded-full bg-yellow-400"/>}</Link>)}</nav><NotificationBell/></div></header>
 <div className="mx-auto max-w-[1500px] px-4 pb-12 sm:px-7">
 <section className="mt-3 h-[140px] overflow-hidden rounded-[22px] bg-[#d9f5ff] sm:h-[190px] lg:h-[230px]"><img src="/profile-assets/profile-hero.webp" alt="My Profile — This is me! Keep learning, keep growing!" className="h-full w-full object-fill" onError={e=>{e.currentTarget.style.display="none";}}/></section>
 {error&&<div role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}<button className="ml-3 underline" onClick={()=>setError("")}>Dismiss</button></div>}
 <section className="mt-4 grid gap-5 rounded-[22px] border border-[#dceaf8] bg-white p-5 shadow-sm lg:grid-cols-[minmax(0,1.1fr)_minmax(0,1.8fr)] lg:items-center">
 <div className="flex items-center gap-4"><div className="relative h-28 w-28 shrink-0 overflow-hidden rounded-full bg-[#ffe5a0] sm:h-36 sm:w-36">{displayAvatar?<img src={displayAvatar} alt="Profile photo" className="h-full w-full object-cover"/>:avatars.find(a=>a.emoji===profile?.avatar_emoji)?<img src={`/profile-assets/${avatars.find(a=>a.emoji===profile?.avatar_emoji)?.image}`} alt="Selected avatar" className="h-full w-full object-cover"/>:<span className="grid h-full place-items-center text-6xl">{profile?.avatar_emoji||"👦"}</span>}<label className="absolute bottom-0 right-0 grid h-9 w-9 cursor-pointer place-items-center rounded-full bg-[#086ee3] text-white" title="Upload profile photo"><Camera size={20}/><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadPhoto(file);e.target.value="";}}/></label></div><div className="min-w-0"><div className="flex items-center gap-2"><h1 className="truncate text-3xl font-black sm:text-4xl">{first}</h1><button aria-label="Edit name" onClick={()=>setEditing(true)} className="rounded-xl bg-[#eaf5ff] p-2 text-[#096de1]"><Pencil size={20}/></button></div><span className="mt-3 inline-flex rounded-xl bg-[#e6f2ff] px-4 py-2 font-bold">{grade?`🏅 Grade ${grade}`:"Grade not set"}</span><p className="mt-3 text-sm font-medium">Keep learning, keep growing! ⭐</p></div></div>
 <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{([{icon:<Star size={37} fill="#ffc83d" color="#ef9e00"/>,label:"XP Points",value:(profile?.xp??0).toLocaleString(),bg:"bg-[#fff8e5]"},{icon:<span className="text-4xl">✨</span>,label:"Mind Sparks",value:coins===null?"—":coins.toLocaleString(),bg:"bg-[#ffebf0]"},{icon:<Flame size={40} fill="#ffb82e" color="#f34c19"/>,label:"Day Streak",value:String(profile?.current_streak??0),bg:"bg-[#e1f4ff]"},{icon:<Medal size={40} color="#7e42d9"/>,label:"Badges",value:String(earned.length),bg:"bg-[#eee9ff]"}]).map(x=><div key={x.label} className={`flex flex-col items-center rounded-2xl ${x.bg} px-2 py-4 text-center`}>{x.icon}<strong className="mt-2 text-3xl font-black">{x.value}</strong><span className="text-sm font-medium">{x.label}</span></div>)}</div>
 </section>
 <nav aria-label="Profile sections" className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-4">{([{id:"profile",label:"My Profile",Icon:UserRound},{id:"achievements",label:"Achievements",Icon:Trophy},{id:"settings",label:"Settings",Icon:Settings},{id:"parent",label:"Parent Access",Icon:ShieldCheck}] as const).map(x=><button key={x.id} onClick={()=>setTab(x.id)} className={`flex items-center justify-center gap-3 rounded-2xl border px-3 py-4 text-base font-bold shadow-sm ${tab===x.id?"border-[#0d56a9] bg-[#12549d] text-white":"border-[#deebf8] bg-white text-[#274e82]"}`}><x.Icon size={23}/>{x.label}</button>)}</nav>
 {tab==="profile"&&<div className="mt-4 grid gap-4 lg:grid-cols-3">
 <section className="rounded-[22px] border border-[#dceaf8] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Personal Information</h2><button aria-label="Edit name" onClick={()=>setEditing(true)} className="rounded-xl bg-[#eaf5ff] p-2 text-[#096de1]"><Pencil size={19}/></button></div><div className="mt-4 space-y-3">{([{label:"Name",value:profile?.full_name||"Student"},{label:"Grade",value:grade?`Grade ${grade}`:"Not set"},{label:"Joined",value:joined||"—"},{label:"About Me",value:bio||"I love learning maths! ⭐"}]).map(x=><div key={x.label} className="grid grid-cols-[90px_1fr] gap-2 rounded-xl bg-[#f0f7ff] p-3 text-sm"><span className="font-semibold text-[#526f92]">{x.label}</span><strong className="min-w-0 break-words">{x.value}</strong></div>)}</div></section>
 <section className="rounded-[22px] border border-[#dceaf8] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-black">🏆 My Achievements</h2><button onClick={()=>setTab("achievements")} className="text-sm font-bold text-[#0a71db]">View All →</button></div><div className="mt-5 grid grid-cols-3 gap-3">{badgeList.map(x=><div key={x.id} className={`text-center ${earned.includes(x.id)?"":"opacity-40"}`}><img src={`/profile-assets/${x.image}`} alt="" className="mx-auto h-16 w-16 object-contain"/><p className="mt-2 text-xs font-bold">{x.title}</p><p className="text-[10px]">{earned.includes(x.id)?"Earned":"Locked"}</p></div>)}</div></section>
 <section className="rounded-[22px] border border-[#dceaf8] bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Avatar & Appearance</h2><div className="mt-5 grid grid-cols-4 gap-2">{avatars.map(a=><button key={a.id} disabled={saving||uploading} onClick={()=>void selectAvatar(a.emoji)} className={`overflow-hidden rounded-xl border-2 ${!displayAvatar&&profile?.avatar_emoji===a.emoji?"border-[#086fe3]":"border-transparent"}`}><img src={`/profile-assets/${a.image}`} alt={a.id+" avatar"} className="aspect-square w-full object-cover"/></button>)}</div><label className="mt-5 flex cursor-pointer flex-col items-center rounded-xl bg-[#e9f5ff] p-4 text-sm font-bold text-[#096bd5]"><span><Camera className="mr-2 inline" size={19}/>{uploading?"Uploading…":"Upload Photo"}</span><small className="mt-1 font-normal">JPG, PNG or WebP · Max 2 MB</small><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadPhoto(file);e.target.value="";}}/></label></section>
 </div>}
 {tab==="achievements"&&<section className="mt-4 rounded-[22px] bg-white p-6"><h2 className="text-2xl font-black">My Achievements</h2><p className="mt-1 text-sm text-[#6480a2]">Your earned badges and the next milestones to unlock.</p><div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{badgeList.map(x=><div key={x.id} className={`rounded-2xl bg-[#f0f7ff] p-4 text-center ${earned.includes(x.id)?"":"opacity-50"}`}><img src={`/profile-assets/${x.image}`} alt="" className="mx-auto h-20 w-20 object-contain"/><p className="mt-2 font-bold">{x.title}</p><p className="text-sm">{earned.includes(x.id)?"✓ Earned":"Locked"}</p></div>)}</div><Link href="/rewards" className="mt-5 inline-flex items-center gap-2 font-bold text-[#086bd4]">Visit Rewards <ArrowRight size={16}/></Link></section>}
 {tab==="settings"&&<section className="mt-4 rounded-[22px] bg-white p-6"><h2 className="text-2xl font-black">Settings</h2><button onClick={()=>setEditing(true)} className="mt-5 flex items-center gap-3 rounded-xl bg-[#eaf4ff] px-5 py-3 font-bold"><Pencil size={18}/> Edit your name</button><div className="mt-5 flex flex-wrap gap-3"><Link href="/privacy" className="rounded-xl bg-[#eaf4ff] px-5 py-3 font-bold">Privacy Policy</Link><Link href="/about" className="rounded-xl bg-[#eaf4ff] px-5 py-3 font-bold">About Fahi Hisaabu</Link><button onClick={()=>void signOut()} className="flex items-center gap-2 rounded-xl bg-red-50 px-5 py-3 font-bold text-red-700"><LogOut size={18}/> Sign Out</button></div></section>}
 {tab==="parent"&&<section className="mt-4 rounded-[22px] bg-white p-6"><h2 className="text-2xl font-black">Parent Access</h2><p className="mt-2 text-sm text-[#597a9d]">Parents can view learner activity and manage subscriptions from their own account.</p><Link href="/parent" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#0c71df] px-5 py-3 font-bold text-white">Parent Dashboard <ArrowRight size={18}/></Link></section>}
 {editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={e=>{e.preventDefault();void saveName();}} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-black">Edit your name</h2><label className="mt-4 block text-sm font-bold">Full name<input value={name} onChange={e=>setName(e.target.value)} maxLength={80} required className="mt-2 w-full rounded-xl border border-[#cbdff5] p-3"/></label><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={()=>setEditing(false)} className="rounded-xl bg-[#edf5ff] px-4 py-2 font-bold">Cancel</button><button disabled={saving||!name.trim()} className="rounded-xl bg-[#086fe2] px-4 py-2 font-bold text-white">{saving?"Saving…":"Save"}</button></div></form></div>}
 </div></main>;
}
