"use client";

import Link from "next/link";
import { ArrowLeft, Brain, Gamepad2, Lock, Play, Sparkles, Trophy, Zap } from "lucide-react";

const games = [
  { title: "Memory Tiles", category: "Memory", emoji: "🧠", href: "/brain-games/memory-tiles", active: true, description: "Remember the tiles and match each math equation with its answer.", gradient: "from-cyan-400 via-sky-500 to-blue-600", tag: "NEW" },
  { title: "Number Rush", category: "Speed", emoji: "⚡", href: "/brain-games/number-rush", active: true, description: "Race the clock, solve quick math challenges and build powerful combos.", gradient: "from-yellow-300 via-orange-400 to-pink-500", tag: "SPEED" },
  { title: "Even or Odd", category: "Attention", emoji: "🔢", href: "/brain-games/even-odd", active: true, description: "Quickly identify whether numbers are even or odd before they disappear.", gradient: "from-violet-400 via-purple-500 to-fuchsia-500", tag: "NEW" },
  { title: "Flash Memory", category: "Memory", emoji: "✨", href: "/brain-games/flash-memory", active: true, description: "Watch a sequence of numbers and recreate it from memory.", gradient: "from-blue-400 via-cyan-500 to-teal-500", tag: "NEW" },
  { title: "Hidden Numbers", category: "Attention", emoji: "🔎", href: "#", active: false, description: "Find hidden numbers and mathematical patterns in a busy scene.", gradient: "from-emerald-400 via-teal-500 to-cyan-600", tag: "SOON" },
  { title: "Number Order", category: "Flexibility", emoji: "🔀", href: "/brain-games/number-order", active: true, description: "Remember the numbers, then rebuild the sequence from smallest to largest.", gradient: "from-amber-300 via-orange-400 to-rose-500", tag: "NEW" },
  { title: "Pattern Quest", category: "Problem Solving", emoji: "🧩", href: "/brain-games/pattern-quest", active: true, description: "Discover the rule behind a pattern and choose what comes next.", gradient: "from-pink-400 via-rose-500 to-red-600", tag: "NEW" },
  { title: "What's Missing?", category: "Attention", emoji: "👀", href: "#", active: false, description: "Study a group of numbers, then spot the one that has vanished.", gradient: "from-indigo-400 via-blue-500 to-violet-600", tag: "SOON" },
];

const categories = ["All", "Memory", "Speed", "Attention", "Flexibility", "Problem Solving"];

export default function BrainGamesPage() {
  const ready = games.filter((g) => g.active).length;
  return (
    <main className="min-h-screen overflow-x-hidden bg-[radial-gradient(circle_at_10%_8%,#fff59a,transparent_20%),radial-gradient(circle_at_90%_15%,#b9f5ff,transparent_24%),linear-gradient(135deg,#effcff,#eef7ff_45%,#f9efff)] px-3 py-4 text-[#12375d] sm:px-6 sm:py-6">
      <div className="mx-auto max-w-7xl">
        <Link href="/games" className="inline-flex items-center gap-2 rounded-full border-2 border-white bg-white px-4 py-2 font-black shadow-sm transition hover:-translate-y-0.5"><ArrowLeft size={18}/> Game Zone</Link>
        <section className="relative mt-5 overflow-hidden rounded-[38px] border-4 border-white bg-gradient-to-br from-cyan-500 via-blue-600 to-indigo-700 p-6 text-white shadow-[0_25px_70px_rgba(14,116,200,.24)] sm:p-10">
          <div className="pointer-events-none absolute -right-20 -top-24 h-72 w-72 rounded-full bg-yellow-300/20"/><div className="pointer-events-none absolute -bottom-24 left-1/3 h-80 w-80 rounded-full bg-pink-300/15"/>
          <div className="relative flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/15 px-4 py-2 text-sm font-black"><Brain size={18}/> BRAIN GAMES</div><h1 className="mt-4 text-5xl font-black leading-none sm:text-7xl">Train Your Math Brain! 🧠</h1><p className="mt-4 max-w-2xl text-lg font-bold text-white/90 sm:text-xl">Play quick brain challenges for memory, speed, attention, flexibility and problem solving.</p></div><div className="grid grid-cols-3 gap-2 sm:min-w-[390px] sm:gap-3"><div className="rounded-3xl border border-white/15 bg-white/15 p-4 text-center"><Zap className="mx-auto"/><b className="mt-2 block text-2xl">5</b><span className="text-xs font-bold">SKILLS</span></div><div className="rounded-3xl border border-white/15 bg-white/15 p-4 text-center"><Gamepad2 className="mx-auto"/><b className="mt-2 block text-2xl">{ready}</b><span className="text-xs font-bold">READY</span></div><div className="rounded-3xl border border-white/15 bg-white/15 p-4 text-center"><Trophy className="mx-auto"/><b className="mt-2 block text-2xl">+XP</b><span className="text-xs font-bold">REWARDS</span></div></div></div>
        </section>
        <div className="mt-6 flex gap-2 overflow-x-auto pb-1">{categories.map((category, index) => <button key={category} className={`whitespace-nowrap rounded-full border-2 px-4 py-2.5 text-sm font-black shadow-sm ${index === 0 ? "border-blue-500 bg-blue-500 text-white" : "border-white bg-white text-slate-600 hover:bg-cyan-50"}`}>{category}</button>)}</div>
        <section className="mt-6 rounded-[30px] border-4 border-cyan-100 bg-white p-5 shadow-md sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-yellow-100 px-3 py-1 text-xs font-black text-amber-700">⭐ TODAY'S BRAIN CHALLENGE</div><h2 className="mt-2 text-2xl font-black">Memory Tiles</h2><p className="mt-1 font-semibold text-slate-500">60 seconds • Match 6 pairs • Earn XP, coins and stars</p></div><Link href="/brain-games/memory-tiles" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-cyan-500 to-blue-600 px-6 py-3.5 font-black text-white shadow-md transition hover:scale-105"><Play size={18} fill="currentColor"/> Play Challenge</Link></div></section>
        <div className="mt-8 flex items-end justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-purple-100 px-3 py-1 text-xs font-black text-purple-700"><Sparkles size={14}/> BRAIN ARENA</div><h2 className="mt-2 text-3xl font-black sm:text-4xl">Choose a Challenge</h2><p className="mt-1 font-semibold text-slate-500">Short games designed to make mathematical thinking fun.</p></div><span className="hidden rounded-full bg-white px-4 py-2 text-sm font-black shadow sm:block">{games.length} challenges</span></div>
        <div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{games.map((game) => <article key={game.title} className={`overflow-hidden rounded-[28px] border-4 bg-white shadow-[0_12px_30px_rgba(30,80,120,.12)] transition ${game.active ? "border-cyan-200 hover:-translate-y-2 hover:shadow-xl" : "border-white"}`}><div className={`relative h-40 bg-gradient-to-br ${game.gradient}`}><div className="absolute left-4 top-4 rounded-full bg-white/95 px-3 py-1 text-[10px] font-black text-slate-600 shadow">{game.tag}</div><div className="absolute inset-0 flex items-center justify-center text-[68px] drop-shadow-xl">{game.emoji}</div>{!game.active && <div className="absolute right-4 top-4 rounded-full bg-black/15 px-2 py-1 text-[10px] font-black text-white"><Lock size={11} className="mr-1 inline"/> SOON</div>}</div><div className="p-5"><div className="text-[10px] font-black uppercase tracking-widest text-purple-500">{game.category}</div><h3 className="mt-1 text-xl font-black">{game.title}</h3><p className="mt-2 min-h-[60px] text-sm font-semibold leading-5 text-slate-500">{game.description}</p>{game.active ? <Link href={game.href} className="mt-4 flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-blue-500 to-purple-600 px-4 py-3 font-black text-white shadow hover:scale-[1.02]"><Play size={16} fill="currentColor"/> Play</Link> : <div className="mt-4 rounded-xl bg-slate-100 px-4 py-3 text-center text-sm font-black text-slate-500"><Lock size={15} className="mr-1 inline"/> Coming soon</div>}</div></article>)}</div>
        <section className="mt-8 rounded-[30px] border-4 border-dashed border-purple-200 bg-white/80 p-7 text-center shadow-sm"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-purple-100 text-purple-600"><Brain size={28}/></div><h2 className="mt-3 text-2xl font-black">Every game trains a different skill ✨</h2><p className="mx-auto mt-2 max-w-2xl font-semibold text-slate-500">Complete challenges to grow your Brain Power and earn rewards inside your Math World.</p></section>
      </div>
    </main>
  );
}
