"use client";

import Link from "next/link";
import { ArrowLeft, Brain, Gamepad2, Lock, Play, Sparkles, Trophy, Zap } from "lucide-react";
import { useMemo, useState } from "react";

const games = [
  { title: "Memory Tiles", category: "Memory", href: "/brain-games/memory-tiles", active: true, description: "Match equations with answers and train your memory.", gradient: "from-cyan-400 via-sky-500 to-blue-600", tag: "NEW", level: 1, reward: 20, art: "memory" },
  { title: "Number Rush", category: "Speed", href: "/brain-games/number-rush", active: true, description: "Race the clock and solve quick math challenges.", gradient: "from-yellow-300 via-orange-400 to-pink-500", tag: "SPEED", level: 1, reward: 20, art: "rush" },
  { title: "Even or Odd", category: "Attention", href: "/brain-games/even-odd", active: true, description: "Spot the correct number before it disappears.", gradient: "from-violet-400 via-purple-500 to-fuchsia-500", tag: "NEW", level: 1, reward: 20, art: "evenodd" },
  { title: "Flash Memory", category: "Memory", href: "/brain-games/flash-memory", active: true, description: "Watch a number sequence and rebuild it from memory.", gradient: "from-blue-400 via-cyan-500 to-teal-500", tag: "NEW", level: 2, reward: 25, art: "flash" },
  { title: "Hidden Numbers", category: "Attention", href: "#", active: false, description: "Find hidden numbers inside a busy mathematical scene.", gradient: "from-emerald-400 via-teal-500 to-cyan-600", tag: "SOON", level: 2, reward: 25, art: "hidden" },
  { title: "Number Order", category: "Flexibility", href: "/brain-games/number-order", active: true, description: "Remember the numbers, then rebuild the correct order.", gradient: "from-amber-300 via-orange-400 to-rose-500", tag: "NEW", level: 2, reward: 25, art: "order" },
  { title: "Pattern Quest", category: "Problem Solving", href: "/brain-games/pattern-quest", active: true, description: "Discover the rule behind a pattern and continue it.", gradient: "from-pink-400 via-rose-500 to-red-600", tag: "NEW", level: 3, reward: 30, art: "pattern" },
  { title: "What's Missing?", category: "Attention", href: "#", active: false, description: "Study a group of numbers and spot the missing one.", gradient: "from-indigo-400 via-blue-500 to-violet-600", tag: "SOON", level: 3, reward: 30, art: "missing" },
];

const categories = ["All", "Memory", "Speed", "Attention", "Flexibility", "Problem Solving"];
const skills = [["Memory",72,"🧠"],["Speed",58,"⚡"],["Attention",64,"👀"],["Flexibility",46,"🔄"],["Problem Solving",55,"🧩"]];

function GameArt({ type }: { type: string }) {
  const common = "absolute rounded-xl border-2 border-white/60 bg-white/85 shadow-[0_5px_0_rgba(0,0,0,.12)]";
  if (type === "memory") return <div className="relative h-full w-full"><div className={`${common} left-[17%] top-[28%] h-14 w-14 rotate-[-8deg]`}><span className="flex h-full items-center justify-center text-xl font-black text-cyan-600">2+3</span></div><div className={`${common} right-[18%] top-[24%] h-14 w-14 rotate-[7deg]`}><span className="flex h-full items-center justify-center text-2xl font-black text-blue-600">5</span></div><div className="absolute left-[34%] top-[12%] text-4xl">🧠</div><div className={`${common} left-[31%] bottom-[17%] h-14 w-14 rotate-[5deg]`}><span className="flex h-full items-center justify-center text-xl font-black text-cyan-600">4+4</span></div><div className={`${common} right-[29%] bottom-[14%] h-14 w-14 rotate-[-5deg]`}><span className="flex h-full items-center justify-center text-2xl font-black text-blue-600">8</span></div></div>;
  if (type === "rush") return <div className="relative h-full w-full"><div className="absolute bottom-7 left-[15%] h-3 w-[70%] rounded-full bg-white/60"/><div className="absolute bottom-10 left-[25%] text-6xl">🏃</div><div className="absolute left-[16%] top-[20%] rounded-xl bg-white/90 px-4 py-2 text-2xl font-black text-orange-500">7+6</div><div className="absolute right-[14%] top-[35%] rounded-xl bg-white/90 px-4 py-2 text-2xl font-black text-pink-500">13</div><div className="absolute right-[25%] top-[12%] text-4xl">⚡</div></div>;
  if (type === "evenodd") return <div className="relative h-full w-full"><div className="absolute left-[14%] top-[18%] h-20 w-20 rounded-full bg-white/90 text-center text-4xl font-black leading-[5rem] text-purple-600">8</div><div className="absolute right-[15%] top-[18%] h-20 w-20 rounded-full bg-white/90 text-center text-4xl font-black leading-[5rem] text-fuchsia-600">7</div><div className="absolute left-[37%] bottom-[15%] rounded-2xl bg-white/90 px-5 py-3 text-xl font-black text-purple-700">EVEN ✓</div><div className="absolute right-[15%] bottom-[14%] text-4xl">👀</div></div>;
  if (type === "flash") return <div className="relative h-full w-full"><div className="absolute left-[31%] top-[16%] rounded-3xl bg-white/90 px-7 py-4 text-5xl font-black text-teal-600 shadow-xl">4 8 2</div><div className="absolute left-[24%] bottom-[18%] text-4xl">✨</div><div className="absolute right-[23%] bottom-[15%] rounded-xl bg-white/90 px-4 py-2 text-xl font-black text-cyan-600">?</div></div>;
  if (type === "order") return <div className="relative h-full w-full"><div className="absolute left-[15%] top-[24%] rotate-[-7deg] rounded-xl bg-white/90 px-4 py-3 text-2xl font-black text-orange-500">42</div><div className="absolute left-[38%] top-[16%] rotate-[4deg] rounded-xl bg-white/90 px-4 py-3 text-2xl font-black text-rose-500">17</div><div className="absolute right-[15%] top-[28%] rotate-[7deg] rounded-xl bg-white/90 px-4 py-3 text-2xl font-black text-pink-600">31</div><div className="absolute left-[30%] bottom-[13%] text-4xl">🔀</div></div>;
  if (type === "pattern") return <div className="relative h-full w-full"><div className="absolute left-[13%] top-[25%] rounded-xl bg-white/90 px-3 py-2 text-2xl font-black text-rose-500">2</div><div className="absolute left-[32%] top-[16%] rounded-xl bg-white/90 px-3 py-2 text-2xl font-black text-pink-600">4</div><div className="absolute left-[51%] top-[27%] rounded-xl bg-white/90 px-3 py-2 text-2xl font-black text-orange-500">6</div><div className="absolute right-[13%] top-[16%] rounded-xl bg-white/90 px-3 py-2 text-2xl font-black text-rose-500">?</div><div className="absolute left-[38%] bottom-[13%] text-4xl">🧩</div></div>;
  return <div className="relative h-full w-full"><div className="absolute inset-x-[17%] top-[20%] grid grid-cols-4 gap-2">{[1,2,3,4,5,6,7,8].map(n=><span key={n} className="flex h-10 items-center justify-center rounded-lg bg-white/75 text-lg font-black text-indigo-600">{n}</span>)}</div><div className="absolute right-[18%] bottom-[12%] text-4xl">🔎</div></div>;
}

export default function BrainGamesPage() {
  const [category,setCategory]=useState("All");
  const [dailySeconds]=useState(25*60);
  const filtered=useMemo(()=>category==="All"?games:games.filter(g=>g.category===category),[category]);
  const mins=Math.floor(dailySeconds/60).toString().padStart(2,"0"); const secs=(dailySeconds%60).toString().padStart(2,"0");
  return <main className="min-h-screen overflow-x-hidden bg-[#18b9e7] px-3 py-4 text-[#12375d] sm:px-6 sm:py-6">
    <div className="mx-auto max-w-7xl">
      <Link href="/games" className="inline-flex items-center gap-2 rounded-full border-2 border-white bg-white px-4 py-2 font-black shadow-sm"><ArrowLeft size={18}/> Game Zone</Link>
      <section className="relative mt-4 overflow-hidden rounded-[34px] border-4 border-white bg-gradient-to-br from-[#09a9df] via-[#18c7ee] to-[#1684d7] p-5 text-white shadow-xl sm:p-8"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-white/10"/><div className="absolute -bottom-24 left-1/3 h-72 w-72 rounded-full bg-yellow-300/15"/><div className="relative grid gap-6 lg:grid-cols-[1fr_360px] lg:items-center"><div><div className="inline-flex rounded-full bg-white/15 px-4 py-2 text-sm font-black"><Brain size={18} className="mr-2"/> BRAIN GAMES</div><h1 className="mt-3 text-4xl font-black sm:text-6xl">Train Your Brain! 🧠</h1><p className="mt-3 max-w-xl text-lg font-bold text-white/90">Play, think, remember and beat your best score.</p></div><div className="rounded-[26px] border border-white/25 bg-white/15 p-4 backdrop-blur"><div className="flex items-center justify-between"><div><div className="text-xs font-black uppercase tracking-widest text-white/75">Remaining Time</div><div className="mt-1 text-4xl font-black">{mins}:{secs}</div></div><div className="rounded-2xl bg-yellow-300 px-4 py-3 text-center text-slate-900"><div className="text-2xl font-black">5</div><div className="text-[9px] font-black">TOKENS</div></div></div><div className="mt-4 h-3 rounded-full bg-white/20"><div className="h-full w-[100%] rounded-full bg-yellow-300"/></div></div></div></section>
      <section className="mt-5 rounded-[28px] border-4 border-white bg-white/95 p-4 shadow-lg sm:p-5"><div className="flex flex-wrap gap-2">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`rounded-full px-5 py-2.5 text-sm font-black transition ${category===c?"bg-[#079ddd] text-white shadow":"bg-[#e8f8ff] text-[#17628a] hover:bg-[#d5f3ff]"}`}>{c}</button>)}</div></section>
      <section className="mt-5 rounded-[30px] border-4 border-white bg-[#f8fdff] p-4 shadow-xl sm:p-6"><div className="flex items-center justify-between gap-3"><div><div className="inline-flex rounded-full bg-yellow-100 px-3 py-1 text-xs font-black text-amber-700">⭐ DAILY CHALLENGE</div><h2 className="mt-2 text-2xl font-black">Memory Tiles</h2><p className="font-semibold text-slate-500">Complete today's challenge and earn bonus rewards.</p></div><Link href="/brain-games/memory-tiles" className="rounded-2xl bg-[#08a6df] px-5 py-3 font-black text-white shadow">Play Now <Play size={16} className="ml-1 inline" fill="currentColor"/></Link></div></section>
      <section className="mt-6 rounded-[30px] border-4 border-white bg-white/95 p-5 shadow-lg"><div className="flex items-center gap-2"><Sparkles size={18} className="text-purple-500"/><h2 className="text-2xl font-black">Brain Skills</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{skills.map(([name,value,icon])=><div key={name} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between font-black"><span>{icon} {name}</span><span>{value}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-200"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-purple-500" style={{width:`${value}%`}}/></div></div>)}</div></section>
      <div className="mt-7 flex items-end justify-between"><div><div className="inline-flex rounded-full bg-white px-3 py-1 text-xs font-black text-purple-700"><Gamepad2 size={14} className="mr-1"/> GAME ARENA</div><h2 className="mt-2 text-3xl font-black text-white sm:text-4xl">Choose a Brain Game</h2></div><span className="hidden rounded-full bg-white px-4 py-2 text-sm font-black shadow sm:block">{filtered.length} games</span></div>
      <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.map(game=><article key={game.title} className="overflow-hidden rounded-[24px] border-4 border-white bg-white shadow-[0_10px_0_rgba(0,70,100,.12)] transition hover:-translate-y-1.5 hover:shadow-xl"><div className={`relative h-44 overflow-hidden bg-gradient-to-br ${game.gradient}`}><div className="absolute inset-x-0 top-0 h-9 bg-white/10"/><div className="absolute left-3 top-3 rounded-xl bg-[#078fd2] px-3 py-1 text-xs font-black text-white shadow">{game.title}</div><div className="absolute right-3 top-3 rounded-full bg-white/90 px-2 py-1 text-[9px] font-black text-slate-600">{game.category}</div><GameArt type={game.art}/>{!game.active&&<div className="absolute inset-0 flex items-center justify-center bg-slate-900/15"><span className="rounded-full bg-white px-4 py-2 text-xs font-black text-slate-600 shadow"><Lock size={14} className="mr-1 inline"/> Unlock</span></div>}</div><div className="p-4"><div className="flex items-center justify-between"><span className="text-xs font-black uppercase tracking-wider text-[#0a9bd5]">Level {game.level}</span><span className="rounded-full bg-yellow-50 px-2.5 py-1 text-xs font-black text-amber-700">🪙 +{game.reward}</span></div><p className="mt-2 min-h-[42px] text-sm font-semibold leading-5 text-slate-500">{game.description}</p>{game.active?<Link href={game.href} className="mt-3 flex items-center justify-center gap-2 rounded-xl bg-[#08a6df] px-4 py-3 font-black text-white shadow">Play <Play size={15} fill="currentColor"/></Link>:<div className="mt-3 rounded-xl bg-slate-100 px-4 py-3 text-center text-sm font-black text-slate-500">Unlock at Level {game.level}</div>}</div></article>)}</div>
      <section className="mt-7 rounded-[28px] border-4 border-white bg-white/95 p-6 text-center shadow-lg"><Trophy className="mx-auto text-amber-500" size={30}/><h2 className="mt-2 text-2xl font-black">Keep Playing, Keep Growing! 🌈</h2><p className="mt-1 font-semibold text-slate-500">Every challenge helps you build your math brain.</p></section>
    </div>
  </main>;
}
