"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, BarChart3, BookOpen, CheckCircle2, Flame, LogOut, Map, Sparkles, Star, Target, Trophy, Zap } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Profile={full_name:string|null;grade:string|null;learning_level:string|null;xp:number;current_streak:number;best_streak:number};
type Topic={id:string;title:string;description:string;level:string;lessons:number;sort_order:number};
type TopicProgress={topic_id:string;questions_answered:number;correct_answers:number;completed_at:string|null};
type Lesson={id:string;topic_id:string;title:string;lesson_number:number;sort_order:number};
type LessonProgress={lesson_id:string;completed_at:string|null};
type Achievement={id:string;title:string;description:string;icon:string};

const topicIds=["place-value","addition-subtraction","multiplication","fractions"];
const topicStyles=[
 {bg:"from-violet-500 to-indigo-500",soft:"bg-violet-50",icon:"text-violet-600"},
 {bg:"from-cyan-400 to-blue-500",soft:"bg-cyan-50",icon:"text-cyan-600"},
 {bg:"from-amber-400 to-orange-500",soft:"bg-amber-50",icon:"text-orange-600"},
 {bg:"from-pink-400 to-rose-500",soft:"bg-pink-50",icon:"text-pink-600"},
];

export default function DashboardPage(){
 const[profile,setProfile]=useState<Profile|null>(null),[status,setStatus]=useState("Loading your learning space…"),[topics,setTopics]=useState<Topic[]>([]),[topicProgress,setTopicProgress]=useState<TopicProgress[]>([]),[lessons,setLessons]=useState<Lesson[]>([]),[lessonProgress,setLessonProgress]=useState<LessonProgress[]>([]),[achievements,setAchievements]=useState<Achievement[]>([]);
 useEffect(()=>{const supabase=createClient();if(!supabase){setStatus("Supabase is not configured yet.");return;}supabase.auth.getUser().then(async({data,error})=>{if(error||!data.user){window.location.href="/login";return;}const[{data:row},{data:ts},{data:tp},{data:ls},{data:lp},{data:sa}]=await Promise.all([
  supabase.from("profiles").select("full_name,grade,learning_level,xp,current_streak,best_streak").eq("id",data.user.id).maybeSingle(),
  supabase.from("learning_topics").select("id,title,description,level,lessons,sort_order").order("sort_order"),
  supabase.from("topic_progress").select("topic_id,questions_answered,correct_answers,completed_at").eq("user_id",data.user.id),
  supabase.from("learning_lessons").select("id,topic_id,title,lesson_number,sort_order").order("sort_order"),
  supabase.from("lesson_progress").select("lesson_id,completed_at").eq("user_id",data.user.id),
  supabase.from("student_achievements").select("achievement_id,earned_at").eq("user_id",data.user.id)
 ]);setProfile(row??{full_name:data.user.user_metadata?.full_name??"Student",grade:null,learning_level:null,xp:0,current_streak:0,best_streak:0});setTopics((ts??[]) as Topic[]);setTopicProgress((tp??[]) as TopicProgress[]);setLessons((ls??[]) as Lesson[]);setLessonProgress((lp??[]) as LessonProgress[]);const ids=(sa??[]).map((a:{achievement_id:string})=>a.achievement_id);if(ids.length){const{data:ad}=await supabase.from("learning_achievements").select("id,title,description,icon").in("id",ids).order("sort_order");setAchievements((ad??[]) as Achievement[]);}setStatus("")})},[]);
 async function signOut(){const supabase=createClient();if(supabase)await supabase.auth.signOut();window.location.href="/"}
 const completedLessonIds=useMemo(()=>new Set(lessonProgress.filter(p=>p.completed_at).map(p=>p.lesson_id)),[lessonProgress]);
 const completedLessons=completedLessonIds.size,totalLessons=lessons.length||21,overallProgress=Math.min(100,Math.round((completedLessons/totalLessons)*100));
 const answered=topicProgress.reduce((n,p)=>n+p.questions_answered,0),correct=topicProgress.reduce((n,p)=>n+p.correct_answers,0),completedTopics=topicProgress.filter(p=>p.completed_at).length,accuracy=answered?Math.round((correct/answered)*100):0;
 const nextLesson=lessons.filter(l=>!completedLessonIds.has(l.id)).sort((a,b)=>a.sort_order-b.sort_order)[0];
 const nextTopic=nextLesson?.topic_id||"place-value",nextTopicTitle=topics.find(t=>t.id===nextTopic)?.title||"Place Value",firstName=(profile?.full_name||"Student").split(" ")[0];
 const level=Math.floor((profile?.xp??0)/100)+1,levelProgress=(profile?.xp??0)%100;
 if(status)return <main className="flex min-h-screen items-center justify-center bg-gradient-to-br from-violet-50 via-white to-cyan-50 p-6"><div className="rounded-3xl border border-white bg-white p-8 text-center shadow-xl"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-400 text-white"><Sparkles/></div><p className="mt-4 font-semibold text-[#071b3a]">{status}</p><Link href="/login" className="mt-4 inline-block text-sm font-bold text-violet-600">Go to student login</Link></div></main>;
 return <main className="min-h-screen bg-gradient-to-br from-[#f7f7ff] via-white to-[#f0fbff]">
  <header className="sticky top-0 z-30 border-b border-white/70 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-600 to-indigo-500 text-xl font-black text-white shadow-lg shadow-violet-200">F</div><div><p className="text-sm font-black tracking-wide text-[#071b3a]">FAHI VISSNUN</p><p className="text-xs text-slate-500">Math Adventure</p></div></Link><div className="flex items-center gap-2"><Link href="/progress" className="hidden rounded-xl px-3 py-2 text-sm font-bold text-slate-600 hover:bg-violet-50 hover:text-violet-600 sm:inline-flex">Progress</Link><Link href="/rewards" className="hidden rounded-xl px-3 py-2 text-sm font-bold text-slate-600 hover:bg-yellow-50 hover:text-yellow-700 sm:inline-flex">Rewards</Link><button onClick={signOut} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-600 hover:border-violet-200 hover:text-violet-600"><LogOut size={16}/> Sign out</button></div></div></header>
  <div className="mx-auto max-w-7xl px-5 py-7 lg:px-8 lg:py-9">
   <section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-violet-600 via-indigo-600 to-blue-500 p-7 text-white shadow-2xl shadow-indigo-200 sm:p-9"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-fuchsia-400/25 blur-2xl"/><div className="absolute -bottom-24 left-1/3 h-64 w-64 rounded-full bg-cyan-300/20 blur-2xl"/><div className="relative grid gap-8 lg:grid-cols-[1.25fr_.75fr] lg:items-center"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1.5 text-xs font-black uppercase tracking-wider"><Sparkles size={14}/> Your learning adventure</div><h1 className="mt-4 text-3xl font-black sm:text-5xl">Hey {firstName}! <span className="text-yellow-300">Let’s level up.</span> 🚀</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-indigo-100 sm:text-base">Your dashboard is your learning hub. Practise a mission, complete today's challenge, check your progress and collect rewards.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/mission" className="inline-flex items-center gap-2 rounded-2xl bg-yellow-300 px-5 py-3.5 font-black text-[#24134f] shadow-lg hover:-translate-y-0.5 hover:bg-yellow-200">Continue Mission <ArrowRight size={18}/></Link><Link href="/challenge" className="inline-flex items-center gap-2 rounded-2xl bg-white/15 px-5 py-3.5 font-black text-white ring-1 ring-white/25 hover:bg-white/20">Daily Challenge <Target size={18}/></Link></div></div><div className="rounded-3xl bg-white/10 p-5 backdrop-blur"><div className="flex items-end justify-between"><div><p className="text-xs font-bold text-indigo-100">Level</p><p className="text-4xl font-black">{level}</p></div><div className="text-right"><p className="text-xs text-indigo-100">XP</p><p className="text-2xl font-black">{profile?.xp??0}</p></div></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-yellow-300 transition-all" style={{width:`${levelProgress}%`}}/></div><p className="mt-2 text-xs text-indigo-100">{100-levelProgress} XP to Level {level+1}</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-3"><Flame className="text-orange-300" size={20}/><p className="mt-1 text-xl font-black">{profile?.current_streak??0}</p><p className="text-[11px] text-indigo-100">Day streak</p></div><div className="rounded-2xl bg-white/10 p-3"><Trophy className="text-yellow-300" size={20}/><p className="mt-1 text-xl font-black">{achievements.length}</p><p className="text-[11px] text-indigo-100">Badges</p></div></div></div></div></section>
   <section className="mt-6"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-violet-600">Your learning journey</p><h2 className="mt-1 text-2xl font-black text-[#071b3a] sm:text-3xl">What do you want to do next?</h2></div><Sparkles className="text-yellow-500"/></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
    <Link href="/mission" className="group rounded-3xl bg-gradient-to-br from-violet-600 to-indigo-600 p-5 text-white shadow-lg shadow-violet-200 transition hover:-translate-y-1 hover:shadow-xl"><Zap size={24}/><h3 className="mt-5 text-xl font-black">Mission</h3><p className="mt-2 text-sm text-violet-100">Adaptive practice that focuses on the skills you need most.</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-black">Practise now <ArrowRight size={15}/></span></Link>
    <Link href="/challenge" className="group rounded-3xl bg-gradient-to-br from-orange-400 to-rose-500 p-5 text-white shadow-lg shadow-orange-200 transition hover:-translate-y-1 hover:shadow-xl"><Target size={24}/><h3 className="mt-5 text-xl font-black">Daily Challenge</h3><p className="mt-2 text-sm text-orange-50">Take today's 5-question maths sprint and keep your streak alive.</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-black">Start challenge <ArrowRight size={15}/></span></Link>
    <Link href="/progress" className="group rounded-3xl bg-gradient-to-br from-cyan-400 to-blue-500 p-5 text-white shadow-lg shadow-cyan-200 transition hover:-translate-y-1 hover:shadow-xl"><BarChart3 size={24}/><h3 className="mt-5 text-xl font-black">Progress</h3><p className="mt-2 text-sm text-cyan-50">See your mastery, accuracy, learning map and streak milestones.</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-black">View progress <ArrowRight size={15}/></span></Link>
    <Link href="/rewards" className="group rounded-3xl bg-gradient-to-br from-amber-400 to-yellow-500 p-5 text-[#3b2500] shadow-lg shadow-yellow-200 transition hover:-translate-y-1 hover:shadow-xl"><Trophy size={24}/><h3 className="mt-5 text-xl font-black">Rewards</h3><p className="mt-2 text-sm text-amber-950/70">Track XP, levels, streaks and the badges you have unlocked.</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-black">Open rewards <ArrowRight size={15}/></span></Link>
   </div></section>
   <section className="mt-7 grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-3xl border border-violet-100 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-violet-500">Pathway progress</p><p className="mt-1 text-2xl font-black text-[#071b3a]">{completedLessons} / {totalLessons} lessons</p></div><Link href="/progress" className="rounded-full bg-violet-50 px-3 py-1 text-sm font-black text-violet-600">{overallProgress}%</Link></div><div className="mt-5 h-4 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 via-fuchsia-500 to-cyan-400" style={{width:`${overallProgress}%`}}/></div><p className="mt-3 text-sm text-slate-500">Next destination: <span className="font-bold text-[#071b3a]">{nextTopicTitle}</span></p></div><div className="rounded-3xl bg-gradient-to-br from-amber-50 to-orange-50 p-6 ring-1 ring-amber-100"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-500 text-white"><Flame size={22}/></div><div><p className="text-xs font-black uppercase tracking-wider text-orange-600">Streak</p><p className="font-black text-[#071b3a]">{profile?.current_streak??0} days 🔥</p></div></div><p className="mt-4 text-sm leading-6 text-slate-600">Best streak: <b>{profile?.best_streak??0} days</b>. Complete today's challenge to keep building your habit.</p><Link href="/challenge" className="mt-4 inline-flex items-center gap-1 text-sm font-black text-orange-600">Keep streak alive <ArrowRight size={15}/></Link></div></section>
   <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-3xl bg-gradient-to-br from-violet-500 to-indigo-500 p-5 text-white"><Zap size={22}/><p className="mt-4 text-3xl font-black">{answered}</p><p className="text-sm text-violet-100">Questions answered</p></div><div className="rounded-3xl bg-gradient-to-br from-cyan-400 to-blue-500 p-5 text-white"><CheckCircle2 size={22}/><p className="mt-4 text-3xl font-black">{accuracy}%</p><p className="text-sm text-cyan-50">Accuracy</p></div><div className="rounded-3xl bg-gradient-to-br from-amber-400 to-orange-500 p-5 text-white"><Map size={22}/><p className="mt-4 text-3xl font-black">{completedTopics}</p><p className="text-sm text-orange-50">Topics completed</p></div><div className="rounded-3xl bg-gradient-to-br from-pink-400 to-rose-500 p-5 text-white"><Star size={22}/><p className="mt-4 text-3xl font-black">{profile?.best_streak??0}</p><p className="text-sm text-pink-50">Best streak</p></div></section>
   <section className="mt-9"><div className="flex items-end justify-between"><div><p className="text-sm font-black uppercase tracking-[0.15em] text-violet-600">Choose your adventure</p><h2 className="mt-1 text-2xl font-black text-[#071b3a] sm:text-3xl">Maths worlds</h2></div><BookOpen className="text-violet-500"/></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{topicIds.map((id,index)=>{const topic=topics.find(t=>t.id===id);if(!topic)return null;const style=topicStyles[index%topicStyles.length];const done=lessons.filter(l=>l.topic_id===id&&completedLessonIds.has(l.id)).length;const pct=Math.min(100,Math.round((done/(topic.lessons||1))*100));return <Link key={id} href={`/learn/${id}`} className="group overflow-hidden rounded-3xl border border-white bg-white shadow-sm transition duration-200 hover:-translate-y-1.5 hover:shadow-xl"><div className={`h-2 bg-gradient-to-r ${style.bg}`}/><div className="p-5"><div className="flex items-center justify-between"><div className={`flex h-12 w-12 items-center justify-center rounded-2xl ${style.soft} ${style.icon} text-xl font-black`}>{topic.title[0]}</div><span className="rounded-full bg-slate-50 px-2.5 py-1 text-xs font-black text-slate-500">{pct}%</span></div><h3 className="mt-5 font-extrabold text-[#071b3a] group-hover:text-violet-600">{topic.title}</h3><p className="mt-2 min-h-10 text-sm leading-5 text-slate-500">{topic.description}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full bg-gradient-to-r ${style.bg}`} style={{width:`${pct}%`}}/></div><span className="mt-4 inline-flex items-center gap-1 text-sm font-black text-violet-600">Enter world <ArrowRight size={15}/></span></div></Link>})}</div></section>
   <section className="mt-9 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-yellow-100 text-yellow-600"><Trophy size={22}/></div><div><h2 className="font-black text-[#071b3a]">Your trophy shelf</h2><p className="text-sm text-slate-500">Collect badges as you learn, practise and master new skills.</p></div></div><Link href="/rewards" className="inline-flex items-center gap-1 text-sm font-black text-violet-600">See all rewards <ArrowRight size={15}/></Link></div>{achievements.length>0?<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{achievements.map(a=><div key={a.id} className="rounded-2xl border border-yellow-100 bg-yellow-50 p-4"><span className="text-2xl">{a.icon}</span><p className="mt-2 font-bold text-[#071b3a]">{a.title}</p><p className="mt-1 text-xs text-slate-500">{a.description}</p></div>)}</div>:<div className="mt-5 rounded-2xl bg-gradient-to-r from-violet-50 to-cyan-50 p-5"><p className="font-bold text-[#071b3a]">Your first badge is waiting! 🌟</p><p className="mt-1 text-sm text-slate-500">Complete lessons and build your streak to unlock achievements.</p></div>}</section>
  </div>
 </main>;
}
