"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, Flame, LogOut, Sparkles, Star, Target, Trophy, Zap } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Profile={full_name:string|null;grade:string|null;learning_level:string|null;xp:number;current_streak:number;best_streak:number};
type Topic={id:string;title:string;description:string;level:string;lessons:number;sort_order:number};
type TopicProgress={topic_id:string;questions_answered:number;correct_answers:number;completed_at:string|null};
type Lesson={id:string;topic_id:string;title:string;lesson_number:number;sort_order:number};
type LessonProgress={lesson_id:string;completed_at:string|null};
type Achievement={id:string;title:string;description:string;icon:string};

const topicIds=["place-value","addition-subtraction","multiplication","fractions"];
const topicStyles=[
 {bg:"from-violet-500 to-indigo-500",soft:"bg-violet-50",icon:"text-violet-600"},
 {bg:"from-cyan-400 to-blue-500",soft:"bg-cyan-50",icon:"text-cyan-600"},
 {bg:"from-amber-400 to-orange-500",soft:"bg-amber-50",icon:"text-orange-600"},
 {bg:"from-pink-400 to-rose-500",soft:"bg-pink-50",icon:"text-pink-600"},
];

export default function DashboardPage(){
 const[profile,setProfile]=useState<Profile|null>(null),[status,setStatus]=useState("Loading your learning space…"),[topics,setTopics]=useState<Topic[]>([]),[topicProgress,setTopicProgress]=useState<TopicProgress[]>([]),[lessons,setLessons]=useState<Lesson[]>([]),[lessonProgress,setLessonProgress]=useState<LessonProgress[]>([]),[achievements,setAchievements]=useState<Achievement[]>([]);
 useEffect(()=>{const supabase=createClient();if(!supabase){setStatus("Supabase is not configured yet.");return;}supabase.auth.getUser().then(async({data,error})=>{if(error||!data.user){window.location.href="/login";return;}const[{data:row},{data:ts},{data:tp},{data:ls},{data:lp},{data:sa}]=await Promise.all([
  supabase.from("profiles").select("full_name,grade,learning_level,xp,current_streak,best_streak").eq("id",data.user.id).maybeSingle(),
  supabase.from("learning_topics").select("id,title,description,level,lessons,sort_order").order("sort_order"),
  supabase.from("topic_progress").select("topic_id,questions_answered,correct_answers,completed_at").eq("user_id",data.user.id),
  supabase.from("learning_lessons").select("id,topic_id,title,lesson_number,sort_order").order("sort_order"),
  supabase.from("lesson_progress").select("lesson_id,completed_at").eq("user_id",data.user.id),
  supabase.from("student_achievements").select("achievement_id,earned_at").eq("user_id",data.user.id)
 ]);setProfile(row??{full_name:data.user.user_metadata?.full_name??"Student",grade:null,learning_level:null,xp:0,current_streak:0,best_streak:0});setTopics((ts??[]) as Topic[]);setTopicProgress((tp??[]) as TopicProgress[]);setLessons((ls??[]) as Lesson[]);setLessonProgress((lp??[]) as LessonProgress[]);const ids=(sa??[]).map((a:{achievement_id:string})=>a.achievement_id);if(ids.length){const{data:ad}=await supabase.from("learning_achievements").select("id,title,description,icon").in("id",ids).order("sort_order");setAchievements((ad??[]) as Achievement[]);}setStatus("")})},[]);
 async function signOut(){const supabase=createClient();if(supabase)await supabase.auth.signOut();window.location.href="/"}
 const completedLessonIds=useMemo(()=>new Set(lessonProgress.filter(p=>p.completed_at).map(p=>p.lesson_id)),[lessonProgress]);
 const completedLessons=completedLessonIds.size;
 const totalLessons=lessons.length||21;
 const overallProgress=Math.round((completedLessons/totalLessons)*100);
 const answered=topicProgress.reduce((n,p)=>n+p.questions_answered,0),correct=topicProgress.reduce((n,p)=>n+p.correct_answers,0),completedTopics=topicProgress.filter(p=>p.completed_at).length;
 const accuracy=answered?Math.round((correct/answered)*100):0;
 const nextLesson=lessons.filter(l=>!completedLessonIds.has(l.id)).sort((a,b)=>a.sort_order-b.sort_order)[0];
 const nextTopic=nextLesson?.topic_id||"place-value";
 const nextTopicTitle=topics.find(t=>t.id===nextTopic)?.title||"Place Value";
 const firstName=(profile?.full_name||"Student").split(" ")[0];
 if(status)return <main className="flex min-h-screen items-center justify-center bg-gradient-to-br from-violet-50 via-white to-cyan-50 p-6"><div className="rounded-3xl border border-white bg-white p-8 text-center shadow-xl"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-400 text-white"><Sparkles/></div><p className="mt-4 font-semibold text-[#071b3a]">{status}</p><Link href="/login" className="mt-4 inline-block text-sm font-bold text-violet-600">Go to student login</Link></div></main>;
 return <main className="min-h-screen bg-gradient-to-br from-[#f7f7ff] via-white to-[#f0fbff]">
  <header className="sticky top-0 z-20 border-b border-white/70 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-600 to-indigo-500 text-xl font-black text-white shadow-lg shadow-violet-200">F</div><div><p className="text-sm font-black tracking-wide text-[#071b3a]">FAHI VISSNUN</p><p className="text-xs text-slate-500">Math Adventure</p></div></Link><button onClick={signOut} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-600 transition hover:border-violet-200 hover:text-violet-600"><LogOut size={16}/> Sign out</button></div></header>
  <div className="mx-auto max-w-7xl px-5 py-7 lg:px-8 lg:py-9">
   <section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-violet-600 via-indigo-600 to-blue-500 p-7 text-white shadow-2xl shadow-indigo-200 sm:p-9"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-fuchsia-400/25 blur-2xl"/><div className="absolute -bottom-24 left-1/3 h-64 w-64 rounded-full bg-cyan-300/20 blur-2xl"/><div className="relative flex flex-col gap-7 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-2xl"><div className="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1.5 text-xs font-black uppercase tracking-wider"><Sparkles size={14}/> Your learning adventure</div><h1 className="mt-4 text-3xl font-black sm:text-5xl">Hey {firstName}! <span className="text-yellow-300">Let’s level up.</span> 🚀</h1><p className="mt-3 max-w-xl text-sm leading-6 text-indigo-100 sm:text-base">{nextLesson?`Your next mission is ${nextLesson.title}. A few minutes today can keep your maths streak alive.`:"Amazing work — you completed your learning pathway!"}</p><Link href={nextLesson?`/learn/${nextTopic}/lesson/${nextLesson.id}`:"/learn"} className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-yellow-300 px-5 py-3.5 font-black text-[#24134f] shadow-lg shadow-yellow-900/20 transition hover:-translate-y-0.5 hover:bg-yellow-200">{nextLesson?"Continue Mission":"Explore More"} <ArrowRight size={18}/></Link></div><div className="grid grid-cols-3 gap-2 sm:gap-3"><div className="rounded-2xl bg-white/12 p-4 text-center backdrop-blur"><Trophy className="mx-auto text-yellow-300" size={23}/><p className="mt-2 text-xl font-black">{profile?.xp??0}</p><p className="text-[11px] font-semibold text-indigo-100">XP earned</p></div><div className="rounded-2xl bg-white/12 p-4 text-center backdrop-blur"><Flame className="mx-auto text-orange-300" size={23}/><p className="mt-2 text-xl font-black">{profile?.current_streak??0}</p><p className="text-[11px] font-semibold text-indigo-100">Day streak</p></div><div className="rounded-2xl bg-white/12 p-4 text-center backdrop-blur"><Star className="mx-auto text-cyan-200" size={23}/><p className="mt-2 text-xl font-black">{overallProgress}%</p><p className="text-[11px] font-semibold text-indigo-100">Pathway</p></div></div></div></section>
   <section className="mt-6 grid gap-4 lg:grid-cols-[1.4fr_.6fr]"><div className="rounded-3xl border border-violet-100 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-violet-500">Adventure progress</p><p className="mt-1 text-2xl font-black text-[#071b3a]">{completedLessons} / {totalLessons} lessons</p></div><span className="rounded-full bg-violet-50 px-3 py-1 text-sm font-black text-violet-600">{overallProgress}%</span></div><div className="mt-5 h-4 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 via-fuchsia-500 to-cyan-400 transition-all" style={{width:`${overallProgress}%`}}/></div><p className="mt-3 text-sm text-slate-500">Next destination: <span className="font-bold text-[#071b3a]">{nextTopicTitle}</span></p></div><div className="rounded-3xl bg-gradient-to-br from-amber-50 to-orange-50 p-6 shadow-sm ring-1 ring-amber-100"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-500 text-white shadow-lg shadow-orange-200"><Target size={22}/></div><div><p className="text-xs font-black uppercase tracking-wider text-orange-600">Daily mission</p><p className="font-black text-[#071b3a]">10 maths questions</p></div></div><p className="mt-4 text-sm leading-6 text-slate-600">Keep your streak moving and earn more XP with a focused practice session.</p><Link href="/learn" className="mt-4 inline-flex items-center gap-1 text-sm font-black text-orange-600">Start mission <ArrowRight size={15}/></Link></div></section>
   <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-3xl bg-gradient-to-br from-violet-500 to-indigo-500 p-5 text-white shadow-lg shadow-violet-100"><Zap size={22}/><p className="mt-4 text-3xl font-black">{answered}</p><p className="text-sm text-violet-100">Questions answered</p></div><div className="rounded-3xl bg-gradient-to-br from-cyan-400 to-blue-500 p-5 text-white shadow-lg shadow-cyan-100"><CheckCircle2 size={22}/><p className="mt-4 text-3xl font-black">{accuracy}%</p><p className="text-sm text-cyan-50">Accuracy</p></div><div className="rounded-3xl bg-gradient-to-br from-amber-400 to-orange-500 p-5 text-white shadow-lg shadow-orange-100"><Trophy size={22}/><p className="mt-4 text-3xl font-black">{completedTopics}</p><p className="text-sm text-orange-50">Topics completed</p></div><div className="rounded-3xl bg-gradient-to-br from-pink-400 to-rose-500 p-5 text-white shadow-lg shadow-pink-100"><Flame size={22}/><p className="mt-4 text-3xl font-black">{profile?.best_streak??0}</p><p className="text-sm text-pink-50">Best streak</p></div></section>
   <section className="mt-9"><div className="flex items-end justify-between"><div><p className="text-sm font-black uppercase tracking-[0.15em] text-violet-600">Choose your adventure</p><h2 className="mt-1 text-2xl font-black text-[#071b3a] sm:text-3xl">Maths worlds</h2></div><BookOpen className="text-violet-500"/></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{topicIds.map((id,index)=>{const topic=topics.find(t=>t.id===id);if(!topic)return null;const style=topicStyles[index%topicStyles.length];const done=lessons.filter(l=>l.topic_id===id&&completedLessonIds.has(l.id)).length;const pct=Math.round((done/(topic.lessons||1))*100);return <Link key={id} href={`/learn/${id}`} className="group overflow-hidden rounded-3xl border border-white bg-white shadow-sm transition duration-200 hover:-translate-y-1.5 hover:shadow-xl"><div className={`h-2 bg-gradient-to-r ${style.bg}`}/><div className="p-5"><div className="flex items-center justify-between"><div className={`flex h-12 w-12 items-center justify-center rounded-2xl ${style.soft} ${style.icon} text-xl font-black`}>{topic.title[0]}</div><span className="rounded-full bg-slate-50 px-2.5 py-1 text-xs font-black text-slate-500">{pct}%</span></div><h3 className="mt-5 font-extrabold text-[#071b3a] group-hover:text-violet-600">{topic.title}</h3><p className="mt-2 min-h-10 text-sm leading-5 text-slate-500">{topic.description}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full bg-gradient-to-r ${style.bg}`} style={{width:`${pct}%`}}/></div><span className="mt-4 inline-flex items-center gap-1 text-sm font-black text-violet-600">Enter world <ArrowRight size={15} className="transition group-hover:translate-x-1"/></span></div></Link>})}</div></section>
   <section className="mt-9 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-yellow-100 text-yellow-600"><Trophy size={22}/></div><div><h2 className="font-black text-[#071b3a]">Your trophy shelf</h2><p className="text-sm text-slate-500">Collect badges as you learn, practise and master new skills.</p></div></div>{achievements.length>0?<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{achievements.map(a=><div key={a.id} className="rounded-2xl border border-yellow-100 bg-yellow-50 p-4"><span className="text-2xl">{a.icon}</span><p className="mt-2 font-bold text-[#071b3a]">{a.title}</p><p className="mt-1 text-xs text-slate-500">{a.description}</p></div>)}</div>:<div className="mt-5 rounded-2xl bg-gradient-to-r from-violet-50 to-cyan-50 p-5"><p className="font-bold text-[#071b3a]">Your first badge is waiting! 🌟</p><p className="mt-1 text-sm text-slate-500">Complete lessons and build your streak to unlock achievements.</p></div>}</section>
  </div><footer className="mx-auto max-w-7xl px-5 pb-8 pt-2 text-center text-xs text-slate-400 lg:px-8">© 2026 FAHI VISSNUN Learning Institute · Math Adventure</footer>
 </main>;
}
