import Link from "next/link";
import { ArrowLeft, Lock, Play } from "lucide-react";
import CategoryGameIllustration from "@/components/brain-games/CategoryGameIllustration";

const games = [
  { title: "Number Order", description: "Remember the numbers and rebuild them in the correct order.", href: "/brain-games/number-order", reward: "+30 XP", active: true, illustration: "order" },
  { title: "Pattern Quest", description: "Discover the rule and continue the changing number pattern.", href: "/brain-games/pattern-quest", reward: "+30 XP", active: true, illustration: "pattern" },
];
const categories = [["🧠","Brain Boost","memory"],["🔄","Brain Twist","flexibility"],["⚡","Speed Rush","speed"],["🎯","Spot On!","attention"],["🧩","Puzzle Power","problem-solving"],["🗺️","Brain Quest","adventure"]] as const;

export default function FlexibilityPage(){return <main className="min-h-screen overflow-x-hidden bg-[#f0fff9] px-3 py-2 text-[#17395f] sm:px-5 sm:py-3"><div className="mx-auto max-w-6xl">
<header className="flex h-8 items-center justify-between px-1"><Link href="/brain-games" className="inline-flex items-center gap-1 rounded-full px-2 py-1 text-[10px] font-black text-slate-500 hover:bg-white"><ArrowLeft size={13}/> Brain Games</Link><Link href="/dashboard" className="rounded-full px-2 py-1 text-[10px] font-black text-slate-500 hover:bg-white">Home</Link></header>
<section className="relative px-1 pb-3 pt-1 text-center sm:pb-4"><div className="pointer-events-none absolute left-[15%] top-1 text-lg text-emerald-400 sm:text-xl">✦</div><div className="pointer-events-none absolute right-[15%] top-3 text-sm text-teal-400 sm:text-lg">✦</div><h1 className="inline-block bg-gradient-to-r from-emerald-500 via-teal-500 to-cyan-500 bg-clip-text text-3xl font-black leading-none tracking-tight text-transparent drop-shadow-[0_3px_0_rgba(255,255,255,.95)] sm:text-4xl md:text-5xl" style={{fontFamily:"'Comic Sans MS', 'Trebuchet MS', cursive"}}>🔄 BRAIN TWIST</h1></section>
<nav className="flex gap-1.5 overflow-x-auto border-y border-emerald-100 py-1.5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{categories.map(([icon,title,href])=><Link key={href} href={`/brain-games/${href}`} className={`flex shrink-0 items-center gap-1 rounded-full border px-2.5 py-1 text-[9px] font-black sm:text-[10px] ${href==="flexibility"?"border-emerald-400 bg-emerald-500 text-white":"border-transparent bg-white text-slate-500 hover:border-emerald-100"}`}><span>{icon}</span>{title}</Link>)}</nav>
<section className="mt-2.5"><div className="mb-1.5 flex items-center justify-between px-1"><h2 className="text-sm font-black text-slate-800 sm:text-base">What do you want to play? 🎮</h2><span className="text-[8px] font-black text-emerald-400">2 GAMES</span></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{games.map(game=><article key={game.title} className="group rounded-2xl border border-white bg-white p-1.5 shadow-[0_4px_14px_rgba(15,23,42,.07)] transition duration-200 hover:-translate-y-0.5 hover:shadow-[0_8px_18px_rgba(15,23,42,.1)]"><div className="relative h-28 overflow-hidden rounded-xl bg-emerald-50 sm:h-32"><div className="h-full w-full transition duration-200 group-hover:scale-[1.05]"><CategoryGameIllustration type={game.illustration}/></div><span className="absolute left-1.5 top-1.5 z-10 rounded-full bg-white px-1.5 py-0.5 text-[7px] font-black text-emerald-600 shadow-sm">READY!</span><span className="absolute right-1.5 top-1.5 z-10 rounded-full bg-white px-1.5 py-0.5 text-[7px] font-black text-emerald-600 shadow-sm">{game.reward}</span></div><div className="px-0.5 pt-1.5"><div className="flex items-center justify-between gap-1"><h3 className="truncate text-[12px] font-black text-slate-800 sm:text-[13px]">{game.title}</h3>{!game.active&&<Lock size={10} className="shrink-0 text-slate-300"/>}</div><p className="mt-0.5 truncate text-[9px] font-bold text-slate-400">{game.description}</p>{game.active?<Link href={game.href} className="mt-1.5 inline-flex w-full items-center justify-center gap-1 rounded-lg bg-emerald-500 px-2 py-1.5 text-[10px] font-black text-white transition hover:bg-emerald-600"><Play size={10} fill="currentColor"/> PLAY</Link>:<span className="mt-1.5 inline-flex w-full items-center justify-center rounded-lg bg-slate-100 px-2 py-1.5 text-[9px] font-black text-slate-400">Coming Soon</span>}</div></article>)}</div></section><p className="mt-2 pb-1 text-center text-[9px] font-black text-slate-400">🌟 Change your thinking and discover new ways! 🌟</p></div></main>}
