"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {BarChart3,Gamepad2,Gift,GraduationCap,Home,Printer,RefreshCw,Trophy} from "lucide-react";
import NotificationBell from "@/components/learner-notification-bell";

type Problem={question:string;answer:string;visual?:string;options?:string[]};
const topics=["Place Value to 1000","Number Names to 1000","Expanded Form to 1000","Compare Numbers to 1000","Order Numbers to 1000","Number Patterns to 1000","Addition to 100","Subtraction to 100","Multiplication by 2","Multiplication by 5","Multiplication by 10","Equal Sharing","Quarter-Hour Time","Odd and Even Numbers","Shape Patterns","Skip Counting by 2 5 10","Fractions of Collections","Unit Fractions","Compare Fractions","Measure Length","Compare Mass","Compare Capacity","Calendar Dates","Identify Shapes","Count Vertices","Half and Quarter Turns","Read a Data Table","Read a Pictograph"] as const;
type Topic=typeof topics[number];
const words=(n:number):string=>{
 const ones=["zero","one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen"];
 const tens=["","","twenty","thirty","forty","fifty","sixty","seventy","eighty","ninety"];
 if(n<20)return ones[n];if(n<100)return tens[Math.floor(n/10)]+(n%10?"-"+ones[n%10]:"");
 if(n<1000)return ones[Math.floor(n/100)]+" hundred"+(n%100?" and "+words(n%100):"");
 return "one thousand";
};
const generate=(topic:Topic,challenge:number,index:number,seed:number):Problem=>{
 const k=index+seed*17+challenge*11;
 const max=challenge===1?200:challenge===2?500:999;
 const a=101+(k*37%(max-100)),b=101+(k*53+19)%(max-100);
 const small=challenge===1?20:challenge===2?50:100;
 switch(topic){
 case "Place Value to 1000":{const n=a,d=k%3;return{question:d===0?`How many hundreds are in ${n}?`:d===1?`How many tens are in the tens place of ${n}?`:`How many ones are in ${n}?`,answer:String(d===0?Math.floor(n/100):d===1?Math.floor(n/10)%10:n%10),visual:`Hundreds | Tens | Ones\n${Math.floor(n/100)}             ${Math.floor(n/10)%10}          ${n%10}`};}
 case "Number Names to 1000":return{question:`Write ${a} in words.`,answer:words(a)};
 case "Expanded Form to 1000":return{question:`Write ${a} in expanded form.`,answer:[Math.floor(a/100)*100,Math.floor(a/10)%10*10,a%10].filter(x=>x>0).join(" + ")};
 case "Compare Numbers to 1000":return{question:`Fill in >, < or =: ${a} ___ ${k%5===0?a:b}`,answer:a===(k%5===0?a:b)?"=":a>b?">":"<",options:[">","<","="]};
 case "Order Numbers to 1000":{const nums=Array.from({length:4},(_,j)=>101+(k*31+j*73)%(max-100));const asc=k%2===0;return{question:`Put these numbers in ${asc?"ascending":"descending"} order: ${nums.join(", ")}`,answer:[...nums].sort((x,y)=>asc?x-y:y-x).join(", ")};}
 case "Number Patterns to 1000":{const step=challenge===1?10:challenge===2?25:50,first=100+(k*step)%Math.max(step,max-100-step*3);return{question:`Fill in the missing number: ${first}, ${first+step}, ___, ${first+step*3}`,answer:String(first+step*2)};}
 case "Addition to 100":{const x=1+(k*7%small),y=1+(k*13%(101-x));return{question:`${x} + ${y} = ?`,answer:String(x+y)};}
 case "Subtraction to 100":{const x=small+(k*7%(101-small)),y=1+(k*11%x);return{question:`${x} − ${y} = ?`,answer:String(x-y)};}
 case "Multiplication by 2":case "Multiplication by 5":case "Multiplication by 10":{const m=Number(topic.split("by ")[1]),n=1+(k*7%(challenge===1?5:challenge===2?10:12));return{question:`${n} × ${m} = ?`,answer:String(n*m),visual:challenge===1?Array.from({length:n},()=>`[ ${m} ]`).join("  "):undefined};}
 case "Equal Sharing":{const groups=[2,5,10][k%3],each=1+(k*3%(challenge===1?4:challenge===2?7:10));return{question:`Share ${groups*each} objects equally among ${groups} children. How many does each child get?`,answer:String(each),visual:"● ".repeat(Math.min(groups*each,30))};}
 case "Quarter-Hour Time":{const hour=1+k%12,minute=[0,15,30,45][k%4];return{question:`Write the digital time: ${minute===0?hour+" o'clock":minute===15?"quarter past "+hour:minute===30?"half past "+hour:"quarter to "+(hour===12?1:hour+1)}.`,answer:`${hour}:${String(minute).padStart(2,"0")}`};}

 case "Odd and Even Numbers":return{question:`Is ${a} odd or even?`,answer:a%2?"odd":"even",options:["odd","even"]};
 case "Shape Patterns":{const symbols=["●","▲","■"],period=2+k%2,seq=Array.from({length:6},(_,j)=>symbols[(j+k)%period]);return{question:"What shape comes next in the pattern? Write circle, triangle or square.",visual:seq.join("  ")+"  ?",answer:({ "●":"circle","▲":"triangle","■":"square"} as Record<string,string>)[symbols[(6+k)%period]]};}
 case "Skip Counting by 2 5 10":{const step=[2,5,10][k%3],start=step*(1+k%Math.floor(90/step));return{question:`Complete: ${start}, ${start+step}, ___, ${start+step*3}`,answer:String(start+step*2)};}
 case "Unit Fractions":{const den=[2,3,4,5,6][k%5];return{question:`One part of a shape divided into ${den} equal parts is what fraction? Write 1/2, 1/3 etc.`,answer:`1/${den}`,visual:"■ ".repeat(den)};}
 case "Fractions of Collections":{const den=[2,3,4,5][k%4],part=1+k%5,total=den*part;return{question:`What is 1/${den} of ${total} objects?`,answer:String(part),visual:"● ".repeat(total)};}
 case "Compare Fractions":{const den=[2,3,4,5,6][k%5],other=[2,3,4,5,6][(k+2)%5];return{question:`Which is larger: 1/${den} or 1/${other}? Write the fraction.`,answer:`1/${Math.min(den,other)}`};}
 case "Measure Length":{const n=1+k%(challenge===1?15:challenge===2?50:100);return{question:"How long is the line in centimetres? (Use the labelled scale.)",visual:`0 cm |────────| ${n} cm`,answer:String(n)};}
 case "Compare Mass":{const x=100+(k*37%900),y=100+(k*19%900);return{question:`Which is heavier: A (${x} g) or B (${y} g)?`,answer:x>=y?"A":"B",options:["A","B"]};}
 case "Compare Capacity":{const x=100+(k*37%900),y=100+(k*19%900);return{question:`Which holds more: A (${x} mL) or B (${y} mL)?`,answer:x>=y?"A":"B",options:["A","B"]};}
 case "Calendar Dates":{const day=1+k%27;return{question:`If today is the ${day}th of the month, what date is tomorrow? Write the day number.`,answer:String(day+1)};}
 case "Identify Shapes":{const names=["circle","triangle","square","rectangle"],icons=["●","▲","■","▭"],i=k%4;return{question:"Name the shape shown.",visual:icons[i],answer:names[i]};}
 case "Count Vertices":{const names=["triangle","square","rectangle","pentagon"],verts=[3,4,4,5],i=k%4;return{question:`How many vertices (corners) does a ${names[i]} have?`,answer:String(verts[i])};}
 case "Half and Quarter Turns":{const dir=["up","right","down","left"],turn=k%2?"half":"quarter",start=k%4,end=(start+(turn==="half"?2:1))%4;return{question:`An arrow points ${dir[start]}. Turn it ${turn==="half"?"half a turn":"a quarter turn clockwise"}. Which direction does it point?`,answer:dir[end],options:dir};}
 case "Read a Data Table":{const vals=[2+k%4,3+(k*3)%5,1+(k*5)%4],labels=["Fish","Shells","Turtles"];return{question:"How many items are there altogether in the table?",visual:labels.map((x,j)=>x+": "+vals[j]).join("\\n"),answer:String(vals.reduce((x,y)=>x+y,0))};}
 case "Read a Pictograph":{const vals=[2+k%4,4+(k*3)%4,3+(k*5)%4],names=["Fish","Shells","Turtles"],mode=k%3;return{question:mode===0?"Which group has the most?":mode===1?"How many pictures are there altogether?":"How many more fish than shells, or shells than fish?",answer:mode===0?names[vals.indexOf(Math.max(...vals))]:String(mode===1?vals.reduce((x,y)=>x+y,0):Math.abs(vals[0]-vals[1])),visual:vals.map((n,j)=>names[j]+": "+["🐟","🐚","🐢"][j].repeat(n)).join("\n")};}
 }
};
const norm=(s:string,topic:Topic)=>{let x=s.trim().toLowerCase().replace(/\s+/g," ");if(topic==="Expanded Form to 1000")x=x.replace(/\s/g,"");if(topic==="Order Numbers to 1000")x=x.replace(/\s/g,"");if(topic==="Number Names to 1000")x=x.replace(/-/g," ");if(topic==="Quarter-Hour Time")x=x.replace(/^0(?=\d:)/,"");return x;};
export default function Grade2Worksheets(){
 const [topic,setTopic]=useState<Topic>("Place Value to 1000"),[challenge,setChallenge]=useState(1),[count,setCount]=useState(5),[seed,setSeed]=useState(0);
 const [answers,setAnswers]=useState<Record<number,string>>({}),[checked,setChecked]=useState(false),[printMode,setPrintMode]=useState<"blank"|"completed"|"key"|null>(null);
 const problems=Array.from({length:count},(_,i)=>generate(topic,challenge,i,seed));
 useEffect(()=>{setAnswers({});setChecked(false)},[topic,challenge,count,seed]);
 useEffect(()=>{const done=()=>setPrintMode(null);window.addEventListener("afterprint",done);return()=>window.removeEventListener("afterprint",done)},[]);
 const score=problems.filter((p,i)=>norm(answers[i]??"",topic)===norm(p.answer,topic)).length;
 const print=(mode:"blank"|"completed"|"key")=>{setPrintMode(mode);setTimeout(()=>window.print(),180)};
 return <main className="min-h-screen bg-[#f8f5e9] text-[#17234b] print:bg-white">
 <header className="sticky top-0 z-40 hidden h-[90px] bg-[#073b73] text-white shadow-sm lg:block print:hidden"><div className="mx-auto flex h-full max-w-[1680px] items-center justify-between px-12"><Link href="/dashboard" className="rounded-2xl bg-white px-3 py-1.5"><img src="/fahi-hisaabu-logo-optimized.webp" alt="Fahi Hisaabu" className="h-[57px] w-auto max-w-[220px] object-contain"/></Link><nav className="flex items-center gap-5 text-base font-bold"><Link href="/dashboard" className="flex items-center gap-2"><Home size={20}/>Home</Link><Link href="/brain-games" className="flex items-center gap-2"><Gamepad2 size={20}/>Games</Link><Link href="/leaderboard" className="flex items-center gap-2"><Trophy size={20}/>Leaderboard</Link><Link href="/rewards" className="flex items-center gap-2"><Gift size={20}/>Rewards</Link><Link href="/progress" className="flex items-center gap-2"><BarChart3 size={20}/>Progress</Link><Link href="/profile" className="flex items-center gap-2"><GraduationCap size={20}/>Profile</Link><NotificationBell/></nav></div></header>
 <div className="mx-auto max-w-5xl px-4 py-6 print:max-w-none print:p-0"><div className="mb-5 flex flex-wrap items-center justify-between gap-3 print:hidden"><div><h1 className="text-3xl font-black">Grade 2 Worksheets</h1><p className="text-sm font-semibold text-slate-600">Based on Exploring Mathematics 2: ten textbook chapters.</p></div></div>
 <section className="rounded-3xl bg-white p-5 shadow-sm print:hidden"><div className="grid gap-3 sm:grid-cols-4"><label className="font-bold">Topic<select value={topic} onChange={e=>setTopic(e.target.value as Topic)} className="mt-2 w-full rounded-xl border p-3">{topics.map(x=><option key={x}>{x}</option>)}</select></label><label className="font-bold">Challenge<select value={challenge} onChange={e=>setChallenge(+e.target.value)} className="mt-2 w-full rounded-xl border p-3">{[1,2,3].map(x=><option key={x} value={x}>Challenge {x}</option>)}</select></label><label className="font-bold">Questions<select value={count} onChange={e=>setCount(+e.target.value)} className="mt-2 w-full rounded-xl border p-3">{[5,10,15,20].map(x=><option key={x}>{x}</option>)}</select></label><div className="flex items-end"><button onClick={()=>setSeed(x=>x+1)} className="flex w-full items-center justify-center gap-2 rounded-xl bg-amber-400 p-3 font-black"><RefreshCw size={18}/>New Worksheet</button></div></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>setChecked(true)} className="rounded-xl bg-violet-700 px-5 py-3 font-bold text-white">Check Answers</button><button onClick={()=>print("blank")} className="flex items-center gap-2 rounded-xl border px-4 py-3 font-bold"><Printer size={18}/>Blank PDF / Print</button><button onClick={()=>print("completed")} className="rounded-xl border px-4 py-3 font-bold">Print My Answers</button><button onClick={()=>print("key")} className="rounded-xl border px-4 py-3 font-bold">Answer Key</button></div>{checked&&<p className="mt-4 text-xl font-black" role="status">Score: {score} / {count} ({Math.round(score/count*100)}%)</p>}</section>
 <section className="mt-5 rounded-3xl border-2 border-amber-200 bg-white p-5 sm:p-8 print:mt-0 print:border-0 print:p-0"><div className="mb-5 flex items-center justify-between gap-4 border-b-2 pb-4"><div><h2 className="text-2xl font-black">Grade 2 · {topic}</h2><p className="text-sm font-semibold">Challenge {challenge} · {count} questions</p></div><div className="text-sm font-bold">Date: __________</div></div><div className="mb-6 text-sm font-bold">Name: ____________________________________</div><div className="grid gap-4 sm:grid-cols-2">{problems.map((p,i)=>{const correct=norm(answers[i]??"",topic)===norm(p.answer,topic);return <div key={i} className="min-w-0 break-inside-avoid rounded-2xl border-2 border-slate-200 p-4 print:break-inside-avoid"><div className="flex gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-violet-100 font-black print:border print:bg-white">{i+1}</span><div className="min-w-0 flex-1"><p className="text-lg font-black">{p.question}</p>{p.visual&&<p className="my-3 whitespace-pre-wrap break-words rounded-xl bg-sky-50 p-3 text-base font-bold print:border print:bg-white">{p.visual}</p>}{p.options&&!printMode?<div className="mt-3 flex gap-2">{p.options.map(x=><button key={x} onClick={()=>setAnswers(v=>({...v,[i]:x}))} className={`rounded-xl border-2 px-5 py-2 text-xl font-black ${answers[i]===x?"border-violet-600 bg-violet-100":"border-slate-200"}`}>{x}</button>)}</div>:null}<div className="mt-3">{printMode?<div className="min-h-10 border-b-2 border-slate-300 p-2 font-bold">{printMode==="key"?p.answer:printMode==="completed"?answers[i]??"":""}</div>:<input aria-label={`Answer to question ${i+1}`} value={answers[i]??""} onChange={e=>setAnswers(v=>({...v,[i]:e.target.value}))} placeholder="Your answer" className="w-full rounded-xl border-2 border-slate-200 p-3 font-semibold"/>}</div>{checked&&!printMode&&<p className={`mt-2 text-sm font-black ${correct?"text-green-700":"text-red-700"}`}>{correct?"Correct!":"Try again"}</p>}</div></div></div>})}</div></section></div></main>;
}
