-- Rewards & Persistence 3.0
-- Persistent gems, coins, badges, achievements, daily rewards, combo records and reward history.

create table if not exists public.student_rewards (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  coins integer not null default 0 check (coins >= 0),
  gems integer not null default 0 check (gems >= 0),
  lifetime_xp integer not null default 0 check (lifetime_xp >= 0),
  best_combo integer not null default 0 check (best_combo >= 0),
  missions_completed integer not null default 0 check (missions_completed >= 0),
  daily_claimed_at date,
  daily_streak integer not null default 0 check (daily_streak >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.student_badges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  badge_key text not null,
  badge_name text not null,
  description text not null default '',
  earned_at timestamptz not null default now(),
  unique(user_id, badge_key)
);

create table if not exists public.student_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  achievement_key text not null,
  progress integer not null default 0,
  target integer not null default 1,
  completed boolean not null default false,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(user_id, achievement_key)
);

create table if not exists public.student_reward_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  source text not null,
  reason text not null,
  coins integer not null default 0,
  gems integer not null default 0,
  xp integer not null default 0,
  combo integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists student_reward_history_user_created_idx on public.student_reward_history(user_id, created_at desc);
create index if not exists student_badges_user_idx on public.student_badges(user_id);
create index if not exists student_achievements_user_idx on public.student_achievements(user_id);

alter table public.student_rewards enable row level security;
alter table public.student_badges enable row level security;
alter table public.student_achievements enable row level security;
alter table public.student_reward_history enable row level security;

drop policy if exists student_rewards_self on public.student_rewards;
create policy student_rewards_self on public.student_rewards for select using (auth.uid() = user_id);
drop policy if exists student_badges_self on public.student_badges;
create policy student_badges_self on public.student_badges for select using (auth.uid() = user_id);
drop policy if exists student_achievements_self on public.student_achievements;
create policy student_achievements_self on public.student_achievements for select using (auth.uid() = user_id);
drop policy if exists student_reward_history_self on public.student_reward_history;
create policy student_reward_history_self on public.student_reward_history for select using (auth.uid() = user_id);

create or replace function public.get_student_rewards()
returns table(coins integer, gems integer, lifetime_xp integer, best_combo integer, missions_completed integer, daily_claimed_at date, daily_streak integer)
language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  insert into public.student_rewards(user_id) values(auth.uid()) on conflict(user_id) do nothing;
  return query select r.coins,r.gems,r.lifetime_xp,r.best_combo,r.missions_completed,r.daily_claimed_at,r.daily_streak from public.student_rewards r where r.user_id=auth.uid();
end; $$;

create or replace function public.award_mission_rewards(p_xp integer, p_combo integer, p_correct integer, p_total integer, p_perfect boolean default false)
returns table(coins_awarded integer, gems_awarded integer, badge_key text, daily_bonus integer)
language plpgsql security definer set search_path = public
as $$
declare
  uid uuid := auth.uid(); c integer := greatest(0, floor(greatest(0,p_xp)::numeric / 5)::integer); g integer := case when p_perfect then 5 else case when p_correct >= greatest(1,p_total/2) then 2 else 0 end end; b text := null; d integer := 0;
  old_best integer;
begin
  if uid is null then raise exception 'Not authenticated'; end if;
  insert into public.student_rewards(user_id) values(uid) on conflict(user_id) do nothing;
  select best_combo into old_best from public.student_rewards where user_id=uid;
  if p_combo > coalesce(old_best,0) then update public.student_rewards set best_combo=p_combo where user_id=uid; end if;
  if p_perfect then b := 'perfect-run'; end if;
  update public.student_rewards set coins=coins+c, gems=gems+g, lifetime_xp=lifetime_xp+greatest(0,p_xp), missions_completed=missions_completed+1, updated_at=now() where user_id=uid;
  insert into public.student_reward_history(user_id,source,reason,coins,gems,xp,combo,metadata) values(uid,'mission','Math Adventure completed',c,g,greatest(0,p_xp),greatest(0,p_combo),jsonb_build_object('correct',p_correct,'total',p_total,'perfect',p_perfect));
  if b is not null then insert into public.student_badges(user_id,badge_key,badge_name,description) values(uid,b,'Perfect Run','Completed a Math Adventure without hints or retries') on conflict(user_id,badge_key) do nothing; end if;
  insert into public.student_achievements(user_id,achievement_key,progress,target,completed,completed_at) values(uid,'missions',1,10,false,null) on conflict(user_id,achievement_key) do update set progress=student_achievements.progress+1, completed=(student_achievements.progress+1)>=student_achievements.target, completed_at=case when (student_achievements.progress+1)>=student_achievements.target then coalesce(student_achievements.completed_at,now()) else student_achievements.completed_at end, updated_at=now();
  if p_perfect then insert into public.student_achievements(user_id,achievement_key,progress,target,completed,completed_at) values(uid,'perfect-runs',1,5,false,null) on conflict(user_id,achievement_key) do update set progress=student_achievements.progress+1, completed=(student_achievements.progress+1)>=student_achievements.target, completed_at=case when (student_achievements.progress+1)>=student_achievements.target then coalesce(student_achievements.completed_at,now()) else student_achievements.completed_at end, updated_at=now(); end if;
  return query select c,g,b,d;
end; $$;

grant execute on function public.get_student_rewards() to authenticated;
grant execute on function public.award_mission_rewards(integer,integer,integer,integer,boolean) to authenticated;
