-- Student Profile & Parent/Teacher Analytics 3.0
-- Secure profile metadata, guardian/teacher links and report-ready analytics views.

alter table public.profiles
  add column if not exists display_name text,
  add column if not exists avatar_emoji text not null default '🧑‍🎓',
  add column if not exists school_name text,
  add column if not exists class_name text,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.student_relationships (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  related_user_id uuid not null references public.profiles(id) on delete cascade,
  relationship text not null check (relationship in ('parent','guardian','teacher')),
  status text not null default 'active' check (status in ('active','revoked')),
  created_at timestamptz not null default now(),
  unique(student_id, related_user_id, relationship)
);

create index if not exists student_relationships_related_idx on public.student_relationships(related_user_id,status);
create index if not exists student_relationships_student_idx on public.student_relationships(student_id,status);

alter table public.student_relationships enable row level security;

drop policy if exists student_relationships_self on public.student_relationships;
create policy student_relationships_self on public.student_relationships
for select using (auth.uid() = student_id or auth.uid() = related_user_id);

-- A compact, reusable report function. It only returns the requesting user's
-- own student record, or students explicitly linked to the requesting account.
create or replace function public.get_learning_report(p_student_id uuid default null)
returns table(
  student_id uuid,
  display_name text,
  grade text,
  learning_level text,
  school_name text,
  class_name text,
  xp integer,
  current_streak integer,
  best_streak integer,
  total_questions bigint,
  total_correct bigint,
  accuracy integer,
  average_mastery integer,
  topics_explored bigint,
  missions_completed integer,
  best_combo integer,
  coins integer,
  gems integer
)
language sql security definer set search_path=public
as $$
  with target as (
    select coalesce(p_student_id, auth.uid()) as id
  ),
  allowed as (
    select id from target where id = auth.uid()
    union
    select sr.student_id
      from public.student_relationships sr
      join target t on t.id = auth.uid()
     where sr.related_user_id = auth.uid() and sr.status = 'active'
  ),
  tp as (
    select user_id,
           sum(questions_answered)::bigint as total_questions,
           sum(correct_answers)::bigint as total_correct,
           round(avg(coalesce(mastery,0)))::integer as average_mastery,
           count(*) filter (where questions_answered > 0)::bigint as topics_explored
      from public.topic_progress
     group by user_id
  ),
  rewards as (
    select * from public.student_rewards
  )
  select p.id,
         coalesce(nullif(p.display_name,''), nullif(p.full_name,''), 'Student'),
         p.grade,p.learning_level,p.school_name,p.class_name,
         coalesce(p.xp,0),coalesce(p.current_streak,0),coalesce(p.best_streak,0),
         coalesce(tp.total_questions,0),coalesce(tp.total_correct,0),
         case when coalesce(tp.total_questions,0)=0 then 0 else round(tp.total_correct::numeric/tp.total_questions::numeric*100)::integer end,
         coalesce(tp.average_mastery,0),coalesce(tp.topics_explored,0),
         coalesce(r.missions_completed,0),coalesce(r.best_combo,0),coalesce(r.coins,0),coalesce(r.gems,0)
    from public.profiles p
    join allowed a on a.id=p.id
    left join tp on tp.user_id=p.id
    left join rewards r on r.user_id=p.id
   where p.id=coalesce(p_student_id,auth.uid())
      or p.id in (select id from allowed where id<>auth.uid());
$$;

revoke all on function public.get_learning_report(uuid) from public,anon;
grant execute on function public.get_learning_report(uuid) to authenticated;

-- Child-safe analytics for linked adults: topic mastery only, never answer text.
create or replace function public.get_linked_student_topics(p_student_id uuid)
returns table(topic_id text, topic_title text, questions_answered bigint, correct_answers bigint, mastery integer)
language sql security definer set search_path=public
as $$
  select t.id,t.title,coalesce(tp.questions_answered,0)::bigint,coalesce(tp.correct_answers,0)::bigint,coalesce(tp.mastery,0)::integer
    from public.student_relationships sr
    join public.learning_topics t on true
    left join public.topic_progress tp on tp.topic_id=t.id and tp.user_id=sr.student_id
   where sr.student_id=p_student_id and sr.related_user_id=auth.uid() and sr.status='active'
   order by t.sort_order;
$$;
revoke all on function public.get_linked_student_topics(uuid) from public,anon;
grant execute on function public.get_linked_student_topics(uuid) to authenticated;
