-- Admin / Teacher Class Management 3.0
-- Stage A: secure role, class, roster and teacher-assignment foundation.
-- Idempotent migration: safe to run more than once.

create table if not exists public.user_roles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  role text not null check (role in ('student','parent','guardian','teacher','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists user_roles_role_idx on public.user_roles(role);

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  class_code text not null unique,
  grade text,
  learning_level text,
  description text not null default '',
  created_by uuid not null references public.profiles(id) on delete restrict,
  status text not null default 'active' check (status in ('active','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists classes_created_by_idx on public.classes(created_by);
create index if not exists classes_status_idx on public.classes(status);

create table if not exists public.class_members (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'active' check (status in ('active','removed')),
  joined_at timestamptz not null default now(),
  unique(class_id, student_id)
);

create index if not exists class_members_class_idx on public.class_members(class_id,status);
create index if not exists class_members_student_idx on public.class_members(student_id,status);

create table if not exists public.class_teachers (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'teacher' check (role in ('teacher','lead_teacher')),
  status text not null default 'active' check (status in ('active','removed')),
  assigned_at timestamptz not null default now(),
  unique(class_id, teacher_id)
);

create index if not exists class_teachers_class_idx on public.class_teachers(class_id,status);
create index if not exists class_teachers_teacher_idx on public.class_teachers(teacher_id,status);

-- ------------------------------------------------------------
-- Security helpers
-- ------------------------------------------------------------

create or replace function public.has_role(p_role text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
      from public.user_roles ur
     where ur.user_id = auth.uid()
       and ur.role = p_role
  );
$$;

create or replace function public.is_class_teacher(p_class_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
      from public.class_teachers ct
     where ct.class_id = p_class_id
       and ct.teacher_id = auth.uid()
       and ct.status = 'active'
  );
$$;

create or replace function public.is_class_student(p_class_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
      from public.class_members cm
     where cm.class_id = p_class_id
       and cm.student_id = auth.uid()
       and cm.status = 'active'
  );
$$;

revoke all on function public.has_role(text) from public, anon;
grant execute on function public.has_role(text) to authenticated;
revoke all on function public.is_class_teacher(bigint) from public, anon;
grant execute on function public.is_class_teacher(bigint) to authenticated;
revoke all on function public.is_class_student(bigint) from public, anon;
grant execute on function public.is_class_student(bigint) to authenticated;

-- ------------------------------------------------------------
-- Row Level Security
-- ------------------------------------------------------------

alter table public.user_roles enable row level security;
alter table public.classes enable row level security;
alter table public.class_members enable row level security;
alter table public.class_teachers enable row level security;

drop policy if exists user_roles_self on public.user_roles;
create policy user_roles_self on public.user_roles
for select to authenticated
using (auth.uid() = user_id or public.has_role('admin'));

drop policy if exists classes_select on public.classes;
create policy classes_select on public.classes
for select to authenticated
using (
  public.has_role('admin')
  or created_by = auth.uid()
  or public.is_class_teacher(id)
  or public.is_class_student(id)
);

drop policy if exists classes_insert on public.classes;
create policy classes_insert on public.classes
for insert to authenticated
with check (
  public.has_role('admin')
  or (public.has_role('teacher') and created_by = auth.uid())
);

drop policy if exists classes_update on public.classes;
create policy classes_update on public.classes
for update to authenticated
using (
  public.has_role('admin')
  or (public.has_role('teacher') and created_by = auth.uid())
)
with check (
  public.has_role('admin')
  or (public.has_role('teacher') and created_by = auth.uid())
);

drop policy if exists classes_delete on public.classes;
create policy classes_delete on public.classes
for delete to authenticated
using (public.has_role('admin'));

drop policy if exists class_members_select on public.class_members;
create policy class_members_select on public.class_members
for select to authenticated
using (
  public.has_role('admin')
  or public.is_class_teacher(class_id)
  or public.is_class_student(class_id)
);

drop policy if exists class_members_insert on public.class_members;
create policy class_members_insert on public.class_members
for insert to authenticated
with check (
  public.has_role('admin')
  or public.is_class_teacher(class_id)
);

drop policy if exists class_members_update on public.class_members;
create policy class_members_update on public.class_members
for update to authenticated
using (
  public.has_role('admin')
  or public.is_class_teacher(class_id)
)
with check (
  public.has_role('admin')
  or public.is_class_teacher(class_id)
);

drop policy if exists class_members_delete on public.class_members;
create policy class_members_delete on public.class_members
for delete to authenticated
using (public.has_role('admin') or public.is_class_teacher(class_id));

drop policy if exists class_teachers_select on public.class_teachers;
create policy class_teachers_select on public.class_teachers
for select to authenticated
using (
  public.has_role('admin')
  or teacher_id = auth.uid()
  or public.is_class_teacher(class_id)
);

drop policy if exists class_teachers_insert on public.class_teachers;
create policy class_teachers_insert on public.class_teachers
for insert to authenticated
with check (public.has_role('admin'));

drop policy if exists class_teachers_update on public.class_teachers;
create policy class_teachers_update on public.class_teachers
for update to authenticated
using (public.has_role('admin'))
with check (public.has_role('admin'));

drop policy if exists class_teachers_delete on public.class_teachers;
create policy class_teachers_delete on public.class_teachers
for delete to authenticated
using (public.has_role('admin'));

-- ------------------------------------------------------------
-- Secure management RPCs
-- ------------------------------------------------------------

create or replace function public.create_learning_class(
  p_name text,
  p_class_code text,
  p_grade text default null,
  p_learning_level text default null,
  p_description text default ''
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id bigint;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  if not (public.has_role('admin') or public.has_role('teacher')) then
    raise exception 'Only admins and teachers can create classes';
  end if;

  insert into public.classes(name,class_code,grade,learning_level,description,created_by)
  values (
    trim(p_name),
    upper(trim(p_class_code)),
    nullif(trim(p_grade),''),
    nullif(trim(p_learning_level),''),
    coalesce(p_description,''),
    auth.uid()
  )
  returning id into new_id;

  -- A teacher who creates a class automatically becomes its lead teacher.
  if public.has_role('teacher') and not public.has_role('admin') then
    insert into public.class_teachers(class_id,teacher_id,role)
    values(new_id,auth.uid(),'lead_teacher')
    on conflict(class_id,teacher_id) do update set status='active',role='lead_teacher';
  end if;

  return new_id;
end;
$$;

create or replace function public.add_student_to_class(
  p_class_id bigint,
  p_student_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  if not (public.has_role('admin') or public.is_class_teacher(p_class_id)) then
    raise exception 'Not authorized to manage this class';
  end if;
  if not exists (select 1 from public.profiles where id=p_student_id) then
    raise exception 'Student profile not found';
  end if;

  insert into public.class_members(class_id,student_id,status)
  values(p_class_id,p_student_id,'active')
  on conflict(class_id,student_id) do update set status='active';
end;
$$;

create or replace function public.remove_student_from_class(
  p_class_id bigint,
  p_student_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  if not (public.has_role('admin') or public.is_class_teacher(p_class_id)) then
    raise exception 'Not authorized to manage this class';
  end if;

  update public.class_members
     set status='removed'
   where class_id=p_class_id and student_id=p_student_id;
end;
$$;

create or replace function public.assign_teacher_to_class(
  p_class_id bigint,
  p_teacher_id uuid,
  p_teacher_role text default 'teacher'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  if not public.has_role('admin') then
    raise exception 'Only admins can assign teachers';
  end if;
  if p_teacher_role not in ('teacher','lead_teacher') then
    raise exception 'Invalid teacher role';
  end if;
  if not exists (
    select 1 from public.user_roles
     where user_id=p_teacher_id and role='teacher'
  ) then
    raise exception 'User is not assigned the teacher role';
  end if;

  insert into public.class_teachers(class_id,teacher_id,role,status)
  values(p_class_id,p_teacher_id,p_teacher_role,'active')
  on conflict(class_id,teacher_id) do update
    set role=excluded.role,status='active';
end;
$$;

revoke all on function public.create_learning_class(text,text,text,text,text) from public, anon;
grant execute on function public.create_learning_class(text,text,text,text,text) to authenticated;
revoke all on function public.add_student_to_class(bigint,uuid) from public, anon;
grant execute on function public.add_student_to_class(bigint,uuid) to authenticated;
revoke all on function public.remove_student_from_class(bigint,uuid) from public, anon;
grant execute on function public.remove_student_from_class(bigint,uuid) to authenticated;
revoke all on function public.assign_teacher_to_class(bigint,uuid,text) from public, anon;
grant execute on function public.assign_teacher_to_class(bigint,uuid,text) to authenticated;

-- ------------------------------------------------------------
-- Verification
-- ------------------------------------------------------------

select 'user_roles' as object_name, to_regclass('public.user_roles') is not null as exists;
select 'classes' as object_name, to_regclass('public.classes') is not null as exists;
select 'class_members' as object_name, to_regclass('public.class_members') is not null as exists;
select 'class_teachers' as object_name, to_regclass('public.class_teachers') is not null as exists;
select 'has_role' as object_name, exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='has_role') as exists;
select 'create_learning_class' as object_name, exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='create_learning_class') as exists;
select 'add_student_to_class' as object_name, exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='add_student_to_class') as exists;
select 'assign_teacher_to_class' as object_name, exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='assign_teacher_to_class') as exists;

-- BOOTSTRAP NOTE:
-- Do not automatically assign an admin role here.
-- After confirming the migration works, an existing authenticated account
-- can be explicitly promoted by an authorized database administrator with:
-- insert into public.user_roles(user_id,role) values('<AUTH_USER_UUID>','admin')
-- on conflict(user_id) do update set role='admin',updated_at=now();
