-- ============================================================
-- FAHI VISSNUN Math Learning Platform
-- Migration 0026
-- Teacher Dashboard 4.2: intervention center
-- ============================================================

create table if not exists public.teacher_interventions (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  intervention_type text not null check (intervention_type in ('review','reinforce','extend')),
  topic_id text,
  notes text not null default '',
  status text not null default 'open' check (status in ('open','completed')),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists teacher_interventions_class_idx
  on public.teacher_interventions(class_id, status, created_at desc);

create index if not exists teacher_interventions_student_idx
  on public.teacher_interventions(student_id, status, created_at desc);

create index if not exists teacher_interventions_teacher_idx
  on public.teacher_interventions(teacher_id, status, created_at desc);

alter table public.teacher_interventions enable row level security;

drop policy if exists teacher_interventions_select on public.teacher_interventions;
create policy teacher_interventions_select
on public.teacher_interventions
for select to authenticated
using (
  public.has_role('admin')
  or teacher_id = auth.uid()
  or public.is_class_teacher(class_id)
);

drop policy if exists teacher_interventions_insert on public.teacher_interventions;
create policy teacher_interventions_insert
on public.teacher_interventions
for insert to authenticated
with check (
  public.has_role('admin')
  or (
    teacher_id = auth.uid()
    and public.is_class_teacher(class_id)
  )
);

drop policy if exists teacher_interventions_update on public.teacher_interventions;
create policy teacher_interventions_update
on public.teacher_interventions
for update to authenticated
using (
  public.has_role('admin')
  or teacher_id = auth.uid()
  or public.is_class_teacher(class_id)
)
with check (
  public.has_role('admin')
  or teacher_id = auth.uid()
  or public.is_class_teacher(class_id)
);

create or replace function public.create_teacher_intervention(
  p_class_id bigint,
  p_student_id uuid,
  p_intervention_type text,
  p_topic_id text default null,
  p_notes text default ''
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not (
    public.has_role('admin')
    or (
      public.has_role('teacher')
      and public.is_class_teacher(p_class_id)
    )
  ) then
    raise exception 'Not authorized to create an intervention for this class';
  end if;

  if p_intervention_type not in ('review','reinforce','extend') then
    raise exception 'Invalid intervention type';
  end if;

  if not exists (
    select 1
    from public.classes c
    where c.id = p_class_id
      and c.status = 'active'
  ) then
    raise exception 'Class not found or inactive';
  end if;

  if not exists (
    select 1
    from public.class_members cm
    where cm.class_id = p_class_id
      and cm.student_id = p_student_id
      and cm.status = 'active'
  ) then
    raise exception 'Student is not an active member of this class';
  end if;

  insert into public.teacher_interventions(
    class_id,
    student_id,
    teacher_id,
    intervention_type,
    topic_id,
    notes
  )
  values (
    p_class_id,
    p_student_id,
    auth.uid(),
    p_intervention_type,
    nullif(trim(p_topic_id), ''),
    coalesce(p_notes, '')
  )
  returning id into new_id;

  return new_id;
end;
$$;

create or replace function public.get_teacher_interventions(
  p_class_id bigint default null,
  p_student_id uuid default null,
  p_status text default 'open'
)
returns table(
  id bigint,
  class_id bigint,
  class_name text,
  student_id uuid,
  student_name text,
  teacher_id uuid,
  intervention_type text,
  topic_id text,
  notes text,
  status text,
  created_at timestamptz,
  completed_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    ti.id,
    ti.class_id,
    c.name as class_name,
    ti.student_id,
    coalesce(
      nullif(p.display_name, ''),
      nullif(p.full_name, ''),
      'Student'
    ) as student_name,
    ti.teacher_id,
    ti.intervention_type,
    ti.topic_id,
    ti.notes,
    ti.status,
    ti.created_at,
    ti.completed_at
  from public.teacher_interventions ti
  join public.classes c
    on c.id = ti.class_id
  join public.profiles p
    on p.id = ti.student_id
  where (
    public.has_role('admin')
    or ti.teacher_id = auth.uid()
    or public.is_class_teacher(ti.class_id)
  )
  and (p_class_id is null or ti.class_id = p_class_id)
  and (p_student_id is null or ti.student_id = p_student_id)
  and (p_status is null or ti.status = p_status)
  order by ti.created_at desc;
$$;

create or replace function public.complete_teacher_intervention(
  p_intervention_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not exists (
    select 1
    from public.teacher_interventions ti
    where ti.id = p_intervention_id
      and (
        public.has_role('admin')
        or ti.teacher_id = auth.uid()
        or public.is_class_teacher(ti.class_id)
      )
  ) then
    raise exception 'Intervention not found or not authorized';
  end if;

  update public.teacher_interventions
     set status = 'completed',
         completed_at = coalesce(completed_at, now())
   where id = p_intervention_id;
end;
$$;

revoke all on function public.create_teacher_intervention(bigint,uuid,text,text,text)
from public, anon;
grant execute on function public.create_teacher_intervention(bigint,uuid,text,text,text)
to authenticated;

revoke all on function public.get_teacher_interventions(bigint,uuid,text)
from public, anon;
grant execute on function public.get_teacher_interventions(bigint,uuid,text)
to authenticated;

revoke all on function public.complete_teacher_intervention(bigint)
from public, anon;
grant execute on function public.complete_teacher_intervention(bigint)
to authenticated;

select to_regprocedure(
  'public.create_teacher_intervention(bigint,uuid,text,text,text)'
) as create_teacher_intervention;

select to_regprocedure(
  'public.get_teacher_interventions(bigint,uuid,text)'
) as get_teacher_interventions;

select to_regprocedure(
  'public.complete_teacher_intervention(bigint)'
) as complete_teacher_intervention;

-- ============================================================
-- END OF MIGRATION 0026
-- ============================================================
