-- ============================================================
-- FAHI VISSNUN Math Learning Platform
-- Migration 0026
-- Teacher Dashboard 4.2: intervention center
-- ============================================================

create table if not exists public.teacher_interventions (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  created_by uuid not null references public.profiles(id) on delete restrict,
  action text not null check (action in ('review','reinforce','extend')),
  topic_id text,
  note text not null default '',
  status text not null default 'open' check (status in ('open','completed')),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists teacher_interventions_class_idx
  on public.teacher_interventions(class_id, status, created_at desc);

create index if not exists teacher_interventions_student_idx
  on public.teacher_interventions(student_id, status, created_at desc);

alter table public.teacher_interventions enable row level security;

drop policy if exists teacher_interventions_select on public.teacher_interventions;
create policy teacher_interventions_select
on public.teacher_interventions
for select to authenticated
using (
  public.has_role('admin')
  or public.is_class_teacher(class_id)
);

drop policy if exists teacher_interventions_insert on public.teacher_interventions;
create policy teacher_interventions_insert
on public.teacher_interventions
for insert to authenticated
with check (
  (public.has_role('admin') or public.is_class_teacher(class_id))
  and created_by = auth.uid()
);

drop policy if exists teacher_interventions_update on public.teacher_interventions;
create policy teacher_interventions_update
on public.teacher_interventions
for update to authenticated
using (
  public.has_role('admin')
  or public.is_class_teacher(class_id)
)
with check (
  public.has_role('admin')
  or public.is_class_teacher(class_id)
);

create or replace function public.create_teacher_intervention(
  p_class_id bigint,
  p_student_id uuid,
  p_action text,
  p_topic_id text default null,
  p_note text default ''
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not (public.has_role('admin') or public.is_class_teacher(p_class_id)) then
    raise exception 'Not authorized to manage interventions for this class';
  end if;

  if p_action not in ('review','reinforce','extend') then
    raise exception 'Invalid intervention action';
  end if;

  if not exists (
    select 1
    from public.class_members cm
    where cm.class_id = p_class_id
      and cm.student_id = p_student_id
      and cm.status = 'active'
  ) then
    raise exception 'Student is not actively enrolled in this class';
  end if;

  insert into public.teacher_interventions(
    class_id,
    student_id,
    created_by,
    action,
    topic_id,
    note
  )
  values(
    p_class_id,
    p_student_id,
    auth.uid(),
    p_action,
    nullif(trim(p_topic_id), ''),
    coalesce(trim(p_note), '')
  )
  returning id into new_id;

  return new_id;
end;
$$;

create or replace function public.get_teacher_interventions(
  p_class_id bigint default null,
  p_student_id uuid default null,
  p_status text default 'open'
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', ti.id,
        'class_id', ti.class_id,
        'student_id', ti.student_id,
        'student_name', coalesce(
          nullif(p.display_name, ''),
          nullif(p.full_name, ''),
          'Student'
        ),
        'action', ti.action,
        'topic_id', ti.topic_id,
        'note', ti.note,
        'status', ti.status,
        'created_at', ti.created_at,
        'completed_at', ti.completed_at
      )
      order by ti.created_at desc
    ),
    '[]'::jsonb
  )
  from public.teacher_interventions ti
  join public.profiles p on p.id = ti.student_id
  where (
    public.has_role('admin')
    or public.is_class_teacher(ti.class_id)
  )
  and (p_class_id is null or ti.class_id = p_class_id)
  and (p_student_id is null or ti.student_id = p_student_id)
  and (p_status is null or ti.status = p_status);
$$;

create or replace function public.complete_teacher_intervention(
  p_intervention_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  update public.teacher_interventions ti
  set status = 'completed',
      completed_at = now()
  where ti.id = p_intervention_id
    and (
      public.has_role('admin')
      or public.is_class_teacher(ti.class_id)
    );

  if not found then
    raise exception 'Intervention not found or not authorized';
  end if;
end;
$$;

revoke all on function public.create_teacher_intervention(bigint,uuid,text,text,text) from public, anon;
grant execute on function public.create_teacher_intervention(bigint,uuid,text,text,text) to authenticated;

revoke all on function public.get_teacher_interventions(bigint,uuid,text) from public, anon;
grant execute on function public.get_teacher_interventions(bigint,uuid,text) to authenticated;

revoke all on function public.complete_teacher_intervention(bigint) from public, anon;
grant execute on function public.complete_teacher_intervention(bigint) to authenticated;

select to_regprocedure(
  'public.create_teacher_intervention(bigint,uuid,text,text,text)'
) as create_teacher_intervention;

select to_regprocedure(
  'public.get_teacher_interventions(bigint,uuid,text)'
) as get_teacher_interventions;

select to_regprocedure(
  'public.complete_teacher_intervention(bigint)'
) as complete_teacher_intervention;

-- ============================================================
-- END OF MIGRATION 0026
-- ============================================================
