-- ============================================================
-- FAHI VISSNUN Math Learning Platform
-- Migration 0028
-- Teacher Dashboard 4.4: action history & follow-up center
-- ============================================================

alter table public.teacher_interventions
  add column if not exists follow_up_status text not null default 'not_required'
    check (follow_up_status in ('not_required','pending','in_progress','completed')),
  add column if not exists follow_up_due_at timestamptz,
  add column if not exists follow_up_completed_at timestamptz,
  add column if not exists follow_up_note text not null default '';

create index if not exists teacher_interventions_follow_up_idx
  on public.teacher_interventions(follow_up_status, follow_up_due_at);

create table if not exists public.teacher_intervention_events (
  id bigint generated by default as identity primary key,
  intervention_id bigint not null references public.teacher_interventions(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete restrict,
  event_type text not null check (event_type in ('created','completed','reopened','follow_up_updated')),
  event_note text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists teacher_intervention_events_intervention_idx
  on public.teacher_intervention_events(intervention_id, created_at desc);

create index if not exists teacher_intervention_events_actor_idx
  on public.teacher_intervention_events(actor_id, created_at desc);

alter table public.teacher_intervention_events enable row level security;

drop policy if exists teacher_intervention_events_select on public.teacher_intervention_events;
create policy teacher_intervention_events_select
on public.teacher_intervention_events
for select to authenticated
using (
  public.has_role('admin')
  or exists (
    select 1
    from public.teacher_interventions ti
    where ti.id = intervention_id
      and public.is_class_teacher(ti.class_id)
  )
);

drop policy if exists teacher_intervention_events_insert on public.teacher_intervention_events;
create policy teacher_intervention_events_insert
on public.teacher_intervention_events
for insert to authenticated
with check (actor_id = auth.uid());

-- The two historical 4.2 migration variants used different column names.
-- Reading through to_jsonb keeps this migration compatible with either one.
create or replace function public.log_teacher_intervention_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid;
  event_name text;
  note_value text;
  action_value text;
  status_value text;
begin
  actor := auth.uid();
  if actor is null then
    actor := coalesce((to_jsonb(new)->>'created_by')::uuid, (to_jsonb(new)->>'teacher_id')::uuid);
  end if;

  if tg_op = 'INSERT' then
    event_name := 'created';
    note_value := coalesce(to_jsonb(new)->>'note', to_jsonb(new)->>'notes', '');
    action_value := coalesce(to_jsonb(new)->>'action', to_jsonb(new)->>'intervention_type', '');
    status_value := coalesce(to_jsonb(new)->>'status', 'open');
  elsif tg_op = 'UPDATE' then
    if coalesce(to_jsonb(old)->>'status', '') <> coalesce(to_jsonb(new)->>'status', '') then
      event_name := case when coalesce(to_jsonb(new)->>'status', '') = 'completed' then 'completed' else 'reopened' end;
      note_value := coalesce(to_jsonb(new)->>'note', to_jsonb(new)->>'notes', '');
      action_value := coalesce(to_jsonb(new)->>'action', to_jsonb(new)->>'intervention_type', '');
      status_value := coalesce(to_jsonb(new)->>'status', '');
    elsif coalesce(to_jsonb(old)->>'follow_up_status', '') <> coalesce(to_jsonb(new)->>'follow_up_status', '')
       or coalesce(to_jsonb(old)->>'follow_up_note', '') <> coalesce(to_jsonb(new)->>'follow_up_note', '')
       or coalesce(to_jsonb(old)->>'follow_up_due_at', '') <> coalesce(to_jsonb(new)->>'follow_up_due_at', '') then
      event_name := 'follow_up_updated';
      note_value := coalesce(to_jsonb(new)->>'follow_up_note', '');
      action_value := coalesce(to_jsonb(new)->>'action', to_jsonb(new)->>'intervention_type', '');
      status_value := coalesce(to_jsonb(new)->>'status', '');
    else
      return new;
    end if;
  else
    return new;
  end if;

  insert into public.teacher_intervention_events(intervention_id, actor_id, event_type, event_note, metadata)
  values (
    new.id,
    actor,
    event_name,
    note_value,
    jsonb_build_object(
      'action', action_value,
      'status', status_value,
      'follow_up_status', coalesce(to_jsonb(new)->>'follow_up_status', 'not_required'),
      'follow_up_due_at', to_jsonb(new)->>'follow_up_due_at'
    )
  );

  return new;
end;
$$;

drop trigger if exists teacher_intervention_audit_trigger on public.teacher_interventions;
create trigger teacher_intervention_audit_trigger
after insert or update on public.teacher_interventions
for each row execute function public.log_teacher_intervention_event();

create or replace function public.get_teacher_action_history(
  p_class_id bigint default null,
  p_student_id uuid default null,
  p_status text default null,
  p_topic text default null,
  p_limit integer default 100
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select coalesce(jsonb_agg(row_data order by created_at desc), '[]'::jsonb)
    into result
  from (
    select
      ti.created_at,
      jsonb_build_object(
        'id', ti.id,
        'class_id', ti.class_id,
        'class_name', c.name,
        'student_id', ti.student_id,
        'student_name', coalesce(nullif(p.display_name, ''), nullif(p.full_name, ''), 'Student'),
        'action', coalesce(to_jsonb(ti)->>'action', to_jsonb(ti)->>'intervention_type', 'review'),
        'topic_id', to_jsonb(ti)->>'topic_id',
        'note', coalesce(to_jsonb(ti)->>'note', to_jsonb(ti)->>'notes', ''),
        'status', ti.status,
        'created_at', ti.created_at,
        'completed_at', ti.completed_at,
        'follow_up_status', coalesce(ti.follow_up_status, 'not_required'),
        'follow_up_due_at', ti.follow_up_due_at,
        'follow_up_completed_at', ti.follow_up_completed_at,
        'follow_up_note', coalesce(ti.follow_up_note, ''),
        'events', coalesce((
          select jsonb_agg(jsonb_build_object(
            'id', e.id,
            'event_type', e.event_type,
            'event_note', e.event_note,
            'actor_id', e.actor_id,
            'created_at', e.created_at,
            'metadata', e.metadata
          ) order by e.created_at desc)
          from public.teacher_intervention_events e
          where e.intervention_id = ti.id
        ), '[]'::jsonb),
        'follow_up_activity_7d', (
          select count(*)::integer
          from public.question_attempts qa
          where qa.user_id = ti.student_id
            and ti.completed_at is not null
            and qa.created_at > ti.completed_at
            and qa.created_at <= ti.completed_at + interval '7 days'
        )
      ) as row_data
    from public.teacher_interventions ti
    join public.classes c on c.id = ti.class_id
    join public.profiles p on p.id = ti.student_id
    where (
      public.has_role('admin')
      or public.is_class_teacher(ti.class_id)
      or coalesce((to_jsonb(ti)->>'created_by')::uuid, (to_jsonb(ti)->>'teacher_id')::uuid) = auth.uid()
    )
      and (p_class_id is null or ti.class_id = p_class_id)
      and (p_student_id is null or ti.student_id = p_student_id)
      and (p_status is null or ti.status = p_status)
      and (p_topic is null or lower(coalesce(to_jsonb(ti)->>'topic_id', '')) like '%' || lower(trim(p_topic)) || '%')
    order by ti.created_at desc
    limit greatest(1, least(coalesce(p_limit, 100), 500))
  ) q;

  return result;
end;
$$;

create or replace function public.update_teacher_follow_up(
  p_intervention_id bigint,
  p_status text,
  p_due_at timestamptz default null,
  p_note text default ''
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_class bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;
  if p_status not in ('not_required','pending','in_progress','completed') then
    raise exception 'Invalid follow-up status';
  end if;

  select class_id into target_class
  from public.teacher_interventions
  where id = p_intervention_id;

  if target_class is null or not (
    public.has_role('admin')
    or public.is_class_teacher(target_class)
  ) then
    raise exception 'Intervention not found or not authorized';
  end if;

  update public.teacher_interventions
     set follow_up_status = p_status,
         follow_up_due_at = case when p_status in ('pending','in_progress') then p_due_at else null end,
         follow_up_completed_at = case when p_status = 'completed' then coalesce(follow_up_completed_at, now()) else null end,
         follow_up_note = coalesce(trim(p_note), '')
   where id = p_intervention_id;
end;
$$;

revoke all on function public.get_teacher_action_history(bigint,uuid,text,text,integer) from public, anon;
grant execute on function public.get_teacher_action_history(bigint,uuid,text,text,integer) to authenticated;

revoke all on function public.update_teacher_follow_up(bigint,text,timestamptz,text) from public, anon;
grant execute on function public.update_teacher_follow_up(bigint,text,timestamptz,text) to authenticated;

select to_regprocedure('public.get_teacher_action_history(bigint,uuid,text,text,integer)') as get_teacher_action_history;
select to_regprocedure('public.update_teacher_follow_up(bigint,text,timestamptz,text)') as update_teacher_follow_up;

-- ============================================================
-- END OF MIGRATION 0028
-- ============================================================
