-- Visual Math Lab question bank V2
-- Adds varied visual questions across counting, comparison, place value,
-- patterns, geometry, fractions and multiplication.

insert into public.learning_questions (
  id, topic_id, prompt, options, answer, explanation, sort_order,
  difficulty, skill, question_type, interaction_config, hint, animation, media_url
) values
('vml-013','visual-math','How many counters are shown altogether?','["10","11","12","13"]','12','There are 7 counters and 5 counters. 7 + 5 = 12.',113,'easy','Addition','visual_question','{"visual":{"kind":"counters_addition","groups":[7,5]}}','Count both groups and add them.','question-enter',null),
('vml-014','visual-math','How many more counters are in the second group?','["1","2","3","4"]','2','The second group has 9 and the first has 7. 9 - 7 = 2.',114,'easy','Subtraction','visual_question','{"visual":{"kind":"counters_addition","groups":[7,9]}}','Compare the two groups.','question-enter',null),
('vml-015','visual-math','Which number is represented by 2 tens and 6 ones?','["16","20","26","62"]','26','Two tens are 20 and six ones are 6. The number is 26.',115,'easy','Place value','visual_question','{"visual":{"kind":"tens_ones","tens":2,"ones":6}}','Two tens make 20.','question-enter',null),
('vml-016','visual-math','Which number is represented by 8 tens and 3 ones?','["38","83","80","88"]','83','Eight tens are 80 and three ones are 3, making 83.',116,'easy','Place value','visual_question','{"visual":{"kind":"tens_ones","tens":8,"ones":3}}','Eight tens make 80.','question-enter',null),
('vml-017','visual-math','What comes next?','["18","20","21","22"]','21','The pattern increases by 3: 9, 12, 15, 18, 21.',117,'easy','Patterns','visual_question','{"visual":{"kind":"pattern","values":[9,12,15,18]}}','Look at the amount added each time.','question-enter',null),
('vml-018','visual-math','What comes next?','["25","28","30","32"]','30','The pattern increases by 5: 10, 15, 20, 25, 30.',118,'easy','Patterns','visual_question','{"visual":{"kind":"pattern","values":[10,15,20,25]}}','The same number is added each time.','question-enter',null),
('vml-019','visual-math','Which number is greatest?','["19","15","21","17"]','21','21 is greater than all the other numbers shown.',119,'easy','Comparison','visual_question','{"visual":{"kind":"number_cards","numbers":[19,15,21,17]}}','Find the largest number.','question-enter',null),
('vml-020','visual-math','Which number is smallest?','["23","18","25","20"]','18','18 is the smallest number shown.',120,'easy','Comparison','visual_question','{"visual":{"kind":"number_cards","numbers":[23,18,25,20]}}','Find the smallest number.','question-enter',null),
('vml-021','visual-math','How many counters are there in all three groups?','["13","14","15","16"]','15','There are 3 + 7 + 5 counters. That equals 15.',121,'medium','Addition','visual_question','{"visual":{"kind":"counters_addition","groups":[3,7,5]}}','Add all three groups.','question-enter',null),
('vml-022','visual-math','How many more are in the largest group than the smallest group?','["3","4","5","6"]','5','The largest group has 10 and the smallest has 5. 10 - 5 = 5.',122,'medium','Subtraction','visual_question','{"visual":{"kind":"counters_addition","groups":[5,10]}}','Subtract the smaller group from the larger group.','question-enter',null),
('vml-023','visual-math','What number is shown by 4 tens and 9 ones?','["49","94","40","59"]','49','Four tens make 40 and nine ones make 9. Together they make 49.',123,'medium','Place value','visual_question','{"visual":{"kind":"tens_ones","tens":4,"ones":9}}','4 tens = 40.','question-enter',null),
('vml-024','visual-math','What number is shown by 6 tens and 5 ones?','["56","65","60","605"]','65','Six tens are 60 and five ones are 5, so the number is 65.',124,'medium','Place value','visual_question','{"visual":{"kind":"tens_ones","tens":6,"ones":5}}','Put the tens before the ones.','question-enter',null),
('vml-025','visual-math','Which shape has 3 sides?','["Square","Circle","Triangle","Rectangle"]','Triangle','A triangle has three sides.',125,'easy','Geometry','visual_question','{"visual":{"kind":"shape","shape":"triangle"}}','Count the sides.','question-enter',null),
('vml-026','visual-math','Which shape has no corners?','["Triangle","Square","Circle","Rectangle"]','Circle','A circle has no corners.',126,'easy','Geometry','visual_question','{"visual":{"kind":"shape","shape":"circle"}}','Look for the shape without corners.','question-enter',null),
('vml-027','visual-math','Which shape has 4 equal sides?','["Rectangle","Triangle","Square","Circle"]','Square','All four sides of a square are equal.',127,'easy','Geometry','visual_question','{"visual":{"kind":"shape","shape":"square"}}','Check the side lengths.','question-enter',null),
('vml-028','visual-math','What comes next?','["24","26","27","28"]','27','The pattern increases by 3: 12, 15, 18, 21, 24, 27.',128,'medium','Patterns','visual_question','{"visual":{"kind":"pattern","values":[12,15,18,21,24]}}','Add the same amount each time.','question-enter',null),
('vml-029','visual-math','Which number is closest to 20?','["12","18","25","30"]','18','18 is 2 away from 20, closer than the other choices.',129,'medium','Number comparison','visual_question','{"visual":{"kind":"number_cards","numbers":[12,18,25,30]}}','Think about how far each number is from 20.','question-enter',null),
('vml-030','visual-math','Which number is closest to 50?','["42","47","55","61"]','47','47 is 3 away from 50, closer than the other choices.',130,'medium','Number comparison','visual_question','{"visual":{"kind":"number_cards","numbers":[42,47,55,61]}}','Compare the distance from 50.','question-enter',null),
('vml-031','visual-math','How many counters are there altogether?','["16","17","18","19"]','18','There are 9 + 9 counters, which equals 18.',131,'medium','Addition','visual_question','{"visual":{"kind":"counters_addition","groups":[9,9]}}','Add the two equal groups.','question-enter',null),
('vml-032','visual-math','What is the difference between the two groups?','["4","5","6","7"]','6','There are 12 and 6 counters. 12 - 6 = 6.',132,'medium','Subtraction','visual_question','{"visual":{"kind":"counters_addition","groups":[6,12]}}','Find how many more the larger group has.','question-enter',null),
('vml-033','visual-math','Which number is shown by 9 tens and 4 ones?','["49","94","90","904"]','94','Nine tens are 90 and four ones are 4. The number is 94.',133,'medium','Place value','visual_question','{"visual":{"kind":"tens_ones","tens":9,"ones":4}}','9 tens = 90.','question-enter',null),
('vml-034','visual-math','Which number is greater?','["37","73","57","67"]','73','73 has the greatest value.',134,'medium','Comparison','visual_question','{"visual":{"kind":"number_cards","numbers":[37,73,57,67]}}','Compare the tens first.','question-enter',null),
('vml-035','visual-math','Which number is smallest?','["41","14","31","24"]','14','14 is the smallest number shown.',135,'medium','Comparison','visual_question','{"visual":{"kind":"number_cards","numbers":[41,14,31,24]}}','Compare the tens digits.','question-enter',null),
('vml-036','visual-math','What comes next?','["30","32","35","36"]','35','The pattern increases by 5: 15, 20, 25, 30, 35.',136,'medium','Patterns','visual_question','{"visual":{"kind":"pattern","values":[15,20,25,30]}}','Count forward by 5.','question-enter',null),
('vml-037','visual-math','How many counters are in all four groups?','["18","19","20","21"]','20','There are 5 + 4 + 6 + 5 counters. That equals 20.',137,'hard','Addition','visual_question','{"visual":{"kind":"counters_addition","groups":[5,4,6,5]}}','Add each group carefully.','question-enter',null),
('vml-038','visual-math','How many more counters are in the larger group?','["6","7","8","9"]','8','The groups have 7 and 15 counters. 15 - 7 = 8.',138,'hard','Subtraction','visual_question','{"visual":{"kind":"counters_addition","groups":[7,15]}}','Find the difference.','question-enter',null),
('vml-039','visual-math','Which number is greatest?','["68","86","78","88"]','88','88 is the greatest number shown.',139,'hard','Comparison','visual_question','{"visual":{"kind":"number_cards","numbers":[68,86,78,88]}}','Compare the tens and then the ones.','question-enter',null),
('vml-040','visual-math','What number is shown by 9 tens and 8 ones?','["89","98","92","908"]','98','Nine tens make 90 and eight ones make 8. Together they make 98.',140,'hard','Place value','visual_question','{"visual":{"kind":"tens_ones","tens":9,"ones":8}}','9 tens = 90.','question-enter',null)
on conflict (id) do update set
 topic_id=excluded.topic_id,prompt=excluded.prompt,options=excluded.options,answer=excluded.answer,
 explanation=excluded.explanation,sort_order=excluded.sort_order,difficulty=excluded.difficulty,
 skill=excluded.skill,question_type=excluded.question_type,interaction_config=excluded.interaction_config,
 hint=excluded.hint,animation=excluded.animation,media_url=excluded.media_url;
