"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BookOpen, CheckCircle2, GraduationCap, Plus, RefreshCw, ShieldCheck, Trash2, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type ClassRow = { id:number; name:string; class_code:string; grade:string|null; learning_level:string|null; description:string; status:string; created_by:string|null };
type Profile = { id:string; full_name:string|null; display_name:string|null; grade:string|null; learning_level:string|null };
type RoleRow = { user_id:string; role:string };
type Member = { id:number; student_id:string; status:string; profile?:Profile };
type Teacher = { id:number; teacher_id:string; role:string; status:string; profile?:Profile };

export default function AdminClassesPage(){
 const supabase=createClient();
 const[classes,setClasses]=useState<ClassRow[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[teachers,setTeachers]=useState<Profile[]>([]),[members,setMembers]=useState<Member[]>([]),[assignedTeachers,setAssignedTeachers]=useState<Teacher[]>([]);
 const[selectedClass,setSelectedClass]=useState<ClassRow|null>(null),[status,setStatus]=useState("Loading class management…"),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const[name,setName]=useState(""),[code,setCode]=useState(""),[grade,setGrade]=useState(""),[level,setLevel]=useState(""),[description,setDescription]=useState("");
 const[selectedStudent,setSelectedStudent]=useState(""),[selectedTeacher,setSelectedTeacher]=useState(""),[teacherRole,setTeacherRole]=useState("teacher");

 async function load(){
  if(!supabase){setStatus("Supabase is not configured yet.");return;}
  setStatus("Loading class management…");
  const{data:{user}}=await supabase.auth.getUser();
  if(!user){window.location.href="/login";return;}
  const{data:roleRows,error:roleError}=await supabase.from("user_roles").select("role").eq("user_id",user.id).eq("role","admin").maybeSingle();
  if(roleError||!roleRows){setStatus("Admin access is required. Your account must have the admin role.");return;}
  const[{data:cs,error:ce},{data:ps},{data:rs}]=await Promise.all([
   supabase.from("classes").select("id,name,class_code,grade,learning_level,description,status,created_by").order("created_at",{ascending:false}),
   supabase.from("profiles").select("id,full_name,display_name,grade,learning_level").order("full_name"),
   supabase.from("user_roles").select("user_id,role").eq("role","teacher")
  ]);
  if(ce){setStatus(ce.message);return;}
  const allProfiles=(ps??[]) as Profile[]; const roleIds=new Set((rs??[] as RoleRow[]).map(r=>r.user_id));
  setClasses((cs??[]) as ClassRow[]);setProfiles(allProfiles);setTeachers(allProfiles.filter(p=>roleIds.has(p.id)));setStatus("");
 }
 useEffect(()=>{load()},[]);
 async function selectClass(c:ClassRow){setSelectedClass(c);setNotice("");if(!supabase)return;const[{data:ms},{data:ts}]=await Promise.all([supabase.from("class_members").select("id,student_id,status").eq("class_id",c.id).eq("status","active"),supabase.from("class_teachers").select("id,teacher_id,role,status").eq("class_id",c.id).eq("status","active")]);setMembers(((ms??[]) as Member[]).map(m=>({...m,profile:profiles.find(p=>p.id===m.student_id)})));setAssignedTeachers(((ts??[]) as Teacher[]).map(t=>({...t,profile:profiles.find(p=>p.id===t.teacher_id)})));}
 async function createClass(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setNotice("");const{data,error}=await supabase.rpc("create_learning_class",{p_name:name,p_class_code:code,p_grade:grade||null,p_learning_level:level||null,p_description:description});setBusy(false);if(error){setNotice(error.message);return;}setName("");setCode("");setGrade("");setLevel("");setDescription("");setNotice("Class created successfully.");await load();if(data){const created=classes.find(c=>c.id===Number(data));if(created)setSelectedClass(created);}}
 async function addStudent(){if(!supabase||!selectedClass||!selectedStudent)return;setBusy(true);const{error}=await supabase.rpc("add_student_to_class",{p_class_id:selectedClass.id,p_student_id:selectedStudent});setBusy(false);setNotice(error?error.message:"Student added to class.");if(!error){setSelectedStudent("");await selectClass(selectedClass);}}
 async function removeStudent(id:string){if(!supabase||!selectedClass)return;setBusy(true);const{error}=await supabase.rpc("remove_student_from_class",{p_class_id:selectedClass.id,p_student_id:id});setBusy(false);setNotice(error?error.message:"Student removed from class.");if(!error)await selectClass(selectedClass);}
 async function assignTeacher(){if(!supabase||!selectedClass||!selectedTeacher)return;setBusy(true);const{error}=await supabase.rpc("assign_teacher_to_class",{p_class_id:selectedClass.id,p_teacher_id:selectedTeacher,p_teacher_role:teacherRole});setBusy(false);setNotice(error?error.message:"Teacher assigned successfully.");if(!error){setSelectedTeacher("");await selectClass(selectedClass);}}
 if(status)return <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-violet-50 p-6"><div className="mx-auto mt-24 max-w-xl rounded-[2rem] bg-white p-10 text-center shadow-xl ring-1 ring-slate-100"><ShieldCheck className="mx-auto text-violet-600" size={48}/><h1 className="mt-4 text-2xl font-black text-[#071b3a]">Admin Class Management</h1><p className="mt-3 text-sm leading-6 text-slate-500">{status}</p><Link href="/dashboard" className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-violet-600 px-5 py-3 font-black text-white"><ArrowLeft size={17}/> Dashboard</Link></div></main>;
 return <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-violet-50 p-5 pb-28 sm:p-8"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-4"><Link href="/dashboard" className="inline-flex items-center gap-2 font-bold text-slate-600"><ArrowLeft size={18}/> Dashboard</Link><div className="flex items-center gap-2"><span className="rounded-full bg-violet-50 px-4 py-2 text-sm font-black text-violet-700">Admin Console 3.0</span><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold text-slate-600"><RefreshCw size={16}/> Refresh</button></div></header>
 <section className="mt-7 rounded-[2rem] bg-gradient-to-br from-[#17234f] via-violet-700 to-blue-600 p-7 text-white shadow-2xl sm:p-9"><div className="flex flex-wrap items-end justify-between gap-6"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-black uppercase tracking-wider"><ShieldCheck size={14}/> Secure administrator view</div><h1 className="mt-4 text-4xl font-black">Class Management</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-indigo-100">Create learning classes, manage student rosters and assign approved teachers. Management actions use the protected Supabase RPC layer.</p></div><div className="grid grid-cols-2 gap-3"><Stat icon={<BookOpen/>} value={classes.length} label="Classes"/><Stat icon={<Users/>} value={profiles.length} label="Profiles"/></div></div></section>
 {notice&&<div className="mt-5 rounded-2xl border border-violet-100 bg-violet-50 px-5 py-4 text-sm font-bold text-violet-800">{notice}</div>}
 <section className="mt-6 grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100 sm:p-7"><div className="flex items-center gap-3"><Plus className="text-violet-600"/><div><p className="text-xs font-black uppercase tracking-wider text-violet-600">New class</p><h2 className="text-2xl font-black text-[#071b3a]">Create learning class</h2></div></div><form onSubmit={createClass} className="mt-6 space-y-4"><Field label="Class name"><input value={name} onChange={e=>setName(e.target.value)} required placeholder="e.g. Grade 5 Maths"/></Field><Field label="Class code"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} required placeholder="e.g. G5-MATH-01"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Grade"><input value={grade} onChange={e=>setGrade(e.target.value)} placeholder="Grade 5"/></Field><Field label="Learning level"><input value={level} onChange={e=>setLevel(e.target.value)} placeholder="Foundation"/></Field></div><Field label="Description"><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} placeholder="Optional class description"/></Field><button disabled={busy} className="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-violet-600 px-5 py-3.5 font-black text-white shadow-lg shadow-violet-200 disabled:opacity-50"><Plus size={18}/> {busy?"Working…":"Create class"}</button></form></div>
 <div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100 sm:p-7"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-violet-600">Learning classes</p><h2 className="text-2xl font-black text-[#071b3a]">Active class directory</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-600">{classes.filter(c=>c.status==='active').length} active</span></div><div className="mt-5 space-y-3">{classes.length===0?<Empty text="No classes created yet."/>:classes.map(c=><button key={c.id} onClick={()=>selectClass(c)} className={`w-full rounded-2xl border p-4 text-left transition ${selectedClass?.id===c.id?"border-violet-300 bg-violet-50":"border-slate-100 bg-slate-50 hover:border-violet-200 hover:bg-violet-50/50"}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-black text-[#071b3a]">{c.name}</p><p className="mt-1 text-xs font-bold text-slate-500">{c.class_code} · {c.grade||"Grade not set"} · {c.learning_level||"Level not set"}</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-slate-600">{c.status}</span></div></button>)}</div></div></section>
 {selectedClass&&<section className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title="Student roster" icon={<GraduationCap className="text-cyan-600"/>} subtitle={`${selectedClass.name} · ${members.length} active students`}><div className="flex flex-col gap-3 sm:flex-row"><select value={selectedStudent} onChange={e=>setSelectedStudent(e.target.value)} className="min-w-0 flex-1 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold"><option value="">Select a student profile</option>{profiles.filter(p=>!members.some(m=>m.student_id===p.id)).map(p=><option key={p.id} value={p.id}>{p.display_name||p.full_name||p.id} · {p.grade||"No grade"}</option>)}</select><button onClick={addStudent} disabled={!selectedStudent||busy} className="rounded-2xl bg-cyan-600 px-5 py-3 font-black text-white disabled:opacity-50">Add student</button></div><div className="mt-5 space-y-2">{members.length===0?<Empty text="No active students in this class."/>:members.map(m=><div key={m.id} className="flex items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4"><div><p className="font-black text-[#071b3a]">{m.profile?.display_name||m.profile?.full_name||"Student"}</p><p className="text-xs text-slate-500">{m.profile?.grade||"Grade not set"} · {m.profile?.learning_level||"Level not set"}</p></div><button onClick={()=>removeStudent(m.student_id)} className="inline-flex items-center gap-1 rounded-xl px-3 py-2 text-xs font-black text-rose-600 hover:bg-rose-50"><Trash2 size={14}/> Remove</button></div>)}</div></Panel>
 <Panel title="Teacher assignment" icon={<Users className="text-violet-600"/>} subtitle={`${selectedClass.name} · ${assignedTeachers.length} active teachers`}><div className="grid gap-3 sm:grid-cols-[1fr_auto_auto]"><select value={selectedTeacher} onChange={e=>setSelectedTeacher(e.target.value)} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold"><option value="">Select approved teacher</option>{teachers.filter(t=>!assignedTeachers.some(a=>a.teacher_id===t.id)).map(t=><option key={t.id} value={t.id}>{t.display_name||t.full_name||t.id}</option>)}</select><select value={teacherRole} onChange={e=>setTeacherRole(e.target.value)} className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold"><option value="teacher">Teacher</option><option value="lead_teacher">Lead teacher</option></select><button onClick={assignTeacher} disabled={!selectedTeacher||busy} className="rounded-2xl bg-violet-600 px-5 py-3 font-black text-white disabled:opacity-50">Assign</button></div><div className="mt-5 space-y-2">{assignedTeachers.length===0?<Empty text="No active teachers assigned."/>:assignedTeachers.map(t=><div key={t.id} className="flex items-center justify-between rounded-2xl bg-violet-50 p-4"><div><p className="font-black text-[#071b3a]">{t.profile?.display_name||t.profile?.full_name||"Teacher"}</p><p className="text-xs font-bold uppercase tracking-wide text-violet-600">{t.role.replace("_"," ")}</p></div><CheckCircle2 className="text-violet-600" size={20}/></div>)}</div></Panel></section>}
 </div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-black uppercase tracking-wider text-slate-500">{label}</span><div className="[&_input]:w-full [&_input]:rounded-2xl [&_input]:border [&_input]:border-slate-200 [&_input]:bg-white [&_input]:px-4 [&_input]:py-3 [&_input]:text-sm [&_input]:font-semibold [&_textarea]:w-full [&_textarea]:rounded-2xl [&_textarea]:border [&_textarea]:border-slate-200 [&_textarea]:bg-white [&_textarea]:px-4 [&_textarea]:py-3 [&_textarea]:text-sm">{children}</div></label>}
function Panel({title,subtitle,icon,children}:{title:string;subtitle:string;icon:React.ReactNode;children:React.ReactNode}){return <div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100 sm:p-7"><div className="flex items-center gap-3">{icon}<div><h2 className="text-xl font-black text-[#071b3a]">{title}</h2><p className="text-xs text-slate-500">{subtitle}</p></div></div>{children}</div>}
function Stat({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <div className="rounded-2xl bg-white/10 p-4 text-center"><div className="flex justify-center text-indigo-100">{icon}</div><p className="mt-1 text-2xl font-black">{value}</p><p className="text-[11px] text-indigo-100">{label}</p></div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-slate-200 p-6 text-center text-sm text-slate-500">{text}</div>}
